// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// Türkçe.
extension Strings {
    static let tr = Strings(
        statusIdleTooltip: "Vorssaint: normal uyku",
        statusActiveUntil: "Vorssaint: şu zamana kadar uyanık",
        statusActiveIndefinite: "Vorssaint: süresiz uyanık",
        menuEnableAwake: "Uyanık tutmayı etkinleştir",
        menuDisableAwake: "Uyanık tutmayı kapat",
        menuActivateFor: "Şu süreyle etkinleştir…",
        menuSettings: "Ayarlar…",
        menuAbout: "Vorssaint Hakkında",
        menuQuit: "Vorssaint'ten Çık",
        menuHide: "Vorssaint'i Gizle",
        menuHideOthers: "Diğerlerini Gizle",
        menuShowAll: "Tümünü Göster",
        menuEdit: "Düzen",
        menuUndo: "Geri Al",
        menuRedo: "Yinele",
        menuCut: "Kes",
        menuCopy: "Kopyala",
        menuPaste: "Yapıştır",
        menuSelectAll: "Tümünü Seç",
        menuWindow: "Pencere",
        menuMinimize: "Küçült",
        menuZoom: "Yakınlaştır",
        menuClose: "Kapat",

        minutes15: "15 dakika",
        minutes30: "30 dakika",
        hour1: "1 saat",
        hours2: "2 saat",
        hours4: "4 saat",
        hours8: "8 saat",
        indefinitely: "Süresiz",
        indefinite: "Süresiz",

        panelAwake: "Mac uyanık",
        panelNormalSleep: "Normal uyku",
        panelSettings: "Ayarlar",
        panelQuit: "Çık",
        panelHotkeyHint: "Kısayol açıp kapatır",

        keepAwakeTitle: "Uyanık tut",
        keepAwakeEndsIn: "Kalan süre",
        keepAwakeUntilDisabled: "Sen kapatana kadar etkin",
        keepAwakeNormalRules: "Mac normal enerji kurallarını izler",
        keepAwakeOptions: "Seçenekler",
        keepAwakeMouseJiggle: "İmleci hafifçe oynat",
        keepAwakeMouseJiggleCaption: "Oturum sırasında seçilen aralıkta imleci biraz oynatır.",
        keepAwakeMouseJiggleInterval: "Aralık",
        keepAwakeIconTintLabel: "Etkin simge rengi",
        keepAwakeIconTintOrange: "Turuncu",
        keepAwakeIconTintGreen: "Yeşil",
        keepAwakeIconTintBlue: "Mavi",
        keepAwakeIconTintPurple: "Mor",
        keepAwakeIconTintPink: "Pembe",
        keepAwakeIconTintNone: "Renk yok",
        durationLabel: "Süre",
        clamshellTitle: "Kapak kapalıyken devam et",
        clamshellOnCaption: "Uyku tamamen kapalı. Gücü göz önünde bulundur",
        clamshellNeedsSession: "“Uyanık tut” etkinken uygulanır",
        clamshellReady: "Hazır. Parola istemeden açılıp kapanır",
        clamshellNeedsPassword: "Yönetici parolasını bir kez isteyecek",

        systemSection: "Sistem",
        temperatures: "Sıcaklıklar",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "Pil",
        usageSection: "Donanım kullanımı",
        memorySection: "Bellek",
        memoryPressure: "Basınç",
        pressureNormal: "Normal",
        pressureWarning: "Dikkat",
        pressureCritical: "Kritik",
        monitorUnavailable: "Bu Mac'te sensörler kullanılamıyor",
        energyAppsTitle: "Önemli enerji kullanan uygulamalar",
        energyAppsIdle: "Önemli enerji kullanımı yok",

        notifySessionEndedTitle: "Oturum bitti",
        notifySessionEndedBody: "Süre doldu. Mac yeniden normal şekilde uyuyacak.",
        notifyBatteryTitle: "Vorssaint devre dışı",
        notifyBatteryBody: "Pil düşük. Şarjı korumak için normal uyku geri yüklendi.",
        adminPromptClamshellOn: "Vorssaint'in, Mac'i kapak kapalıyken çalıştırmak için parolana ihtiyacı var.",
        adminPromptClamshellOff: "Vorssaint'in, Mac'in normal uykusunu geri yüklemek için parolana ihtiyacı var.",
        adminPromptRecover: "Mac'in uykusu kapalıyken Vorssaint kapandı. Normal uykuyu geri yüklemek için parolayı gir.",
        adminPromptSudoersInstall: "Vorssaint, parola sormadan kapak kapalı modunu açıp kapatmak için kısıtlı bir kural oluşturacak (yalnızca pmset disablesleep). Parolanın gerektiği tek zaman bu.",
        adminPromptSudoersRemove: "Vorssaint, parolasız kapak kapalı kuralını kaldıracak.",

        settingsTitle: "Vorssaint Ayarları",
        tabGeneral: "Genel",
        tabEnergy: "Enerji",
        tabMouse: "Fare",
        tabSwitcher: "Değiştirici",
        tabAdvanced: "Gelişmiş",
        tabAbout: "Hakkında",
        tabReleaseNotes: "Yenilikler",
        releaseNotesOnUpdateToggle: "Güncellemeden sonra yenilikleri göster",
        whatsNewDontShowAgain: "Bir daha gösterme",
        previewSizeLabel: "Önizleme boyutu",
        previewSizeNormal: "Normal",
        previewSizeLarge: "Büyük",
        previewSizeXLarge: "Çok büyük",
        settingsGroupFeatures: "Özellikler",
        advancedResetSection: "İzinler",
        advancedResetDescription: "Vorssaint'e verdiğin tüm izinleri (Erişilebilirlik, Ekran Kaydı, Tam Disk Erişimi ve diğerleri), oturum açma öğesini ve kapak kapalı kuralını kaldırır. Sıfırdan başlamak veya kaldırmadan önce temizlemek için kullanışlıdır. Uygulama yüklü kalır.",
        advancedClearButton: "Tüm izinleri temizle",
        advancedCleared: "İzinler temizlendi.",
        advancedClearConfirmTitle: "Tüm izinler temizlensin mi?",
        advancedClearConfirmBody: "İzin gerektiren özellikler, yeniden izin verene kadar çalışmaz. Ayarların korunur.",
        advancedUninstallSection: "Kaldır",
        advancedUninstallDescription: "Yukarıdakilerin hepsini yapar, ardından tercihleri kaldırır ve Vorssaint'i Çöp Sepeti'ne taşır; geride hiçbir şey bırakmaz. İş bitince uygulama kapanır. İstediğin zaman yeniden yükleyebilirsin.",
        advancedUninstallButton: "Vorssaint'i tamamen kaldır",
        advancedUninstallConfirmTitle: "Vorssaint kaldırılsın mı?",
        advancedUninstallConfirmBody: "Vorssaint izinlerini temizleyecek, tercihlerini kaldıracak ve Çöp Sepeti'ne taşınıp kapanacak. Bu işlem uygulama içinden geri alınamaz, ama Çöp Sepeti'ni boşaltana kadar orada kalır.",

        launchAtLogin: "Oturum açınca başlat",
        languageLabel: "Dil",
        menuBarSection: "Menü çubuğu",
        showCountdown: "Kalan süreyi simgenin yanında göster",
        globalHotkeySection: "Genel kısayol",
        hotkeyToggle: "“Uyanık tut” kısayolunu etkinleştir",
        hotkeyCaption: "Her uygulamada çalışır, ek izin gerekmez.",

        sessionSection: "Oturum",
        defaultDurationLabel: "Varsayılan süre",
        keepAwakeAutoStart: "Uygulama açılınca etkinleştir",
        keepAwakeAutoStartCaption: "“Uyanık tut”u otomatik başlatır.",
        batteryProtectionSection: "Pil koruması",
        batteryDisableBelow: "Pil şu seviyenin altına düşünce kapat",
        batteryNever: "Asla",
        batteryProtectionCaption: "Unutulan bir oturumun MacBook pilini tüketmesini önler.",
        clamshellSection: "Kapak kapalı",
        configuring: "Yapılandırılıyor…",
        sudoersFailed: "Kapak kapalı modu açılamadı. Tekrar dene.",
        clamshellExplanation: "“Kapak kapalıyken devam et”, “Uyanık tut” etkinken uykuyu tamamen kapatır ve oturum bittiğinde veya uygulama kapandığında otomatik geri alınır. Güce bağlıyken kullanman önerilir.",

        scrollSection: "Kaydırma",
        invertMouseScroll: "Fare kaydırmasını ters çevir",
        invertMouseScrollCaption: "Fare tekerleği yönünü tersine çevirir.",
        scrollTrackpadNote: "İzleme dörtgenine dokunulmaz: macOS doğal kaydırması korunur.",
        scrollActiveNow: "Fare kaydırması şu anda ters çevriliyor",

        switcherSection: "Uygulama değiştirici",
        switcherEnable: "Vorssaint değiştiricisini kullan",
        switcherEnableCaption: "Aynı uygulamanın birden çok penceresi dahil, gerçek küçük resimlerle pencereler arasında geçiş yap.",
        switcherUsageHint: "Gezinmek için kısayolu basılı tut; pencereyi etkinleştirmek için bırak. Shift veya ← geri gider; Q seçili uygulamadan çıkar; Esc iptal eder.",
        switcherNoWindows: "Açık pencere yok",
        switcherIconRowMode: "⌘Tab'i büyük simgelerle göster",
        switcherIconRowModeCaption: "Her uygulama için bir simge ve üstünde o uygulamanın pencere önizlemelerini gösterir.",
        switcherShortcutHintApps: "Uygulamalar",
        switcherShortcutHintWindows: "Pencereler",
        switcherMergeTabs: "Uygulama başına bir giriş göster",
        switcherMergeTabsCaption: "Değiştiricide pencere başına bir giriş yerine, bir uygulamanın tüm pencerelerini tek girişte toplar.",
        switcherShowFinder: "Penceresiz Finder'ı göster",
        switcherShowFinderCaption: "Açık Finder penceresi olmasa bile Finder'ı değiştiricide gösterir.",
        dockPreviewName: "Dock Preview",
        dockPreviewEnable: "Dock'tan pencereleri önizle",
        dockPreviewEnableCaption: "Pencerelerini önizlemek ve göz atmak için Dock'ta açık bir uygulamanın üzerine gel.",
        dockPreviewActiveNow: "Dock'ta etkin",
        dockPreviewMagnificationBlocked: "Bunu kullanmak için Dock büyütmeyi kapat.",
        dockPreviewDockUnavailable: "Dock öğeleri okunamadı.",
        dockPreviewAutohideBeta: "Beta. Bazı hatalarla karşılaşabilirsin.",
        dockPreviewOpenWindow: "Pencereyi aç",
        dockPreviewCloseWindow: "Pencereyi kapat",
        dockPreviewMinimizeWindow: "Pencereyi küçült",
        dockPreviewRestoreWindow: "Pencereyi geri yükle",
        dockPreviewPinPanel: "Önizlemeyi sabitle",
        dockPreviewUnpinPanel: "Önizleme sabitlemesini kaldır",
        dockPreviewPinned: "Sabitlendi",
        dockPreviewClosePanel: "Önizlemeyi kapat",
        dockPreviewPreviousWindow: "Önceki pencere",
        dockPreviewNextWindow: "Sonraki pencere",
        dockPreviewIntroPeek: "Göz atmak için küçük resmin üzerine gel. Pencereyi açmak için tıkla.",
        dockPreviewIntroSettingsHint: "Bunu daha sonra Ayarlar › Değiştirici bölümünden değiştirebilirsin.",
        dockPreviewIntroLater: "Şimdi değil",
        dockPreviewIntroEnable: "Dock Preview'i etkinleştir",
        dockPreviewIntroMagnificationAction: "Etkinleştirmek için Dock büyütmeyi kapat.",

        cutPasteName: "Kes ve yapıştır",
        cutPasteEnable: "Finder'da dosya kes ve yapıştır",
        cutPasteEnableCaption: "Finder'da dosya ve klasörleri kesmek için ⌘X, taşımak için ⌘V kullan.",
        cutPasteHowTitle: "Nasıl kullanılır",
        cutPasteStep1: "Finder'da öğeleri seç ve kesmek için ⌘X'e bas.",
        cutPasteStep2: "Hedef klasörü aç ve oraya taşımak için ⌘V'ye bas.",
        cutPasteTextNote: "Metin alanlarında (yeniden adlandırma gibi) ⌘X ve ⌘V normal çalışmaya devam eder.",
        cutPasteActiveNow: "Finder'da kesmeye hazır",
        cutPasteAutomationNote: "İlk seferde macOS, Finder'ı denetlemek için izin ister.",
        cutReadyTitle: "Kesildi",
        cutReadyHint: "taşımak için hedef klasörde",
        cutCancel: "Kesmeyi iptal et",
        cutDoneTitle: "Taşındı!",
        cutMovedSingular: "1 öğe taşındı",
        cutMovedPluralFormat: "%d öğe taşındı",
        cutSomeFailed: "Bazı öğeler taşınamadı",

        autoQuitName: "Kapatınca çık",
        autoQuitEnable: "Son penceresi kapanınca uygulamadan çık",
        autoQuitEnableCaption: "Bir uygulamanın son penceresini kapatmak uygulamadan da çıkar.",
        autoQuitActiveNow: "Etkin ve pencereleri izliyor",
        autoQuitHowTitle: "Nasıl çalışır",
        autoQuitStep1: "Bir uygulamanın son penceresini kapat (⌘W veya kırmızı düğme).",
        autoQuitStep2: "Uygulama kendiliğinden çıkar. “Değişiklikler kaydedilsin mi?” iletişimleri yine görünür.",
        autoQuitPredictableNote: "Normalde penceresiz çalışan uygulamalardan asla çıkılmaz.",
        autoQuitExceptionsTitle: "İstisnalar",
        autoQuitExceptionsCaption: "Bu listedeki uygulamalar penceresiz kalsa bile açık kalır.",
        autoQuitExceptionsEmpty: "İstisna yok",
        autoQuitAddApp: "Uygulama ekle…",

        uninstallerName: "Kaldırıcı",
        uninstallerEnableCaption: "Bir uygulamayı geride bıraktığı önbellekler, tercihler, günlükler ve kalıntılarla birlikte kaldırır.",
        uninstallerStep1: "Bir uygulamayı Ayarlar'a sürükle veya listeden seç.",
        uninstallerStep2: "Bulunan dosyaları ve kapladıkları alanı gözden geçir.",
        uninstallerStep3: "İstediğini Çöp Sepeti'ne taşı. Hiçbir şey kalıcı olarak silinmez.",
        uninstallerMenuItem: "Bir uygulamayı kaldır…",
        uninstallerDropTitle: "Buraya bir uygulama sürükle",
        uninstallerDropSubtitle: "veya taramak için birini seç",
        uninstallerChoose: "Uygulama seç…",
        uninstallerPickerTitle: "Uygulama seç",
        uninstallerPickerSearch: "Uygulamalarda ara",
        uninstallerPickerEmpty: "Uygulama bulunamadı",
        uninstallerEmptyNote: "Onayın olmadan hiçbir şey kaldırılmaz.",
        uninstallerFDANote: "Daha kapsamlı tarama için Tam Disk Erişimi ver.",
        uninstallerFDAGrant: "Erişim ver…",
        uninstallerFDAHint: "Listede Vorssaint'i aç. Orada yoksa + düğmesine tıkla ve Uygulamalar'dan Vorssaint'i seç. Erişim yalnızca uygulamayı yeniden açtıktan sonra geçerli olur.",
        uninstallerFDARelaunch: "Şimdi yeniden başlat",
        uninstallerScanning: "Dosyalar taranıyor…",
        uninstallerRemoving: "Çöp Sepeti'ne taşınıyor…",
        uninstallerFoundTitle: "bulundu",
        uninstallerSelectedFormat: "%d / %d seçili",
        uninstallerRemove: "Çöp Sepeti'ne Taşı",
        uninstallerCancel: "İptal",
        uninstallerDoneTitle: "Tamamlandı!",
        uninstallerFreedFormat: "%@ geri kazanıldı",
        uninstallerSomeFailed: "Bazı öğeler Çöp Sepeti'ne taşınamadı.",
        uninstallerAnother: "Başka uygulama kaldır",
        uninstallerCatApp: "Uygulama",
        uninstallerCatSupport: "Destek",
        uninstallerCatCaches: "Önbellekler",
        uninstallerCatPreferences: "Tercihler",
        uninstallerCatContainers: "Kapsayıcılar",
        uninstallerCatLogs: "Günlükler",
        uninstallerCatState: "Kaydedilen durum",
        uninstallerCatOther: "Diğer",

        urlCleanerName: "URL temizle",
        urlCleanerEnable: "Kopyalanan URL'leri temizle",
        urlCleanerEnableCaption: "Kopyalanan bağlantılardan izleme parametrelerini kaldırır.",
        urlCleanerActiveNow: "Etkin ve panoyu izliyor",
        urlCleanerManualTitle: "Şimdi temizle",
        urlCleanerInputPlaceholder: "Bir URL yapıştır",
        urlCleanerOutputPlaceholder: "Temiz URL burada görünür",
        urlCleanerCleanButton: "Temizle",
        urlCleanerPasteButton: "Yapıştır",
        urlCleanerCopyButton: "Kopyala",
        urlCleanerClearButton: "Alanı temizle",
        urlCleanerNoURL: "Geçerli bir URL yapıştır.",
        urlCleanerNoChange: "Temizlenecek bir şey yok.",
        urlCleanerCleaned: "URL temizlendi.",
        urlCleanerCopied: "Kopyalandı.",
        urlCleanerLocalNote: "Yerel. Ağ yok.",

        homebrewName: "Homebrew",
        homebrewEnableCaption: "Formülleri ve cask'leri ara, yükle ve kaldır.",
        homebrewMissingTitle: "Homebrew bulunamadı",
        homebrewMissingBody: "Vorssaint, resmi Homebrew yükleyicisiyle Terminal'i açabilir. Terminal adımları gösterir ve gerekirse parolanı ister.",
        homebrewInstallHomebrew: "Homebrew yükle",
        homebrewInstallHomebrewCaption: "Terminal bitirdiğinde buraya dön ve Yenile'ye tıkla.",
        homebrewInstallHomebrewOpened: "Yükleyici Terminal'de açıldı.",
        homebrewShellSetupTitle: "Terminal kurulumunu tamamla",
        homebrewShellSetupBody: "Homebrew yüklü, ancak Terminal brew komutunu henüz bulamayabilir. Vorssaint, kurulum komutuyla Terminal'i açabilir.",
        homebrewShellSetupButton: "Terminal'i ayarla",
        homebrewShellSetupOpened: "Komut Terminal'de açıldı. Sonra buraya dön ve Yenile'ye tıkla.",
        homebrewRefresh: "Yenile",
        homebrewSearchPlaceholder: "Paket ara",
        homebrewKeyboardHint: "Boşluk veya Return macOS panelini kapatır. Arama düğmesini kullan.",
        homebrewSearchButton: "Ara",
        homebrewSearchResults: "Sonuçlar",
        homebrewInstalled: "Yüklü",
        homebrewAll: "Tümü",
        homebrewFormulas: "Formüller",
        homebrewCasks: "Cask'ler",
        homebrewNoPackages: "Paket bulunamadı",
        homebrewNoSelection: "Yüklü bir paket seç veya yenisini ara.",
        homebrewDetailsTitle: "Paket ayrıntıları",
        homebrewInstall: "Yükle",
        homebrewUninstall: "Kaldır",
        homebrewUpgrade: "Güncelle",
        homebrewUpgradeAll: "Tümünü güncelle",
        homebrewUpdateHomebrew: "Homebrew'i güncelle",
        homebrewAllPackages: "paket",
        homebrewOpenTerminal: "Terminal'i aç",
        homebrewCancelOperation: "İptal",
        homebrewClearLog: "Günlüğü temizle",
        homebrewLogTitle: "Günlük",
        homebrewVersion: "Sürüm",
        homebrewDescription: "Tür",
        homebrewHomepage: "Web sitesini aç",
        homebrewPopularity: "Popülerlik",
        homebrewPopularityFormat: "%@ yükleme, %@ gün içinde",
        homebrewInstalledBadge: "Yüklü",
        homebrewNotInstalledBadge: "Yüklü değil",
        homebrewUpdates: "Güncellemeler",
        homebrewUpdateAvailableBadge: "Güncelleme var",
        homebrewLatestVersion: "En son",
        homebrewConfirmInstallTitle: "Homebrew ile yüklensin mi?",
        homebrewConfirmInstallBodyFormat: "Homebrew %@ paketini indirip yükleyecek. Bağımlılıklar da yüklenebilir.",
        homebrewConfirmUninstallTitle: "Homebrew ile kaldırılsın mı?",
        homebrewConfirmUninstallBodyFormat: "Homebrew %@ paketini kaldıracak. Yapılandırma dosyaları sistemde kalabilir.",
        homebrewConfirmUpgradeTitle: "Homebrew ile güncellensin mi?",
        homebrewConfirmUpgradeBodyFormat: "Homebrew %@ paketinin en son sürümünü indirip uygulayacak. Bağımlılıklar da güncellenebilir.",
        homebrewConfirmUpgradeAllTitle: "Tümü Homebrew ile güncellensin mi?",
        homebrewConfirmUpgradeAllBody: "Homebrew, güncellemesi bulunan paketlerin en son sürümlerini indirip uygulayacak. Bağımlılıklar da güncellenebilir.",
        homebrewConfirmUpdateHomebrewTitle: "Homebrew güncellensin mi?",
        homebrewConfirmUpdateHomebrewBody: "Homebrew en son bilgileri alacak ve ardından paketlerini yeniden yükleyecek.",
        homebrewTerminalFallback: "Bu işlem, yönetici parolasını istemek için Terminal'e ihtiyaç duyar. Vorssaint parolaları yakalamaz.",
        homebrewLoading: "Yükleniyor…",
        homebrewSearchEmpty: "Sonuç yok",
        homebrewOperationInstallFormat: "%@ yükleniyor",
        homebrewOperationUninstallFormat: "%@ kaldırılıyor",
        homebrewOperationUpgradeFormat: "%@ güncelleniyor",
        homebrewOperationUpgradeAll: "Paketler güncelleniyor",
        homebrewOperationUpdateHomebrew: "Homebrew güncelleniyor",
        homebrewOperationInstalledFormat: "%@ yüklendi.",
        homebrewOperationUninstalledFormat: "%@ kaldırıldı.",
        homebrewOperationUpgradedFormat: "%@ güncellendi.",
        homebrewOperationUpgradedAll: "Paketler güncellendi.",
        homebrewOperationUpdatedHomebrew: "Homebrew güncellendi.",
        homebrewOperationFailedFormat: "%@ tamamlanamadı.",
        homebrewOperationCancelled: "İşlem iptal edildi.",
        homebrewOperationPreparing: "Hazırlanıyor...",
        homebrewOperationDownloading: "Dosyalar indiriliyor...",
        homebrewOperationInstalling: "Dosyalar yükleniyor...",
        homebrewOperationUninstalling: "Dosyalar kaldırılıyor...",
        homebrewOperationUpgrading: "Dosyalar güncelleniyor...",
        homebrewOperationFinalizing: "Bitiriliyor...",
        homebrewOperationRefreshing: "Liste yenileniyor...",
        homebrewOperationTerminal: "Terminal'de devam et.",
        homebrewOperationElapsedFormat: "%@ geçti",
        homebrewOperationShowDetails: "Ayrıntıları göster",
        homebrewOperationHideDetails: "Ayrıntıları gizle",
        homebrewOperationTechnicalLog: "Teknik ayrıntılar",
        homebrewOperationProgressUnknown: "Homebrew henüz yüzde bildirmedi.",

        mediaName: "Medya",
        mediaEnableCaption: "Videoları ve görselleri sıkıştır, GIF oluştur ve metni yerel olarak çıkar.",
        mediaLocalNote: "Yerel. Ağ yok.",
        mediaToolVideo: "Video",
        mediaToolGIF: "GIF",
        mediaToolImage: "Görsel",
        mediaToolText: "Metin",
        mediaSelectFile: "Dosya seç",
        mediaDropHint: "Buraya dosya bırak veya seçmek için tıkla.",
        mediaOutput: "Çıktı",
        mediaOutputAutomatic: "Otomatik",
        mediaChooseOutput: "Hedef",
        mediaStartVideo: "Videoyu sıkıştır",
        mediaStartGIF: "GIF oluştur",
        mediaStartImage: "Görseli sıkıştır",
        mediaStartText: "Metni çıkar",
        mediaCancel: "İptal",
        mediaStartTime: "Başlangıç",
        mediaEndTime: "Bitiş",
        mediaQuality: "Sıkıştırma",
        mediaCompressionLow: "Düşük",
        mediaCompressionMedium: "Orta",
        mediaCompressionHigh: "Yüksek",
        mediaMaxSize: "Boyut",
        mediaWidth: "Genişlik",
        mediaFPS: "FPS",
        mediaKeepAudio: "Sesi koru",
        mediaCodec: "Codec",
        mediaFormat: "Biçim",
        mediaStripMetadata: "Meta verileri kaldır",
        mediaLoopGIF: "GIF'i döngüye al",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "Doğru",
        mediaOCRFast: "Hızlı",
        mediaLanguageCorrection: "Dil düzeltmesi",
        mediaTextOutputNote: "Çıkarılan metin kopyalanabilir ve TXT olarak kaydedilebilir.",
        mediaRunning: "İşleniyor",
        mediaCompleted: "Tamamlandı",
        mediaCancelled: "İptal edildi.",
        mediaOpenInFinder: "Göster",
        mediaCopyText: "Metni kopyala",
        mediaRunAgain: "Tekrar çalıştır",
        mediaEmptyText: "Metin bulunamadı.",
        mediaResultSavedFormat: "%@ olarak kaydedildi",
        mediaResultSizeFormat: "%@ -> %@",
        mediaErrorNoFile: "Önce bir dosya seç.",
        mediaErrorNoVideo: "Bu dosyada video izi yok.",
        mediaErrorSameOutput: "Özgün dosyadan farklı bir hedef seç.",
        mediaErrorUnsupported: "Biçim macOS tarafından desteklenmiyor.",

        shelfName: "Raf",
        shelfEnable: "Dosya sürüklemek için geçici alan",
        shelfEnableCaption: "Dosyaları, görselleri ve metinleri toplamak, sonra istediğin yere sürüklemek için yüzen bir alan.",
        shelfHowTitle: "Nasıl kullanılır",
        shelfStep1: "Kısayolla veya sürüklerken fareyi sallayarak aç.",
        shelfStep2: "Dosyaları, görselleri, bağlantıları veya metni tutması için üzerine bırak.",
        shelfStep3: "Gerektiğinde her öğeyi istediğin uygulamaya geri sürükle.",
        shelfShakeToggle: "Sürüklerken fareyi sallayınca aç",
        shelfShakeCaption: "Bir öğeyi tutarken imleci hızlıca sallarsan raf imlecin yanında belirir.",
        shelfHotkeyLabel: "Kısayol",
        shelfOpenNow: "Şimdi aç",
        shelfNoPermission: "İzin gerektirmez.",
        shelfMenuItem: "Rafı aç",
        shelfTitle: "Raf",
        shelfEmpty: "Öğeleri buraya sürükle",
        shelfClearAll: "Tümünü temizle",
        shelfRemoveSelected: "Seçilenleri kaldır",
        shelfSelectedFormat: "%d seçili",
        shelfHint: "Seçmek için tıkla. Kullanmak için dışarı sürükle.",
        shelfItemImage: "Görsel",

        breakdownMeasuring: "Ölçülüyor…",

        mixerSection: "Ses mikseri",
        mixerEmpty: "Ses kullanan uygulamalar burada görünür",
        mixerUnavailable: "macOS 14.4 ve sonrasında kullanılabilir",
        mixerPermissionBody: "Uygulama başına ses düzeyini ayarlamak için Sistem Ayarları'nda “Ekran ve Sistem Sesi Kaydı”na izin ver. Ses hiçbir zaman kaydedilmez.",
        mixerResetTooltip: "%100'e sıfırla",
        mixerOutputDefault: "Varsayılan",
        mixerOutputCurrent: "geçerli",
        mixerOutputUnavailable: "Çıkış kullanılamıyor",
        mixerOutputFallback: "Bu aygıt geri dönene kadar varsayılan kullanılıyor.",
        mixerOutputTooltip: "Çıkış seç",
        mixerSystemOutputTitle: "Çıkış",
        mixerSystemOutputNoDevices: "Çıkış bulunamadı",
        mixerSystemOutputTooltip: "Sistem çıkışını seç",
        mixerSystemOutputErrorFormat: "Geçiş yapılamadı: %@",
        mixerLowerOnHeadphonesDisconnect: "Kulaklık bağlantısı kesilince sesi düşür",
        mixerLowerOnHeadphonesDisconnectCaption: "Kablolu veya Bluetooth kulaklık bağlantısı kesildiğinde çıkışı seçilen seviyeye ayarlar.",
        mixerHeadphonesDisconnectVolume: "Bağlantı kesilince ses",
        soundOutputSwitcherTitle: "Çıkış değiştirici",
        soundOutputSwitcherEnable: "Çıkışları kısayolla değiştir",
        soundOutputSwitcherCaption: "Çıkışları seç ve kısayolla bir sonraki kullanılabilir çıkışa geç.",
        soundOutputSwitcherDevices: "Döngüdeki çıkışlar",
        soundOutputSwitcherNoAvailableSelection: "En az bir kullanılabilir çıkış seç.",
        mixerInputTitle: "Mikrofon",
        mixerInputNoDevices: "Mikrofon bulunamadı",
        mixerInputUnavailable: "Mikrofon kullanılamıyor",
        mixerInputFallback: "Bu mikrofon geri dönene kadar varsayılan kullanılıyor.",
        mixerInputTooltip: "Mikrofon seç",
        mixerInputErrorFormat: "Geçiş yapılamadı: %@",

        updatesSection: "Güncellemeler",
        autoCheckToggle: "Güncellemeleri otomatik denetle",
        checkNowButton: "Şimdi denetle",
        updateChecking: "Denetleniyor…",
        updateUpToDate: "En son sürümdesin.",
        updateAvailablePrefix: "Güncelleme var:",
        updateInstallButton: "İndir ve yükle",
        updateDownloading: "Güncelleme indiriliyor…",
        updateInstalling: "Yükleniyor ve yeniden başlatılıyor…",
        updateFailedPrefix: "Denetlenemedi:",
        updateLastChecked: "Son denetleme:",
        updateNotifyTitle: "Vorssaint güncellemesi",
        menuCheckUpdates: "Güncellemeleri denetle…",

        permissionRequired: "İzin gerekli",
        permissionAccessibility: "Erişilebilirlik",
        permissionScreenRecording: "Ekran Kaydı",
        permissionGranted: "Verildi",
        permissionMissing: "Verilmedi",
        permissionOpenSettings: "Sistem Ayarları'nı aç…",
        permissionRequest: "Erişim ver",
        permissionRestartNote: "macOS izin verdikten sonra uygulamayı yeniden açmanı isteyebilir.",

        aboutDescription: "Mac'in için bir yardımcı merkez.\nEnerji, sistem monitörü, kaydırma ve pencere değiştirici, doğrudan menü çubuğunda.",
        versionPrefix: "Sürüm",
        reviewIntro: "Tanıtımı incele",
        viewOnGitHub: "GitHub'da görüntüle",

        obContinue: "Devam",
        obBack: "Geri",
        obSkipStep: "Bu adımı atla",
        obStart: "Vorssaint'i aç",
        obStepWelcomeTitle: "Vorssaint'e hoş geldin",
        obStepWelcomeBody: "Günlük macOS kullanımını daha pratik yapan sade bir menü çubuğu yardımcısı.",
        obWelcomeBullet1Title: "Enerji kontrol altında",
        obWelcomeBullet1Body: "Mac'i istediğin kadar, kapak kapalıyken bile uyanık tut.",
        obWelcomeBullet2Title: "Sisteme net bakış",
        obWelcomeBullet2Body: "CPU, GPU ve pil sıcaklıkları, donanım kullanımı ve bellek basıncı gerçek zamanlı.",
        obWelcomeBullet3Title: "Fare ve pencereler, senin tarzın",
        obWelcomeBullet3Body: "Ters fare kaydırması ve küçük resimli pencere değiştirici.",
        obLanguageLabel: "Dil",
        obStepAccessibilityTitle: "Erişilebilirlik",
        obStepAccessibilityBody: "Fare kaydırmasını ters çevirmek ve pencere değiştiricinin klavyeye yanıt vermesi için gereklidir.",
        obAccessibilityWhy: "Uygulama yalnızca fare tekerleğini ve değiştirici kısayolunu izler. Hiçbir şey kaydedilmez veya bir yere gönderilmez.",
        obStepRecordingTitle: "Ekran Kaydı",
        obStepRecordingBody: "Değiştiricinin yalnızca simge yerine gerçek pencere küçük resimleri göstermesini sağlar.",
        obRecordingWhy: "Küçük resimler anlık oluşturulur, bellekte kalır ve Mac'inden çıkmaz. Bu izin olmadan değiştirici simgelerle çalışmaya devam eder.",
        obStepMonitorTitle: "Sistem monitörü",
        obStepMonitorBody: "Panel CPU, GPU ve pil sıcaklıklarını, donanım kullanımını ve bellek basıncını gösterir.",
        obMonitorNoPermission: "İzin gerekmez. Sensörler doğrudan sistemden okunur.",
        obStepOptionalTitle: "İsteğe bağlı özellikler",
        obStepOptionalBody: "Şimdi kullanmak istediklerini aç. Her şeyi daha sonra Ayarlar'dan değiştirebilirsin.",
        obStepStatusTitle: "Kontrol",
        obStepStatusBody: "İstediğin özellikler için her şeyin hazır olduğundan emin ol.",
        obStatusRecheck: "Tekrar denetle",
        obStepDoneTitle: "Her şey hazır!",
        obStepDoneBody: "Vorssaint Mac'inle ilgilenmeye başladı bile.",
        obDoneHint: "Ekranın sağ üstündeki menü çubuğunda kara deliği ara.",
        obWhatsNewTitle: "Bu sürümdeki yenilikler",
        obWhatsNewFallback: "Bu güncelleme en son düzeltmeleri ve iyileştirmeleri içerir.",
        obLanguageUpdateTitle: "Artık kendi dilinde",
        obLanguageUpdateBody: "Vorssaint artık birçok dil konuşuyor. Kullanmak istediğin dili seç; bunu istediğin zaman Ayarlar'dan değiştirebilirsin.",

        tabMonitor: "Monitör",
        monitorMenuBarSection: "Menü çubuğunda",
        monitorMenuBarCaption: "Menü çubuğunda simgenin yanında ne görüneceğini seç.",
        monitorCombineTemperatures: "Kullanımı ve sıcaklığı birleştir",
        monitorCombineTemperaturesCaption: "Aynı öğe için kullanım ve sıcaklık etkinse, bunları tek blokta göster.",
        monitorSeparateMenuBarMetrics: "Metrikleri kendi öğelerine ayır",
        monitorSeparateMenuBarMetricsCaption: "Etkin blokları menü çubuğunda ayırır ve birleştirme açıkken kullanım ile sıcaklığı birlikte tutar.",
        monitorNetworkUploadFirst: "Yükleme indirme üstünde",
        monitorShowCPU: "CPU",
        monitorShowMemory: "Bellek",
        monitorShowNetwork: "Ağ",
        monitorShowPowerLabel: "Güç",
        monitorIntervalLabel: "Güncelleme aralığı",
        monitorInterval1: "1 saniye",
        monitorInterval2: "2 saniye",
        monitorInterval5: "5 saniye",
        monitorPanelSection: "Panelde",
        panelNavigationMode: "Panelde bölümlere göre gezin",
        panelNavigationCaption: "Her seferinde bir bölüm gösterir ve gezinmeyi panelin altına yerleştirir.",
        panelFooterSections: "Bölümler",
        panelFooterList: "Liste",
        fanControlBetaShow: "Fan Control (Beta)'yı panelde göster",
        fanControlBetaSection: "Fan Control",
        fanControlBetaTitle: "Fan Control",
        fanControlBetaStatus: "Otomatik",
        fanControlBetaCaption: "Beta. Her Mac modeli doğrulanana kadar elle denetim kapalı kalır.",
        fanControlModeAutomatic: "Otomatik",
        fanControlModeManual: "Elle",
        betaBadge: "BETA",
        betaFeatureWarning: "Beta. Bazı hatalarla karşılaşabilirsin.",

        networkSection: "Ağ",
        networkDownload: "İndirme",
        networkUpload: "Yükleme",
        networkThisSession: "Bu oturum",
        networkMeasuring: "Ölçülüyor…",
        networkApps: "Ağı kullanan uygulamalar",
        networkAppsIdle: "Şu anda ağı kullanan uygulama yok",

        diskSection: "Diskler",
        diskUsed: "kullanıldı",
        diskFree: "boş",
        diskInternal: "Dahili",
        diskExternal: "Harici",
        diskSelect: "Disk seç",
        diskRead: "Okuma",
        diskWrite: "Yazma",
        diskSMARTStatus: "Durum",
        diskSMARTUnavailable: "Bu disk için SMART kullanılamıyor",
        diskTotalRead: "Toplam okuma",
        diskTotalWritten: "Toplam yazma",
        diskTemperature: "Sıcaklık",
        diskHealth: "Sağlık",
        diskPowerCycles: "Güç döngüleri",
        diskPowerOnHours: "Çalışma saatleri",
        diskUnsafeShutdowns: "Güvensiz kapanmalar",
        diskMediaErrors: "Medya hataları",
        diskEject: "Çıkar",
        diskEjectAll: "Tümünü çıkar",
        diskEjecting: "Çıkarılıyor…",
        diskReadyToRemove: "Kaldırmaya hazır",
        diskEjectFailed: "Çıkarılamadı",
        diskProtectionCaption: "Bağlantıyı kesmeden önce çıkar.",
        diskNoExternal: "Çıkarılmaya hazır harici disk yok.",
        diskOpenInFinder: "Aç",
        diskStorageSettings: "Depolama",
        diskNoDisks: "Bağlı disk bulunamadı.",

        powerSection: "Güç",
        powerSystem: "Sistem",
        powerAdapter: "Adaptör",
        powerBattery: "Pil",
        powerCharging: "Şarj oluyor",
        powerOnBattery: "Pilde",
        powerPluggedIn: "Prize bağlı",
        powerUnavailable: "Bu Mac'te güç metrikleri kullanılamıyor",
        powerAdapterMaxFormat: "%@ maks.",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "CPU sıcaklığı",
        monitorShowGPUTemperature: "GPU sıcaklığı",
        monitorShowBatteryTemperature: "Pil sıcaklığı",
        monitorShowPeripheralBattery: "Çevre birimi pili",
        peripheralBatteryNoDevices: "Aygıt bulunamadı",
        monitorGraphsSection: "Grafikler",
        monitorGraphsCaption: "Hangi metriklerin zaman içinde grafik göstereceğini seç.",

        updateBannerTitle: "Güncelleme var",
        updateBannerAction: "Güncelle",
        obStepMenuBarTitle: "Menü çubuğunda metrikler",
        obStepMenuBarBody: "Simgenin yanında ne gösterileceğini seç. Yukarıdaki önizleme canlı güncellenir.",
        obStepMenuBarNote: "Yeni: Ağ ve Güç blokları ve panelde grafikler. Tümünü daha sonra Ayarlar › Monitör bölümünde ince ayarlayabilirsin.",
        monitorMenuBarPresetLabel: "Stil",
        menuBarPresetReadable: "Okunaklı",
        menuBarPresetDense: "Sıkı",
        monitorLabelStyleLabel: "Etiketler",
        menuBarLabelStyleCompact: "Kompakt",
        menuBarLabelStyleClassic: "Klasik",
        monitorMemoryStyleLabel: "Belleği şöyle göster",
        monitorMemoryPressureDot: "Basınç noktası",
        memoryStyleDot: "Nokta",
        memoryStylePercent: "%",
        memoryStyleBoth: "İkisi de",

        systemUptime: "Çalışma süresi",
        batteryCharge: "Şarj",
        powerHealth: "Pil sağlığı",
        powerCycles: "döngü",
        speedTestRun: "Hız testi",
        speedTestAgain: "Tekrar test et",
        speedTestLatency: "Gecikme",
        speedTestTesting: "Test ediliyor…",
        speedTestFailed: "Test başarısız",

        monitorShowInPanel: "Panelde göster",
        panelHideItem: "Panelden gizle",
        panelShowItem: "Panelde göster",
        panelHiddenItem: "Gizli",
        monitorItemUptime: "Çalışma süresi",
        monitorItemNetSpeed: "Canlı hız",
        monitorItemNetTotals: "Oturum toplamları",
        monitorItemNetTest: "Hız testi",
        monitorItemDiskUsage: "Disk kullanımı",
        monitorItemDiskActivity: "Canlı etkinlik",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "Harici koruma",
        monitorItemDiskTools: "Araçlar",
        monitorPanelConfigHint: "Ne göstereceğini seçmek için bir blok aç.",
        monitorOrderSection: "Bölüm sırası",
        monitorOrderHint: "Panel bölümlerini yeniden sıralamak için sürükle ve her birini göstermek veya gizlemek için göz simgesini kullan.",
        obStepPanelTitle: "Panelde neler var",
        obStepPanelBody: "Her bloğu aç ve simgeye tıkladığında tam olarak ne görüneceğini seç.",
        obStepPanelNavigationTitle: "Bölüm tabanlı panel",
        obStepPanelNavigationBody: "Panel artık altta gezinmeyle her seferinde bir bölüm gösterebilir. Deneyebilmen için bu güncellemede açık geliyor.",

        cleaningMenuItem: "Temizleme Modu",
        utilitiesSection: "Araçlar",
        quickControlsSection: "Denetimler",
        windowMaximizeName: "Pencereleri büyüt",
        windowMaximizeCaption: "Yeşil düğme başka bir Space oluşturmadan pencereyi büyütür.",
        windowMaximizeActiveNow: "Yeşil düğme geçersiz kılma etkin",
        windowMaximizeNeedsAccessibility: "Çalışması için Erişilebilirlik gerekir.",
        keyDebounceName: "Tuş sekmesini filtrele",
        keyDebounceEnable: "Yinelenen tuşları filtrele",
        keyDebounceCaption: "Çok hızlı yinelenen tuş basışlarını filtreler.",
        keyDebounceActiveNow: "Filtre etkin",
        keyDebounceGlobalWindow: "Genel pencere",
        keyDebouncePerKeySection: "Belirli tuşlar",
        keyDebouncePerKeyCaption: "Tuşa özel değerler genel pencereyi geçersiz kılar. Bir tuşu filtrelememek için 0 ms kullan.",
        keyDebounceKeyLabel: "Tuş",
        keyDebounceWindowLabel: "Pencere",
        keyDebounceAddKey: "Tuş ekle",
        keyDebounceNoOverrides: "Belirli tuş ayarı yok.",
        keyDebounceRemoveKey: "Tuşu kaldır",
        cleaningPanelCaption: "Güvenle temizleyebilmen için klavyeyi kilitler.",
        cleaningOverlayTitle: "Klavye temizlik için kilitlendi",
        cleaningOverlaySubtitle: "Kilidi açmak için aynı tuşa 5 kez bas",
        cleaningOverlayUnlock: "Kilidi aç",
        cleaningOverlayMouseHint: "Fare ve izleme dörtgeni çalışmaya devam eder",
        cleaningNeedsAxTitle: "Erişilebilirlik gerekli",
        cleaningNeedsAxBody: "Klavyeyi güvenle kilitlemek için Vorssaint'in Erişilebilirlik iznine ihtiyacı var. Sistem Ayarları'ndan izin ver ve tekrar dene.",
        keyboardCleaningName: "Klavye Temizliği",
        keyboardCleaningToggle: "Klavye temizleme modu",
        keyboardCleaningCaption: "MacBook tuşlarını temizleyebilmen için klavyeyi geçici olarak kilitler.",
        keyboardCleaningActive: "Klavye temizliği açık",
        keyboardCleaningInactive: "Klavye temizliği kapalı",
        keyboardCleaningInputMonitoring: "Giriş İzleme",
        keyboardCleaningNeedsInputMonitoring: "Klavyeyi kilitlemek için Giriş İzleme izni gerekir.",
        keyboardCleaningNoKeyboard: "Kilitlenecek klavye bulunamadı.",
        keyboardCleaningSeizeFailed: "Yerleşik klavyenin özel denetimi alınamadı.",
        keyboardCleaningPartialLock: "Yalnızca bazı klavyeler kilitlendi.",
        keyboardCleaningLockedByHID: "HID özel denetimiyle kilitlendi.",

        tabSupport: "Destek",
        donateHeading: "Vorssaint'i destekle",
        donateMessage: "Herkese açık projelerimin her biri tamamen ücretsizdir ve öyle kalacak: abonelik yok, reklam yok. Onu ayakta tutan tek şey topluluk desteği. Vorssaint sana yardımcı oluyorsa, bir kahvenin gerçekten farkı var.",
        donateButton: "Bana bir kahve al",
        donateThanks: "Burada olduğun için teşekkürler. 🖤",
        supportIntroTitle: "Vorssaint %100 ücretsizdir ve hep öyle kalacak",
        supportIntroMessage: "Uygulamayla boş zamanımda ilgilenmeye devam ediyorum. Sana yardımcı oluyorsa, paylaşarak, GitHub'da yıldız bırakarak veya bana bir kahve alarak basitçe destek olabilirsin. Geliştirmeye devam etmem için çok yardımcı olur.",
        supportIntroStarButton: "Yıldız bırak",
        supportIntroCoffeeButton: "Bana bir kahve al",
        supportIntroLaterButton: "Şimdi değil",
        updateShowcaseTitle: "3.1.4'te yenilikler",
        updateShowcaseMessage: "Bu güncellemedeki başlıca iyileştirmelere hızlıca göz at.",
        updateShowcaseUnavailable: "Video şu anda yüklenemedi. Yine de devam edebilirsin.",
        updateShowcaseRestart: "Yeniden başlat",
        showMenuBarIcon: "Menü çubuğu simgesini göster",
        showMenuBarIconCaption: "Vorssaint simgesi kaybolursa (macOS, çubukta yer kalmadığında menü çubuğu simgelerini gizleyebilir; çentikli Mac'lerde yaygındır), Vorssaint'i Uygulamalar'dan veya Spotlight'tan yeniden aç: bu simgeyi yeniden oluşturur ve hâlâ gizliyse bu pencereyi açar. Buraya zaten ulaşabiliyorsan yukarıdaki düğme de aynısını yapar. Menü çubuğunda daha az simge veya daha az Vorssaint metriği tutmak bunu çok daha az olası kılar.",
        shortcutRecording: "Yeni kısayola bas",
        shortcutReset: "Sıfırla",
        shortcutInvalid: "Bir tuşla birlikte en az Control, Option veya Command kullan.",
        shortcutConflictFormat: "Bu kısayol zaten %@ tarafından kullanılıyor.",
        shortcutUnavailable: "macOS bu kısayolu reddetti. Başka birini seç.",
        shelfShortcutToggle: "Raf kısayolu",
        switcherUsageHintFormat: "Gezinmek için %@ tuşunu basılı tut; pencereyi etkinleştirmek için bırak. Shift veya ← geri gider; Q seçili uygulamadan çıkar; Esc iptal eder."
    )
}
