// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// Español — translated and hand-checked, not machine output.
extension Strings {
    static let es = Strings(
        statusIdleTooltip: "Vorssaint: reposo normal",
        statusActiveUntil: "Vorssaint: activo hasta",
        statusActiveIndefinite: "Vorssaint: activo indefinidamente",
        menuEnableAwake: "Activar mantener activo",
        menuDisableAwake: "Desactivar mantener activo",
        menuActivateFor: "Activar durante…",
        menuSettings: "Ajustes…",
        menuAbout: "Acerca de Vorssaint",
        menuQuit: "Salir de Vorssaint",
        menuHide: "Ocultar Vorssaint",
        menuHideOthers: "Ocultar los demás",
        menuShowAll: "Mostrar todo",
        menuEdit: "Edición",
        menuUndo: "Deshacer",
        menuRedo: "Rehacer",
        menuCut: "Cortar",
        menuCopy: "Copiar",
        menuPaste: "Pegar",
        menuSelectAll: "Seleccionar todo",
        menuWindow: "Ventana",
        menuMinimize: "Minimizar",
        menuZoom: "Zoom",
        menuClose: "Cerrar",

        minutes15: "15 minutos",
        minutes30: "30 minutos",
        hour1: "1 hora",
        hours2: "2 horas",
        hours4: "4 horas",
        hours8: "8 horas",
        indefinitely: "Indefinidamente",
        indefinite: "Indefinido",

        panelAwake: "Mac activo",
        panelNormalSleep: "Reposo normal",
        panelActiveBadge: "ACTIVO",
        panelSettings: "Ajustes",
        panelQuit: "Salir",
        panelHotkeyHint: "⌃⌥⌘K alterna",

        keepAwakeTitle: "Mantener activo",
        keepAwakeEndsIn: "Termina en",
        keepAwakeUntilDisabled: "Activo hasta que lo desactives",
        keepAwakeNormalRules: "El Mac sigue sus reglas de energía normales",
        durationLabel: "Duración",
        clamshellTitle: "Seguir con la tapa cerrada",
        clamshellOnCaption: "Reposo totalmente desactivado. Cuida la energía",
        clamshellNeedsSession: "Se aplica siempre que «Mantener activo» esté activo",
        clamshellReady: "Listo. Se alterna sin contraseña",
        clamshellNeedsPassword: "Pedirá la contraseña de administrador al activarse",

        systemSection: "Sistema",
        temperatures: "Temperaturas",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "Batería",
        usageSection: "Uso del hardware",
        memorySection: "Memoria",
        memoryPressure: "Presión",
        pressureNormal: "Normal",
        pressureWarning: "Precaución",
        pressureCritical: "Crítica",
        monitorUnavailable: "Sensores no disponibles en este Mac",

        notifySessionEndedTitle: "Sesión finalizada",
        notifySessionEndedBody: "Se acabó el tiempo. El Mac volverá a entrar en reposo con normalidad.",
        notifyBatteryTitle: "Vorssaint desactivado",
        notifyBatteryBody: "Batería baja. Se restauró el reposo normal para proteger la carga.",

        adminPromptClamshellOn: "Vorssaint necesita tu contraseña para mantener el Mac activo con la tapa cerrada. Omite esta solicitud en la introducción de la app (Ajustes › Acerca de).",
        adminPromptClamshellOff: "Vorssaint necesita tu contraseña para restaurar el reposo normal del Mac.",
        adminPromptRecover: "Vorssaint se cerró mientras el reposo del Mac estaba desactivado. Introduce la contraseña para restaurar el reposo normal.",
        adminPromptSudoersInstall: "Vorssaint creará una regla restringida (solo pmset disablesleep) para alternar el modo de tapa cerrada sin pedir contraseña. Esta es la única vez que se necesita la contraseña.",
        adminPromptSudoersRemove: "Vorssaint eliminará la regla de tapa cerrada sin contraseña.",

        settingsTitle: "Ajustes de Vorssaint",
        tabGeneral: "General",
        tabEnergy: "Energía",
        tabMouse: "Ratón",
        tabSwitcher: "Selector",
        tabAdvanced: "Avanzado",
        tabAbout: "Acerca de",
        settingsGroupFeatures: "Funciones",
        advancedResetSection: "Permisos",
        advancedResetDescription: "Elimina todos los permisos que concediste a Vorssaint (Accesibilidad, Grabación de pantalla, Acceso total al disco y otros), el ítem de inicio de sesión y la regla de tapa cerrada. Útil para empezar de cero o antes de desinstalar. La app sigue instalada.",
        advancedClearButton: "Borrar todos los permisos",
        advancedCleared: "Permisos borrados.",
        advancedClearConfirmTitle: "¿Borrar todos los permisos?",
        advancedClearConfirmBody: "Las funciones que necesitan permisos dejarán de funcionar hasta que los concedas de nuevo. Tus ajustes se conservan.",
        advancedUninstallSection: "Desinstalar",
        advancedUninstallDescription: "Hace todo lo anterior y, además, elimina las preferencias y mueve Vorssaint a la Papelera, sin dejar rastro. La app se cierra al terminar. Puedes reinstalarla cuando quieras.",
        advancedUninstallButton: "Desinstalar Vorssaint por completo",
        advancedUninstallConfirmTitle: "¿Desinstalar Vorssaint?",
        advancedUninstallConfirmBody: "Vorssaint borrará sus permisos, eliminará sus preferencias y se moverá a la Papelera; después se cerrará. Esto no se puede deshacer desde la app, pero permanece en la Papelera hasta que la vacíes.",

        launchAtLogin: "Abrir al iniciar sesión",
        languageLabel: "Idioma",
        menuBarSection: "Barra de menús",
        showCountdown: "Mostrar el tiempo restante junto al icono",
        globalHotkeySection: "Atajo global",
        hotkeyToggle: "Alternar «Mantener activo» con ⌃⌥⌘K",
        hotkeyCaption: "Funciona en cualquier app, sin permisos adicionales.",

        sessionSection: "Sesión",
        defaultDurationLabel: "Duración predeterminada",
        batteryProtectionSection: "Protección de la batería",
        batteryDisableBelow: "Desactivar cuando la batería baje de",
        batteryNever: "Nunca",
        batteryProtectionCaption: "Evita que una sesión olvidada agote la batería del MacBook.",
        clamshellSection: "Tapa cerrada",
        configuring: "Configurando…",
        sudoersFailed: "No se pudo completar. Comprueba la contraseña e inténtalo de nuevo.",
        clamshellExplanation: "«Seguir con la tapa cerrada» desactiva por completo el reposo mientras «Mantener activo» está activo y se revierte automáticamente cuando la sesión termina o la app se cierra. Es preferible usarlo conectado a la corriente.",

        scrollSection: "Desplazamiento",
        invertMouseScroll: "Invertir el desplazamiento del ratón",
        invertMouseScrollCaption: "Invierte la dirección de la rueda del ratón.",
        scrollTrackpadNote: "El trackpad no se modifica: mantiene el desplazamiento natural de macOS.",
        scrollActiveNow: "Invirtiendo el desplazamiento del ratón ahora",

        switcherSection: "Selector de apps",
        switcherEnable: "Sustituir ⌘Tab por el selector de Vorssaint",
        switcherEnableCaption: "Cambia de ventana con miniaturas reales, incluso entre varias ventanas de la misma app.",
        switcherUsageHint: "Mantén ⌘ y pulsa Tab para navegar; suelta para activar la ventana. Mayúsculas o ← retrocede; Q cierra la app seleccionada; Esc cancela.",
        switcherNoWindows: "No hay ventanas abiertas",
        switcherMergeTabs: "Mostrar una entrada por app",
        switcherMergeTabsCaption: "Agrupa todas las ventanas de una app en una sola entrada del selector, en vez de una por ventana.",

        cutPasteName: "Cortar y pegar",
        cutPasteEnable: "Cortar y pegar archivos en el Finder",
        cutPasteEnableCaption: "Usa ⌘X para cortar y ⌘V para mover archivos y carpetas en el Finder.",
        cutPasteHowTitle: "Cómo se usa",
        cutPasteStep1: "Selecciona ítems en el Finder y pulsa ⌘X para cortarlos.",
        cutPasteStep2: "Abre la carpeta de destino y pulsa ⌘V para moverlos allí.",
        cutPasteTextNote: "En los campos de texto (como al renombrar), ⌘X y ⌘V siguen funcionando con normalidad.",
        cutPasteActiveNow: "Listo para cortar en el Finder",
        cutPasteAutomationNote: "La primera vez, macOS pide permiso para controlar el Finder.",
        cutReadyTitle: "Cortado",
        cutReadyHint: "en la carpeta de destino para mover",
        cutDoneTitle: "¡Movido!",
        cutMovedSingular: "1 ítem movido",
        cutMovedPluralFormat: "%d ítems movidos",
        cutSomeFailed: "Algunos ítems no se pudieron mover",

        autoQuitName: "Salir al cerrar",
        autoQuitEnable: "Salir de una app al cerrar su última ventana",
        autoQuitEnableCaption: "Cerrar la última ventana de una app también la cierra.",
        autoQuitActiveNow: "Activo y vigilando las ventanas",
        autoQuitHowTitle: "Cómo funciona",
        autoQuitStep1: "Cierra la última ventana de una app (⌘W o el botón rojo).",
        autoQuitStep2: "La app se cierra sola. Los diálogos «¿Guardar cambios?» siguen apareciendo.",
        autoQuitPredictableNote: "Las apps que normalmente funcionan sin ventana nunca se cierran.",
        autoQuitExceptionsTitle: "Excepciones",
        autoQuitExceptionsCaption: "Las apps de esta lista permanecen abiertas aunque no tengan ventanas.",
        autoQuitExceptionsEmpty: "Sin excepciones",
        autoQuitAddApp: "Añadir app…",

        uninstallerName: "Desinstalador",
        uninstallerEnableCaption: "Elimina una app junto con las cachés, preferencias, registros y restos que deja atrás.",
        uninstallerStep1: "Arrastra una app a Ajustes o elige una de la lista.",
        uninstallerStep2: "Revisa los archivos encontrados y cuánto espacio ocupan.",
        uninstallerStep3: "Mueve a la Papelera lo que quieras. Nada se elimina de forma permanente.",
        uninstallerMenuItem: "Desinstalar una app…",
        uninstallerDropTitle: "Arrastra una app aquí",
        uninstallerDropSubtitle: "o elige una para analizar",
        uninstallerChoose: "Elegir app…",
        uninstallerEmptyNote: "No se elimina nada sin tu confirmación.",
        uninstallerFDANote: "Concede Acceso total al disco para un análisis más exhaustivo.",
        uninstallerFDAGrant: "Conceder acceso…",
        uninstallerFDAHint: "Activa Vorssaint en la lista. Si no aparece, haz clic en + y elige Vorssaint en Aplicaciones. El acceso solo se aplica después de volver a abrir la app.",
        uninstallerFDARelaunch: "Reabrir ahora",
        uninstallerScanning: "Analizando archivos…",
        uninstallerRemoving: "Moviendo a la Papelera…",
        uninstallerFoundTitle: "encontrado",
        uninstallerSelectedFormat: "%d de %d seleccionados",
        uninstallerRemove: "Mover a la Papelera",
        uninstallerCancel: "Cancelar",
        uninstallerDoneTitle: "¡Listo!",
        uninstallerFreedFormat: "%@ recuperados",
        uninstallerSomeFailed: "Algunos ítems no se pudieron mover a la Papelera.",
        uninstallerAnother: "Desinstalar otra",
        uninstallerCatApp: "Aplicación",
        uninstallerCatSupport: "Soporte",
        uninstallerCatCaches: "Cachés",
        uninstallerCatPreferences: "Preferencias",
        uninstallerCatContainers: "Contenedores",
        uninstallerCatLogs: "Registros",
        uninstallerCatState: "Estado guardado",
        uninstallerCatOther: "Otros",

        shelfName: "Estante",
        shelfEnable: "Área temporal para arrastrar archivos",
        shelfEnableCaption: "Un espacio flotante para reunir archivos, imágenes y texto, y luego arrastrarlos a cualquier sitio.",
        shelfHowTitle: "Cómo se usa",
        shelfStep1: "Ábrelo con ⌃⌥⌘D o agitando el ratón durante un arrastre.",
        shelfStep2: "Suelta sobre él archivos, imágenes, enlaces o texto para guardarlos.",
        shelfStep3: "Arrastra cada ítem de vuelta a cualquier app cuando lo necesites.",
        shelfShakeToggle: "Abrir agitando el ratón al arrastrar",
        shelfShakeCaption: "Agita el puntero rápidamente mientras sostienes un ítem para que aparezca cerca del cursor.",
        shelfHotkeyLabel: "Atajo",
        shelfOpenNow: "Abrir ahora",
        shelfNoPermission: "No requiere ningún permiso.",
        shelfMenuItem: "Abrir el estante",
        shelfTitle: "Estante",
        shelfEmpty: "Arrastra ítems aquí",
        shelfClearAll: "Borrar todo",
        shelfRemoveSelected: "Quitar seleccionados",
        shelfSelectedFormat: "%d seleccionados",
        shelfHint: "Haz clic para seleccionar. Arrastra fuera para usar.",
        shelfItemImage: "Imagen",

        breakdownMeasuring: "Midiendo…",

        mixerSection: "Mezclador de volumen",
        mixerEmpty: "Las apps que usan audio aparecen aquí",
        mixerUnavailable: "Disponible en macOS 14.4 y posteriores",
        mixerPermissionBody: "Para ajustar el volumen por app, permite «Grabación de pantalla y audio del sistema» en Ajustes del Sistema. El audio nunca se graba.",
        mixerResetTooltip: "Restablecer al 100 %",

        updatesSection: "Actualizaciones",
        autoCheckToggle: "Buscar actualizaciones automáticamente",
        checkNowButton: "Buscar ahora",
        updateChecking: "Buscando…",
        updateUpToDate: "Tienes la última versión.",
        updateAvailablePrefix: "Actualización disponible:",
        updateInstallButton: "Descargar e instalar",
        updateDownloading: "Descargando la actualización…",
        updateInstalling: "Instalando y reiniciando…",
        updateFailedPrefix: "No se pudo comprobar:",
        updateLastChecked: "Última comprobación:",
        updateNotifyTitle: "Actualización de Vorssaint",
        menuCheckUpdates: "Buscar actualizaciones…",

        permissionRequired: "Permiso necesario",
        permissionAccessibility: "Accesibilidad",
        permissionScreenRecording: "Grabación de pantalla",
        permissionGranted: "Concedido",
        permissionMissing: "No concedido",
        permissionOpenSettings: "Abrir Ajustes del Sistema…",
        permissionRequest: "Solicitar permiso",
        permissionRestartNote: "macOS puede pedir que vuelvas a abrir la app tras concederlo.",

        aboutDescription: "Un centro de utilidades para tu Mac.\nEnergía, monitor del sistema, desplazamiento y un selector de ventanas, directamente en la barra de menús.",
        versionPrefix: "Versión",
        reviewIntro: "Ver la introducción",
        viewOnGitHub: "Ver en GitHub",

        obContinue: "Continuar",
        obBack: "Atrás",
        obSkipStep: "Omitir este paso",
        obStart: "Abrir Vorssaint",
        obStepWelcomeTitle: "Te damos la bienvenida a Vorssaint",
        obStepWelcomeBody: "Una utilidad discreta en la barra de menús que hace que el día a día con macOS sea más práctico.",
        obWelcomeBullet1Title: "Energía bajo control",
        obWelcomeBullet1Body: "Mantén el Mac activo todo el tiempo que quieras, incluso con la tapa cerrada.",
        obWelcomeBullet2Title: "Una visión clara del sistema",
        obWelcomeBullet2Body: "Temperaturas de CPU, GPU y batería, uso del hardware y presión de memoria en tiempo real.",
        obWelcomeBullet3Title: "El ratón y las ventanas a tu manera",
        obWelcomeBullet3Body: "Desplazamiento invertido del ratón y un selector de ventanas con miniaturas.",
        obLanguageLabel: "Idioma",
        obStepAccessibilityTitle: "Accesibilidad",
        obStepAccessibilityBody: "Necesaria para invertir el desplazamiento del ratón y para que el selector de ventanas responda al teclado.",
        obAccessibilityWhy: "La app solo observa la rueda del ratón y el atajo del selector. No se graba ni se envía nada a ningún sitio.",
        obStepRecordingTitle: "Grabación de pantalla",
        obStepRecordingBody: "Permite que el selector muestre miniaturas reales de las ventanas en lugar de solo iconos.",
        obRecordingWhy: "Las miniaturas se generan al momento, permanecen en la memoria y nunca salen de tu Mac. Sin ella, el selector funciona con iconos.",
        obStepMonitorTitle: "Monitor del sistema",
        obStepMonitorBody: "El panel muestra las temperaturas de CPU, GPU y batería, el uso del hardware y la presión de memoria.",
        obMonitorNoPermission: "No necesita permiso. Los sensores se leen directamente del sistema.",
        obStepOptionalTitle: "Funciones opcionales",
        obStepOptionalBody: "Activa ahora las que quieras usar. Todo se puede cambiar más tarde en Ajustes.",
        obPasswordlessToggle: "Tapa cerrada sin pedir contraseña",
        obPasswordlessCaption: "Crea una regla del sistema restringida a «pmset disablesleep». La contraseña de administrador se pide una sola vez, ahora.",
        obStepStatusTitle: "Comprobación",
        obStepStatusBody: "Asegúrate de que todo está listo para las funciones que quieres usar.",
        obStatusRecheck: "Comprobar de nuevo",
        obStepDoneTitle: "¡Todo listo!",
        obStepDoneBody: "Vorssaint ya está cuidando de tu Mac.",
        obDoneHint: "Busca el agujero negro en la barra de menús, en la esquina superior derecha de la pantalla.",
        obWhatsNewTitle: "Novedades de esta versión",
        obLanguageUpdateTitle: "Ahora en tu idioma",
        obLanguageUpdateBody: "Vorssaint ahora habla varios idiomas. Elige el que quieras usar; puedes cambiarlo cuando quieras en Ajustes.",

        tabMonitor: "Monitor",
        monitorMenuBarSection: "En la barra de menús",
        monitorMenuBarCaption: "Elige qué aparece junto al icono en la barra de menús.",
        monitorShowCPU: "CPU",
        monitorShowMemory: "Memoria",
        monitorShowNetwork: "Red",
        monitorShowPowerLabel: "Energía",
        monitorIntervalLabel: "Actualizar cada",
        monitorInterval1: "1 segundo",
        monitorInterval2: "2 segundos",
        monitorInterval5: "5 segundos",
        monitorPanelSection: "En el panel",

        networkSection: "Red",
        networkDownload: "Descarga",
        networkUpload: "Subida",
        networkThisSession: "En esta sesión",
        networkMeasuring: "Midiendo…",

        powerSection: "Energía",
        powerSystem: "Sistema",
        powerAdapter: "Adaptador",
        powerBattery: "Batería",
        powerCharging: "Cargando",
        powerOnBattery: "Con batería",
        powerPluggedIn: "Enchufado",
        powerUnavailable: "Métricas de energía no disponibles en este Mac",
        powerAdapterMaxFormat: "%@ máx.",
        monitorShowGPU: "GPU",
        monitorGraphsSection: "Gráficas",
        monitorGraphsCaption: "Elige qué métricas muestran una gráfica a lo largo del tiempo.",

        updateBannerTitle: "Actualización disponible",
        updateBannerAction: "Actualizar",
        obStepMenuBarTitle: "Métricas en la barra de menús",
        obStepMenuBarBody: "Elige qué mostrar junto al icono. La vista previa de arriba se actualiza en tiempo real.",
        obStepMenuBarNote: "Novedad: bloques de Red y Energía y gráficas en el panel. Ajústalo todo más tarde en Ajustes › Monitor.",
        monitorMemoryStyleLabel: "Mostrar la memoria como",
        memoryStyleDot: "Punto",
        memoryStylePercent: "%",
        memoryStyleBoth: "Ambos",

        systemUptime: "Activo desde hace",
        powerHealth: "Salud de la batería",
        powerCycles: "ciclos",
        speedTestRun: "Prueba de velocidad",
        speedTestAgain: "Probar de nuevo",
        speedTestLatency: "Latencia",
        speedTestTesting: "Probando…",
        speedTestFailed: "La prueba falló",

        monitorShowInPanel: "Mostrar en el panel",
        monitorItemUptime: "Tiempo activo",
        monitorItemNetSpeed: "Velocidad en directo",
        monitorItemNetTotals: "Totales de la sesión",
        monitorItemNetTest: "Prueba de velocidad",
        monitorPanelConfigHint: "Abre un bloque para elegir qué muestra.",
        monitorOrderSection: "Orden de las secciones",
        monitorOrderHint: "Arrastra para reordenar las secciones del panel. Usa el chevrón de cada sección en el panel para contraerla.",
        obStepPanelTitle: "Qué aparece en el panel",
        obStepPanelBody: "Abre cada bloque y elige exactamente qué se muestra al hacer clic en el icono.",

        cleaningMenuItem: "Modo de limpieza",
        cleaningOverlayTitle: "Teclado bloqueado para limpiar",
        cleaningOverlaySubtitle: "Pulsa la misma tecla 5 veces para desbloquear",
        cleaningOverlayUnlock: "Desbloquear",
        cleaningOverlayMouseHint: "El ratón y el trackpad siguen funcionando",
        cleaningNeedsAxTitle: "Se necesita Accesibilidad",
        cleaningNeedsAxBody: "Para bloquear el teclado de forma segura, Vorssaint necesita el permiso de Accesibilidad. Concédelo en Ajustes del Sistema e inténtalo de nuevo.",

        tabSupport: "Apoyar",
        donateHeading: "Apoya a Vorssaint",
        donateMessage: "Todos mis proyectos públicos son, y siempre serán, totalmente gratuitos: sin suscripción, sin anuncios. El apoyo de la comunidad es lo único que los mantiene vivos. Si Vorssaint te ayuda, un café marca una diferencia de verdad.",
        donateButton: "Buy me a coffee",
        donateThanks: "Gracias por estar aquí. 🖤",
        obStepDonateTitle: "¿Te gusta Vorssaint? 🖤",
        showMenuBarIcon: "Mostrar el icono en la barra de menús",
        showMenuBarIconCaption: "Si el icono de Vorssaint desaparece (macOS puede ocultar iconos de la barra de menús cuando se queda sin espacio, algo habitual en Macs con notch), vuelve a abrir Vorssaint desde Aplicaciones o Spotlight: eso recrea el icono y, si sigue oculto, abre esta ventana. El botón de arriba hace lo mismo cuando ya puedes llegar hasta aquí. Mantener menos iconos en la barra de menús, o menos métricas en Vorssaint, lo hace mucho menos probable."
    )
}
