// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// 简体中文 — translated and hand-checked, not machine output.
extension Strings {
    static let zhHans = Strings(
        statusIdleTooltip: "Vorssaint：正常睡眠",
        statusActiveUntil: "Vorssaint：唤醒至",
        statusActiveIndefinite: "Vorssaint：持续唤醒",
        menuEnableAwake: "开启保持唤醒",
        menuDisableAwake: "关闭保持唤醒",
        menuActivateFor: "启用时长…",
        menuSettings: "设置…",
        menuAbout: "关于 Vorssaint",
        menuQuit: "退出 Vorssaint",
        menuHide: "隐藏 Vorssaint",
        menuHideOthers: "隐藏其他",
        menuShowAll: "全部显示",
        menuEdit: "编辑",
        menuUndo: "撤销",
        menuRedo: "重做",
        menuCut: "剪切",
        menuCopy: "拷贝",
        menuPaste: "粘贴",
        menuSelectAll: "全选",
        menuWindow: "窗口",
        menuMinimize: "最小化",
        menuZoom: "缩放",
        menuClose: "关闭",

        minutes15: "15 分钟",
        minutes30: "30 分钟",
        hour1: "1 小时",
        hours2: "2 小时",
        hours4: "4 小时",
        hours8: "8 小时",
        indefinitely: "持续不限",
        indefinite: "不限时",

        panelAwake: "Mac 已唤醒",
        panelNormalSleep: "正常睡眠",
        panelSettings: "设置",
        panelQuit: "退出",
        panelHotkeyHint: "快捷键切换",

        keepAwakeTitle: "保持唤醒",
        keepAwakeEndsIn: "剩余时间",
        keepAwakeUntilDisabled: "保持启用直到你手动关闭",
        keepAwakeNormalRules: "Mac 遵循正常的能源规则",
        keepAwakeOptions: "选项",
        keepAwakeMouseJiggle: "轻微移动指针",
        keepAwakeMouseJiggleCaption: "会话期间按所选间隔轻微移动指针。",
        keepAwakeMouseJiggleInterval: "间隔",
        keepAwakeIconTintLabel: "启用时图标颜色",
        keepAwakeIconTintOrange: "橙色",
        keepAwakeIconTintGreen: "绿色",
        keepAwakeIconTintBlue: "蓝色",
        keepAwakeIconTintPurple: "紫色",
        keepAwakeIconTintPink: "粉色",
        keepAwakeIconTintNone: "无颜色",
        durationLabel: "时长",
        clamshellTitle: "合盖后继续运行",
        clamshellOnCaption: "已完全禁用睡眠，请注意电量",
        clamshellNeedsSession: "每当“保持唤醒”启用时生效",
        clamshellReady: "已就绪，切换时无需密码",
        clamshellNeedsPassword: "只会要求输入一次管理员密码",

        systemSection: "系统",
        temperatures: "温度",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "电池",
        usageSection: "硬件占用",
        memorySection: "内存",
        memoryPressure: "压力",
        pressureNormal: "正常",
        pressureWarning: "注意",
        pressureCritical: "严重",
        monitorUnavailable: "此 Mac 上无可用传感器",
        energyAppsTitle: "显著耗能",
        energyAppsIdle: "无显著耗能",

        notifySessionEndedTitle: "会话已结束",
        notifySessionEndedBody: "时间到。Mac 将恢复正常睡眠。",
        notifyBatteryTitle: "Vorssaint 已关闭",
        notifyBatteryBody: "电量过低。已恢复正常睡眠以保护电量。",
        adminPromptClamshellOn: "Vorssaint 需要你的密码才能在合盖后继续运行。",
        adminPromptClamshellOff: "Vorssaint 需要你的密码才能恢复 Mac 的正常睡眠。",
        adminPromptRecover: "Vorssaint 在 Mac 睡眠被禁用时退出了。请输入密码以恢复正常睡眠。",
        adminPromptSudoersInstall: "Vorssaint 将创建一条受限规则（仅限 pmset disablesleep），用于切换合盖模式时无需输入密码。这是唯一一次需要密码。",
        adminPromptSudoersRemove: "Vorssaint 将移除免密码的合盖规则。",

        settingsTitle: "Vorssaint 设置",
        tabGeneral: "通用",
        tabEnergy: "能源",
        tabMouse: "鼠标",
        tabSwitcher: "切换器",
        tabAdvanced: "高级",
        tabAbout: "关于",
        tabReleaseNotes: "新功能",
        releaseNotesOnUpdateToggle: "更新后显示新功能",
        whatsNewDontShowAgain: "不再显示",
        previewSizeLabel: "预览大小",
        previewSizeNormal: "正常",
        previewSizeLarge: "大",
        previewSizeXLarge: "特大",
        settingsGroupFeatures: "功能",
        advancedResetSection: "权限",
        advancedResetDescription: "移除你授予 Vorssaint 的所有权限（辅助功能、屏幕录制、完全磁盘访问权限等）、登录项以及合盖规则。适合重新开始或卸载前使用。App 仍保持安装状态。",
        advancedClearButton: "清除所有权限",
        advancedCleared: "权限已清除。",
        advancedClearConfirmTitle: "清除所有权限？",
        advancedClearConfirmBody: "依赖权限的功能将停止工作，直到你重新授予。你的设置会保留。",
        advancedUninstallSection: "卸载",
        advancedUninstallDescription: "执行以上全部操作，然后移除偏好设置并将 Vorssaint 移到废纸篓，不留任何痕迹。完成后 App 会退出。你可以随时重新安装。",
        advancedUninstallButton: "完全卸载 Vorssaint",
        advancedUninstallConfirmTitle: "卸载 Vorssaint？",
        advancedUninstallConfirmBody: "Vorssaint 将清除其权限、移除偏好设置并移到废纸篓，然后退出。此操作无法从 App 内撤销，但在你清倒废纸篓之前它仍会留在其中。",

        launchAtLogin: "登录时启动",
        languageLabel: "语言",
        menuBarSection: "菜单栏",
        showCountdown: "在图标旁显示剩余时间",
        globalHotkeySection: "全局快捷键",
        hotkeyToggle: "启用“保持唤醒”快捷键",
        hotkeyCaption: "在任何 App 中都有效，无需额外权限。",

        sessionSection: "会话",
        defaultDurationLabel: "默认时长",
        keepAwakeAutoStart: "打开 App 时启用",
        keepAwakeAutoStartCaption: "自动启动“保持唤醒”。",
        batteryProtectionSection: "电池保护",
        batteryDisableBelow: "电量低于以下值时关闭",
        batteryNever: "从不",
        batteryProtectionCaption: "避免被遗忘的会话耗尽 MacBook 的电量。",
        clamshellSection: "合盖",
        configuring: "配置中…",
        sudoersFailed: "无法启用合盖模式。请重试。",
        clamshellExplanation: "“合盖后继续运行”会在“保持唤醒”启用期间完全禁用睡眠，并在会话结束或 App 退出时自动恢复。建议在接通电源时使用。",

        scrollSection: "滚动",
        invertMouseScroll: "反转鼠标滚动",
        invertMouseScrollCaption: "反转鼠标滚轮的方向。",
        scrollTrackpadNote: "触控板不受影响：仍保持 macOS 的自然滚动。",
        scrollActiveNow: "正在反转鼠标滚动",

        switcherSection: "App 切换器",
        switcherEnable: "使用 Vorssaint 切换器",
        switcherEnableCaption: "通过真实缩略图切换窗口，包括同一 App 的多个窗口之间。",
        switcherUsageHint: "按住快捷键进行浏览；松开即可激活窗口。Shift 或 ← 返回；Q 退出所选 App；Esc 取消。",
        switcherNoWindows: "没有打开的窗口",
        switcherMergeTabs: "每个 App 仅显示一项",
        switcherMergeTabsCaption: "将一个 App 的所有窗口合并为切换器中的一项，而不是每个窗口一项。",
        switcherShowFinder: "无窗口时显示访达",
        switcherShowFinderCaption: "即使没有打开的访达窗口，也在切换器中显示访达。",
        dockPreviewName: "Dock Preview",
        dockPreviewEnable: "在 Dock 中预览窗口",
        dockPreviewEnableCaption: "将指针悬停在 Dock 中已打开的 App 上，即可查看并临时显示它的窗口。",
        dockPreviewActiveNow: "已在 Dock 中启用",
        dockPreviewMagnificationBlocked: "请关闭 Dock 放大后再使用。",
        dockPreviewDockUnavailable: "无法读取 Dock 项目。",
        dockPreviewAutohideBeta: "测试版。你可能会遇到一些错误。",
        dockPreviewCloseWindow: "关闭窗口",
        dockPreviewIntroPeek: "将指针悬停在缩略图上可临时查看。点按即可打开该窗口。",
        dockPreviewIntroSettingsHint: "你之后可以在设置 › Switcher 中更改。",
        dockPreviewIntroLater: "暂不启用",
        dockPreviewIntroEnable: "启用 Dock Preview",
        dockPreviewIntroMagnificationAction: "请关闭 Dock 放大后再启用。",

        cutPasteName: "剪切和粘贴",
        cutPasteEnable: "在访达中剪切和粘贴文件",
        cutPasteEnableCaption: "在访达中用 ⌘X 剪切、用 ⌘V 移动文件和文件夹。",
        cutPasteHowTitle: "使用方法",
        cutPasteStep1: "在访达中选择项目，按 ⌘X 将其剪切。",
        cutPasteStep2: "打开目标文件夹，按 ⌘V 将其移动到那里。",
        cutPasteTextNote: "在文本字段中（例如重命名时），⌘X 和 ⌘V 仍照常工作。",
        cutPasteActiveNow: "已可在访达中剪切",
        cutPasteAutomationNote: "首次使用时，macOS 会请求控制访达的权限。",
        cutReadyTitle: "已剪切",
        cutReadyHint: "在目标文件夹中粘贴以移动",
        cutCancel: "取消剪切",
        cutDoneTitle: "已移动！",
        cutMovedSingular: "已移动 1 个项目",
        cutMovedPluralFormat: "已移动 %d 个项目",
        cutSomeFailed: "部分项目无法移动",

        autoQuitName: "关闭时退出",
        autoQuitEnable: "App 最后一个窗口关闭时退出该 App",
        autoQuitEnableCaption: "关闭 App 的最后一个窗口也会退出该 App。",
        autoQuitActiveNow: "已启用并正在监视窗口",
        autoQuitHowTitle: "工作原理",
        autoQuitStep1: "关闭某个 App 的最后一个窗口（⌘W 或红色按钮）。",
        autoQuitStep2: "该 App 会自行退出。“是否存储更改？”对话框仍会出现。",
        autoQuitPredictableNote: "通常无窗口运行的 App 永远不会被退出。",
        autoQuitExceptionsTitle: "例外",
        autoQuitExceptionsCaption: "此列表中的 App 即使没有窗口也会保持打开。",
        autoQuitExceptionsEmpty: "没有例外",
        autoQuitAddApp: "添加 App…",

        uninstallerName: "卸载器",
        uninstallerEnableCaption: "在移除 App 的同时，清除它遗留的缓存、偏好设置、日志和残留文件。",
        uninstallerStep1: "将一个 App 拖到设置中，或从列表中选择一个。",
        uninstallerStep2: "查看找到的文件以及它们占用的空间。",
        uninstallerStep3: "把想移除的内容移到废纸篓。不会永久删除任何内容。",
        uninstallerMenuItem: "卸载某个 App…",
        uninstallerDropTitle: "将 App 拖到这里",
        uninstallerDropSubtitle: "或选择一个进行扫描",
        uninstallerChoose: "选择 App…",
        uninstallerPickerTitle: "选择 App",
        uninstallerPickerSearch: "搜索 App",
        uninstallerPickerEmpty: "未找到 App",
        uninstallerEmptyNote: "未经你确认，不会移除任何内容。",
        uninstallerFDANote: "授予完全磁盘访问权限可进行更彻底的扫描。",
        uninstallerFDAGrant: "授予访问权限…",
        uninstallerFDAHint: "在列表中开启 Vorssaint。如果列表中没有，点按 + 并从“应用程序”中选择 Vorssaint。访问权限须在你重新打开 App 后才会生效。",
        uninstallerFDARelaunch: "立即重新打开",
        uninstallerScanning: "正在扫描文件…",
        uninstallerRemoving: "正在移到废纸篓…",
        uninstallerFoundTitle: "已找到",
        uninstallerSelectedFormat: "已选择 %d 项，共 %d 项",
        uninstallerRemove: "移到废纸篓",
        uninstallerCancel: "取消",
        uninstallerDoneTitle: "完成！",
        uninstallerFreedFormat: "已释放 %@",
        uninstallerSomeFailed: "部分项目无法移到废纸篓。",
        uninstallerAnother: "卸载另一个",
        uninstallerCatApp: "应用程序",
        uninstallerCatSupport: "支持文件",
        uninstallerCatCaches: "缓存",
        uninstallerCatPreferences: "偏好设置",
        uninstallerCatContainers: "容器",
        uninstallerCatLogs: "日志",
        uninstallerCatState: "已存储状态",
        uninstallerCatOther: "其他",

        urlCleanerName: "清理 URL",
        urlCleanerEnable: "清理复制的 URL",
        urlCleanerEnableCaption: "移除复制链接中的跟踪参数。",
        urlCleanerActiveNow: "已启用，正在观察剪贴板",
        urlCleanerManualTitle: "立即清理",
        urlCleanerInputPlaceholder: "粘贴 URL",
        urlCleanerOutputPlaceholder: "清理后的 URL 会显示在这里",
        urlCleanerCleanButton: "清理",
        urlCleanerPasteButton: "粘贴",
        urlCleanerCopyButton: "复制",
        urlCleanerClearButton: "清空输入框",
        urlCleanerNoURL: "请粘贴有效的 URL。",
        urlCleanerNoChange: "没有可清理的内容。",
        urlCleanerCleaned: "URL 已清理。",
        urlCleanerCopied: "已复制。",
        urlCleanerLocalNote: "本地处理。无网络。",

        homebrewName: "Homebrew",
        homebrewEnableCaption: "搜索、安装和移除 formula 与 cask。",
        homebrewMissingTitle: "未找到 Homebrew",
        homebrewMissingBody: "Vorssaint 可以在终端中打开官方 Homebrew 安装器。终端会显示步骤，并在需要时请求你的密码。",
        homebrewInstallHomebrew: "安装 Homebrew",
        homebrewInstallHomebrewCaption: "终端完成后，请回到这里并点击刷新。",
        homebrewInstallHomebrewOpened: "安装器已在终端中打开。",
        homebrewShellSetupTitle: "完成终端配置",
        homebrewShellSetupBody: "Homebrew 已安装，但终端可能还找不到 brew 命令。Vorssaint 可以在终端中打开配置命令。",
        homebrewShellSetupButton: "配置终端",
        homebrewShellSetupOpened: "命令已在终端中打开。完成后请回到这里并点击刷新。",
        homebrewRefresh: "刷新",
        homebrewSearchPlaceholder: "搜索包",
        homebrewKeyboardHint: "空格或回车会关闭 macOS 面板。请使用搜索按钮。",
        homebrewSearchButton: "搜索",
        homebrewSearchResults: "结果",
        homebrewInstalled: "已安装",
        homebrewAll: "全部",
        homebrewFormulas: "Formula",
        homebrewCasks: "Cask",
        homebrewNoPackages: "未找到包",
        homebrewNoSelection: "选择一个已安装的包，或搜索一个新的包。",
        homebrewDetailsTitle: "包详情",
        homebrewInstall: "安装",
        homebrewUninstall: "卸载",
        homebrewOpenTerminal: "打开终端",
        homebrewCancelOperation: "取消",
        homebrewClearLog: "清空日志",
        homebrewLogTitle: "日志",
        homebrewVersion: "版本",
        homebrewDescription: "类型",
        homebrewHomepage: "打开网站",
        homebrewPopularity: "热度",
        homebrewPopularityFormat: "%@ 次安装，%@ 天",
        homebrewInstalledBadge: "已安装",
        homebrewNotInstalledBadge: "未安装",
        homebrewConfirmInstallTitle: "用 Homebrew 安装？",
        homebrewConfirmInstallBodyFormat: "Homebrew 将下载并安装 %@。也可能安装依赖项。",
        homebrewConfirmUninstallTitle: "用 Homebrew 卸载？",
        homebrewConfirmUninstallBodyFormat: "Homebrew 将卸载 %@。配置文件可能仍保留在系统中。",
        homebrewTerminalFallback: "此操作需要通过终端询问管理员密码。Vorssaint 不会获取密码。",
        homebrewLoading: "正在加载…",
        homebrewSearchEmpty: "无结果",
        homebrewOperationInstallFormat: "正在安装 %@",
        homebrewOperationUninstallFormat: "正在卸载 %@",
        homebrewOperationInstalledFormat: "%@ 已安装。",
        homebrewOperationUninstalledFormat: "%@ 已卸载。",
        homebrewOperationFailedFormat: "无法完成 %@。",
        homebrewOperationCancelled: "操作已取消。",
        homebrewOperationPreparing: "正在准备...",
        homebrewOperationDownloading: "正在下载文件...",
        homebrewOperationInstalling: "正在安装文件...",
        homebrewOperationUninstalling: "正在移除文件...",
        homebrewOperationFinalizing: "正在完成...",
        homebrewOperationRefreshing: "正在刷新列表...",
        homebrewOperationTerminal: "请在终端中继续。",
        homebrewOperationElapsedFormat: "已用 %@",
        homebrewOperationShowDetails: "显示详情",
        homebrewOperationHideDetails: "隐藏详情",
        homebrewOperationTechnicalLog: "技术详情",
        homebrewOperationProgressUnknown: "Homebrew 尚未报告百分比。",

        mediaName: "媒体",
        mediaEnableCaption: "本地压缩视频和图像、制作 GIF，并从图像中提取文字。",
        mediaLocalNote: "本地。无网络。",
        mediaToolVideo: "视频",
        mediaToolGIF: "GIF",
        mediaToolImage: "图像",
        mediaToolText: "文字",
        mediaSelectFile: "选择文件",
        mediaDropHint: "将文件拖到这里，或点击选择。",
        mediaOutput: "输出",
        mediaOutputAutomatic: "自动",
        mediaChooseOutput: "目标位置",
        mediaStartVideo: "压缩视频",
        mediaStartGIF: "制作 GIF",
        mediaStartImage: "压缩图像",
        mediaStartText: "提取文字",
        mediaCancel: "取消",
        mediaStartTime: "开始",
        mediaEndTime: "结束",
        mediaQuality: "压缩",
        mediaCompressionLow: "低",
        mediaCompressionMedium: "中",
        mediaCompressionHigh: "高",
        mediaMaxSize: "大小",
        mediaWidth: "宽度",
        mediaFPS: "FPS",
        mediaKeepAudio: "保留音频",
        mediaCodec: "编码",
        mediaFormat: "格式",
        mediaStripMetadata: "移除元数据",
        mediaLoopGIF: "循环 GIF",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "准确",
        mediaOCRFast: "快速",
        mediaLanguageCorrection: "语言校正",
        mediaTextOutputNote: "提取的文字可以复制并保存为 TXT。",
        mediaRunning: "处理中",
        mediaCompleted: "完成",
        mediaCancelled: "已取消。",
        mediaOpenInFinder: "显示",
        mediaCopyText: "复制文字",
        mediaRunAgain: "再次运行",
        mediaEmptyText: "未找到文字。",
        mediaResultSavedFormat: "已保存为 %@",
        mediaResultSizeFormat: "%@ 到 %@",
        mediaErrorNoFile: "请先选择文件。",
        mediaErrorNoVideo: "此文件没有视频轨道。",
        mediaErrorSameOutput: "请选择不同于原文件的目标位置。",
        mediaErrorUnsupported: "macOS 不支持此格式。",

        shelfName: "暂存架",
        shelfEnable: "用于拖放文件的临时区域",
        shelfEnableCaption: "一个浮动空间，用来收集文件、图像和文本，稍后再拖到任何 App 中。",
        shelfHowTitle: "使用方法",
        shelfStep1: "用快捷键打开它，或在拖动时晃动鼠标打开。",
        shelfStep2: "把文件、图像、链接或文本拖放到上面以暂存。",
        shelfStep3: "需要时再把每个项目拖回任何 App。",
        shelfShakeToggle: "拖动时晃动鼠标打开",
        shelfShakeCaption: "按住某个项目时快速晃动指针，即可在光标附近呼出暂存架。",
        shelfHotkeyLabel: "快捷键",
        shelfOpenNow: "立即打开",
        shelfNoPermission: "无需任何权限。",
        shelfMenuItem: "打开暂存架",
        shelfTitle: "暂存架",
        shelfEmpty: "将项目拖到这里",
        shelfClearAll: "全部清除",
        shelfRemoveSelected: "移除所选",
        shelfSelectedFormat: "已选择 %d 项",
        shelfHint: "点按以选择，拖出即可使用。",
        shelfItemImage: "图像",

        breakdownMeasuring: "测量中…",

        mixerSection: "音量混音器",
        mixerEmpty: "使用音频的 App 会显示在这里",
        mixerUnavailable: "需 macOS 14.4 及更高版本",
        mixerPermissionBody: "若要调整各 App 的音量，请在“系统设置”中允许“屏幕与系统音频录制”。绝不会录制音频。",
        mixerResetTooltip: "重置为 100%",
        mixerOutputDefault: "默认",
        mixerOutputCurrent: "当前",
        mixerOutputUnavailable: "输出不可用",
        mixerOutputFallback: "在此设备恢复前使用默认输出。",
        mixerOutputTooltip: "选择输出",
        mixerSystemOutputTitle: "输出",
        mixerSystemOutputNoDevices: "未找到输出设备",
        mixerSystemOutputTooltip: "选择系统输出",
        mixerSystemOutputErrorFormat: "无法切换：%@",
        mixerLowerOnHeadphonesDisconnect: "耳机断开时降低音量",
        mixerLowerOnHeadphonesDisconnectCaption: "有线或蓝牙耳机断开时，将输出降到 0%。",
        soundOutputSwitcherTitle: "输出切换器",
        soundOutputSwitcherEnable: "用快捷键切换输出",
        soundOutputSwitcherCaption: "选择输出设备，然后用快捷键切到下一个可用输出。",
        soundOutputSwitcherDevices: "循环中的输出",
        soundOutputSwitcherNoAvailableSelection: "请至少选择一个可用输出。",
        mixerInputTitle: "麦克风",
        mixerInputNoDevices: "未找到麦克风",
        mixerInputUnavailable: "麦克风不可用",
        mixerInputFallback: "在此麦克风恢复前使用默认输入。",
        mixerInputTooltip: "选择麦克风",
        mixerInputErrorFormat: "无法切换：%@",

        updatesSection: "更新",
        autoCheckToggle: "自动检查更新",
        checkNowButton: "立即检查",
        updateChecking: "检查中…",
        updateUpToDate: "你已是最新版本。",
        updateAvailablePrefix: "有可用更新：",
        updateInstallButton: "下载并安装",
        updateDownloading: "正在下载更新…",
        updateInstalling: "正在安装并重新启动…",
        updateFailedPrefix: "无法检查：",
        updateLastChecked: "上次检查：",
        updateNotifyTitle: "Vorssaint 更新",
        menuCheckUpdates: "检查更新…",

        permissionRequired: "需要权限",
        permissionAccessibility: "辅助功能",
        permissionScreenRecording: "屏幕录制",
        permissionGranted: "已授予",
        permissionMissing: "未授予",
        permissionOpenSettings: "打开系统设置…",
        permissionRequest: "授予访问权限",
        permissionRestartNote: "授予后，macOS 可能会要求重新打开 App。",

        aboutDescription: "你的 Mac 实用工具中心。\n能源、系统监视、滚动和窗口切换器，尽在菜单栏中。",
        versionPrefix: "版本",
        reviewIntro: "重看介绍",
        viewOnGitHub: "在 GitHub 上查看",

        obContinue: "继续",
        obBack: "返回",
        obSkipStep: "跳过此步骤",
        obStart: "打开 Vorssaint",
        obStepWelcomeTitle: "欢迎使用 Vorssaint",
        obStepWelcomeBody: "一款低调的菜单栏实用工具，让日常使用 macOS 更顺手。",
        obWelcomeBullet1Title: "掌控能源",
        obWelcomeBullet1Body: "让 Mac 想唤醒多久就唤醒多久，合盖也不例外。",
        obWelcomeBullet2Title: "清晰掌握系统状态",
        obWelcomeBullet2Body: "实时查看 CPU、GPU 和电池温度、硬件占用以及内存压力。",
        obWelcomeBullet3Title: "鼠标和窗口，随你所愿",
        obWelcomeBullet3Body: "反转鼠标滚动，以及带缩略图的窗口切换器。",
        obLanguageLabel: "语言",
        obStepAccessibilityTitle: "辅助功能",
        obStepAccessibilityBody: "用于反转鼠标滚动，并让窗口切换器响应键盘操作。",
        obAccessibilityWhy: "App 只会监视鼠标滚轮和切换器快捷键。不会录制任何内容，也不会发送到任何地方。",
        obStepRecordingTitle: "屏幕录制",
        obStepRecordingBody: "让切换器显示真实的窗口缩略图，而不仅是图标。",
        obRecordingWhy: "缩略图实时生成，仅保留在内存中，绝不会离开你的 Mac。即使没有它，切换器仍可用图标工作。",
        obStepMonitorTitle: "系统监视",
        obStepMonitorBody: "面板会显示 CPU、GPU 和电池温度、硬件占用以及内存压力。",
        obMonitorNoPermission: "无需任何权限。传感器直接从系统读取。",
        obStepOptionalTitle: "可选功能",
        obStepOptionalBody: "现在开启你想用的功能。一切都可以稍后在设置中更改。",
        obStepStatusTitle: "检查",
        obStepStatusBody: "确认你想使用的功能都已就绪。",
        obStatusRecheck: "重新检查",
        obStepDoneTitle: "全部就绪！",
        obStepDoneBody: "Vorssaint 已开始照看你的 Mac。",
        obDoneHint: "在菜单栏（屏幕右上角）寻找那个黑洞图标。",
        obWhatsNewTitle: "此版本的新功能",
        obWhatsNewFallback: "此更新包含最新的修复和改进。",
        obLanguageUpdateTitle: "现在支持你的语言",
        obLanguageUpdateBody: "Vorssaint 现在支持多种语言。选择你想使用的语言，随时可在设置中更改。",

        tabMonitor: "监视",
        monitorMenuBarSection: "在菜单栏中",
        monitorMenuBarCaption: "选择菜单栏中图标旁显示的内容。",
        monitorCombineTemperatures: "合并使用率和温度",
        monitorCombineTemperaturesCaption: "同一项目的使用率和温度都启用时，在一个区块中显示。",
        monitorSeparateMenuBarMetrics: "将指标分成独立项目",
        monitorSeparateMenuBarMetricsCaption: "将已启用的区块拆成单独的菜单栏项目，合并开启时使用率和温度仍保持在一起。",
        monitorShowCPU: "CPU",
        monitorShowMemory: "内存",
        monitorShowNetwork: "网络",
        monitorShowPowerLabel: "电源",
        monitorIntervalLabel: "更新间隔",
        monitorInterval1: "1 秒",
        monitorInterval2: "2 秒",
        monitorInterval5: "5 秒",
        monitorPanelSection: "在面板中",
        panelNavigationMode: "按分区导航面板",
        panelNavigationCaption: "一次显示一个分区，并将导航放在面板底部。",
        panelFooterSections: "分区",
        panelFooterList: "列表",
        fanControlBetaShow: "在面板中显示 Fan Control (Beta)",
        fanControlBetaSection: "Fan Control",
        fanControlBetaTitle: "Fan Control",
        fanControlBetaStatus: "自动",
        fanControlBetaCaption: "Beta。手动控制会保持停用，直到每个 Mac 型号完成验证。",
        fanControlModeAutomatic: "自动",
        fanControlModeManual: "手动",
        betaBadge: "BETA",
        betaFeatureWarning: "测试版。你可能会遇到一些错误。",

        networkSection: "网络",
        networkDownload: "下载",
        networkUpload: "上传",
        networkThisSession: "本次会话",
        networkMeasuring: "测量中…",

        diskSection: "磁盘",
        diskUsed: "已用",
        diskFree: "可用",
        diskInternal: "内置",
        diskExternal: "外置",
        diskSelect: "选择磁盘",
        diskRead: "读取",
        diskWrite: "写入",
        diskSMARTStatus: "状态",
        diskSMARTUnavailable: "此磁盘没有可用的 SMART",
        diskTotalRead: "总读取",
        diskTotalWritten: "总写入",
        diskTemperature: "温度",
        diskHealth: "健康度",
        diskPowerCycles: "通电次数",
        diskPowerOnHours: "通电小时",
        diskUnsafeShutdowns: "异常关机",
        diskMediaErrors: "介质错误",
        diskEject: "推出",
        diskEjectAll: "全部推出",
        diskEjecting: "正在推出…",
        diskReadyToRemove: "可以移除",
        diskEjectFailed: "无法推出",
        diskProtectionCaption: "拔出前先推出。",
        diskNoExternal: "没有可推出的外置磁盘。",
        diskOpenInFinder: "打开",
        diskStorageSettings: "存储",
        diskNoDisks: "未找到已挂载磁盘。",

        powerSection: "电源",
        powerSystem: "系统",
        powerAdapter: "电源适配器",
        powerBattery: "电池",
        powerCharging: "充电中",
        powerOnBattery: "使用电池",
        powerPluggedIn: "已接通电源",
        powerUnavailable: "此 Mac 上无可用电源指标",
        powerAdapterMaxFormat: "最高 %@",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "CPU 温度",
        monitorShowGPUTemperature: "GPU 温度",
        monitorShowBatteryTemperature: "电池温度",
        monitorGraphsSection: "图表",
        monitorGraphsCaption: "选择哪些指标显示随时间变化的图表。",

        updateBannerTitle: "有可用更新",
        updateBannerAction: "更新",
        obStepMenuBarTitle: "菜单栏中的指标",
        obStepMenuBarBody: "选择图标旁要显示的内容。上方预览会实时更新。",
        obStepMenuBarNote: "新增：面板中的网络和电源模块及图表。稍后可在设置 › 监视中细致调整。",
        monitorMenuBarPresetLabel: "样式",
        menuBarPresetReadable: "易读",
        menuBarPresetDense: "密集",
        monitorLabelStyleLabel: "标签",
        menuBarLabelStyleCompact: "紧凑",
        menuBarLabelStyleClassic: "经典",
        monitorMemoryStyleLabel: "内存显示方式",
        monitorMemoryPressureDot: "压力圆点",
        memoryStyleDot: "圆点",
        memoryStylePercent: "%",
        memoryStyleBoth: "两者",

        systemUptime: "已运行",
        powerHealth: "电池健康度",
        powerCycles: "次循环",
        speedTestRun: "测速",
        speedTestAgain: "再次测速",
        speedTestLatency: "延迟",
        speedTestTesting: "测试中…",
        speedTestFailed: "测试失败",

        monitorShowInPanel: "在面板中显示",
        panelHideItem: "从面板隐藏",
        panelShowItem: "在面板中显示",
        panelHiddenItem: "隐藏",
        monitorItemUptime: "运行时间",
        monitorItemNetSpeed: "实时速度",
        monitorItemNetTotals: "会话总量",
        monitorItemNetTest: "测速",
        monitorItemDiskUsage: "磁盘使用",
        monitorItemDiskActivity: "实时活动",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "外置保护",
        monitorItemDiskTools: "工具",
        monitorPanelConfigHint: "打开某个模块以选择它显示的内容。",
        monitorOrderSection: "分区顺序",
        monitorOrderHint: "拖动以重新排列面板分区，点按眼睛图标可显示或隐藏各分区。",
        obStepPanelTitle: "面板中显示的内容",
        obStepPanelBody: "打开每个模块，精确选择点按图标时显示的内容。",
        obStepPanelNavigationTitle: "分区式面板",
        obStepPanelNavigationBody: "面板现在可以一次显示一个分区，并在底部导航。本次更新会默认开启，方便你试用。",

        cleaningMenuItem: "清洁模式",
        utilitiesSection: "实用工具",
        quickControlsSection: "控制",
        windowMaximizeName: "最大化窗口",
        windowMaximizeCaption: "绿色按钮会最大化，不创建新的空间。",
        windowMaximizeActiveNow: "绿色按钮已启用",
        windowMaximizeNeedsAccessibility: "需要辅助功能权限才能工作。",
        cleaningPanelCaption: "锁定键盘，便于安全清洁。",
        cleaningOverlayTitle: "键盘已锁定以便清洁",
        cleaningOverlaySubtitle: "连按同一个键 5 次以解锁",
        cleaningOverlayUnlock: "解锁",
        cleaningOverlayMouseHint: "你的鼠标和触控板仍可使用",
        cleaningNeedsAxTitle: "需要辅助功能",
        cleaningNeedsAxBody: "为安全地锁定键盘，Vorssaint 需要辅助功能权限。请在“系统设置”中授予后重试。",

        tabSupport: "支持",
        donateHeading: "支持 Vorssaint",
        donateMessage: "我的每一个公开项目现在是、将来也永远会完全免费：没有订阅，没有广告。社区的支持是它得以延续的唯一动力。如果 Vorssaint 帮到了你，一杯咖啡真的会带来不同。",
        donateButton: "Buy me a coffee",
        donateThanks: "谢谢你的到来。🖤",
        supportIntroTitle: "Vorssaint 100% 免费，并且永远免费",
        supportIntroMessage: "我会继续用空闲时间维护这个 App。如果它帮到了你，你也可以用很简单的方式帮我，分享它，在 GitHub 上点一颗星，或者请我喝杯咖啡。这对我继续改进它真的很有帮助。",
        supportIntroStarButton: "点一颗星",
        supportIntroCoffeeButton: "Buy me a coffee",
        supportIntroLaterButton: "稍后再说",
        showMenuBarIcon: "显示菜单栏图标",
        showMenuBarIconCaption: "如果 Vorssaint 的图标消失了（当菜单栏空间不足时，macOS 可能会隐藏图标，这在带刘海的 Mac 上很常见），请从“应用程序”或 Spotlight 重新打开 Vorssaint：这会重建图标，如果它仍被隐藏，则会打开此窗口。当你已经能进入这里时，上方按钮的作用相同。让菜单栏中的图标更少，或 Vorssaint 的指标更少，会大大降低这种情况发生的几率。",
        shortcutRecording: "按下新的快捷键",
        shortcutReset: "重置",
        shortcutInvalid: "请至少搭配 Control、Option 或 Command 和一个按键。",
        shortcutConflictFormat: "此快捷键已被 %@ 使用。",
        shortcutUnavailable: "macOS 拒绝了此快捷键。请选择另一个。",
        shelfShortcutToggle: "Shelf 快捷键",
        switcherUsageHintFormat: "按住 %@ 进行浏览；松开即可激活窗口。Shift 或 ← 返回；Q 退出所选 App；Esc 取消。"
    )
}
