// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// 日本語 — translated and hand-checked, not machine output.
extension Strings {
    static let ja = Strings(
        statusIdleTooltip: "Vorssaint：通常のスリープ",
        statusActiveUntil: "Vorssaint：次の時刻までスリープしない",
        statusActiveIndefinite: "Vorssaint：解除するまでスリープしない",
        menuEnableAwake: "スリープ防止をオン",
        menuDisableAwake: "スリープ防止をオフ",
        menuActivateFor: "時間を指定してオン…",
        menuSettings: "設定…",
        menuAbout: "Vorssaint について",
        menuQuit: "Vorssaint を終了",
        menuHide: "Vorssaint を隠す",
        menuHideOthers: "ほかを隠す",
        menuShowAll: "すべてを表示",
        menuEdit: "編集",
        menuUndo: "取り消す",
        menuRedo: "やり直す",
        menuCut: "カット",
        menuCopy: "コピー",
        menuPaste: "ペースト",
        menuSelectAll: "すべてを選択",
        menuWindow: "ウインドウ",
        menuMinimize: "しまう",
        menuZoom: "拡大／縮小",
        menuClose: "閉じる",

        minutes15: "15分",
        minutes30: "30分",
        hour1: "1時間",
        hours2: "2時間",
        hours4: "4時間",
        hours8: "8時間",
        indefinitely: "無期限",
        indefinite: "無期限",

        panelAwake: "Mac はスリープしません",
        panelNormalSleep: "通常のスリープ",
        panelActiveBadge: "オン",
        panelSettings: "設定",
        panelQuit: "終了",
        panelHotkeyHint: "⌃⌥⌘K で切り替え",

        keepAwakeTitle: "スリープ防止",
        keepAwakeEndsIn: "残り",
        keepAwakeUntilDisabled: "オフにするまで継続",
        keepAwakeNormalRules: "Mac は通常の省エネルギー設定に従います",
        durationLabel: "継続時間",
        clamshellTitle: "ふたを閉じても続ける",
        clamshellOnCaption: "スリープを完全に無効化中。電源にご注意ください",
        clamshellNeedsSession: "「スリープ防止」がオンのあいだ常に適用されます",
        clamshellReady: "準備完了。パスワードなしで切り替えられます",
        clamshellNeedsPassword: "オンにするとき管理者パスワードの入力を求められます",

        systemSection: "システム",
        temperatures: "温度",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "バッテリー",
        usageSection: "ハードウェア使用状況",
        memorySection: "メモリ",
        memoryPressure: "プレッシャー",
        pressureNormal: "標準",
        pressureWarning: "注意",
        pressureCritical: "危険",
        monitorUnavailable: "この Mac ではセンサーを利用できません",

        notifySessionEndedTitle: "セッションが終了しました",
        notifySessionEndedBody: "時間になりました。Mac は再び通常どおりスリープします。",
        notifyBatteryTitle: "Vorssaint をオフにしました",
        notifyBatteryBody: "バッテリー残量が少なくなりました。充電を保護するため通常のスリープに戻しました。",

        adminPromptClamshellOn: "ふたを閉じたまま Mac のスリープを防止するにはパスワードが必要です。このダイアログはアプリのはじめにの案内（設定 › 情報）で省略できます。",
        adminPromptClamshellOff: "Mac の通常のスリープを元に戻すにはパスワードが必要です。",
        adminPromptRecover: "Mac のスリープを無効化したまま Vorssaint が終了しました。通常のスリープに戻すにはパスワードを入力してください。",
        adminPromptSudoersInstall: "ふたを閉じたモードをパスワードなしで切り替えられるよう、Vorssaint が制限付きルール（pmset disablesleep のみ）を作成します。パスワードが必要なのはこの一度きりです。",
        adminPromptSudoersRemove: "パスワード不要のふたを閉じたモードのルールを Vorssaint が削除します。",

        settingsTitle: "Vorssaint 設定",
        tabGeneral: "一般",
        tabEnergy: "省エネルギー",
        tabMouse: "マウス",
        tabSwitcher: "スイッチャー",
        tabAdvanced: "詳細",
        tabAbout: "情報",
        settingsGroupFeatures: "機能",
        advancedResetSection: "アクセス権",
        advancedResetDescription: "Vorssaint に許可したすべてのアクセス権（アクセシビリティ、画面収録、フルディスクアクセスなど）、ログイン項目、ふたを閉じたモードのルールを削除します。最初からやり直すときや、アンインストールの前に便利です。アプリはインストールされたまま残ります。",
        advancedClearButton: "すべてのアクセス権を消去",
        advancedCleared: "アクセス権を消去しました。",
        advancedClearConfirmTitle: "すべてのアクセス権を消去しますか？",
        advancedClearConfirmBody: "アクセス権が必要な機能は、再度許可するまで動作しなくなります。設定はそのまま保持されます。",
        advancedUninstallSection: "アンインストール",
        advancedUninstallDescription: "上記をすべて実行したうえで、環境設定を削除し、Vorssaint をゴミ箱に移動して、何も残しません。完了後にアプリは終了します。いつでも再インストールできます。",
        advancedUninstallButton: "Vorssaint を完全にアンインストール",
        advancedUninstallConfirmTitle: "Vorssaint をアンインストールしますか？",
        advancedUninstallConfirmBody: "Vorssaint はアクセス権を消去し、環境設定を削除し、ゴミ箱に移動してから終了します。この操作はアプリからは取り消せませんが、ゴミ箱を空にするまではゴミ箱に残ります。",

        launchAtLogin: "ログイン時に起動",
        languageLabel: "言語",
        menuBarSection: "メニューバー",
        showCountdown: "アイコンの横に残り時間を表示",
        globalHotkeySection: "グローバルショートカット",
        hotkeyToggle: "⌃⌥⌘K で「スリープ防止」を切り替え",
        hotkeyCaption: "追加のアクセス権なしで、どのアプリでも使えます。",

        sessionSection: "セッション",
        defaultDurationLabel: "デフォルトの継続時間",
        batteryProtectionSection: "バッテリー保護",
        batteryDisableBelow: "バッテリーが次の値を下回ったらオフにする",
        batteryNever: "しない",
        batteryProtectionCaption: "オンのままになったセッションが MacBook のバッテリーを消耗させるのを防ぎます。",
        clamshellSection: "ふたを閉じたモード",
        configuring: "設定中…",
        sudoersFailed: "完了できませんでした。パスワードを確認してもう一度お試しください。",
        clamshellExplanation: "「ふたを閉じても続ける」は、「スリープ防止」がオンのあいだスリープを完全に無効化し、セッションの終了時またはアプリの終了時に自動的に元に戻ります。電源に接続した状態での使用をおすすめします。",

        scrollSection: "スクロール",
        invertMouseScroll: "マウスのスクロールを反転",
        invertMouseScrollCaption: "マウスホイールのスクロール方向を逆にします。",
        scrollTrackpadNote: "トラックパッドはそのままで、macOS のナチュラルなスクロールを維持します。",
        scrollActiveNow: "現在マウスのスクロールを反転中",

        switcherSection: "アプリスイッチャー",
        switcherEnable: "⌘Tab を Vorssaint のスイッチャーに置き換える",
        switcherEnableCaption: "実際のサムネールを見ながらウインドウを切り替えられます。同じアプリの複数ウインドウ間でも切り替えできます。",
        switcherUsageHint: "⌘ を押したまま Tab を押して移動し、放すとウインドウがアクティブになります。Shift または ← で戻る、Q で選択中のアプリを終了、Esc でキャンセルします。",
        switcherNoWindows: "開いているウインドウはありません",
        switcherMergeTabs: "アプリごとに1つにまとめて表示",
        switcherMergeTabsCaption: "スイッチャーで、アプリのすべてのウインドウをウインドウごとではなく1つの項目にまとめます。",

        cutPasteName: "カット＆ペースト",
        cutPasteEnable: "Finder でファイルをカット＆ペースト",
        cutPasteEnableCaption: "⌘X でカット、⌘V で Finder のファイルやフォルダを移動できます。",
        cutPasteHowTitle: "使いかた",
        cutPasteStep1: "Finder で項目を選択し、⌘X を押してカットします。",
        cutPasteStep2: "移動先のフォルダを開き、⌘V を押してそこへ移動します。",
        cutPasteTextNote: "テキストフィールド内では（名前の変更時など）、⌘X と ⌘V はこれまでどおり動作します。",
        cutPasteActiveNow: "Finder でカットできます",
        cutPasteAutomationNote: "初回は、macOS が Finder を制御する許可を求めます。",
        cutReadyTitle: "カットしました",
        cutReadyHint: "移動先のフォルダで",
        cutDoneTitle: "移動しました！",
        cutMovedSingular: "1項目を移動しました",
        cutMovedPluralFormat: "%d項目を移動しました",
        cutSomeFailed: "一部の項目を移動できませんでした",

        autoQuitName: "閉じたら終了",
        autoQuitEnable: "最後のウインドウを閉じたらアプリを終了",
        autoQuitEnableCaption: "アプリの最後のウインドウを閉じると、そのアプリも終了します。",
        autoQuitActiveNow: "オンにして、ウインドウを監視中",
        autoQuitHowTitle: "しくみ",
        autoQuitStep1: "アプリの最後のウインドウを閉じます（⌘W または赤いボタン）。",
        autoQuitStep2: "アプリは自動的に終了します。「変更を保存しますか？」のダイアログは引き続き表示されます。",
        autoQuitPredictableNote: "通常ウインドウなしで動作するアプリは、終了されることはありません。",
        autoQuitExceptionsTitle: "例外",
        autoQuitExceptionsCaption: "このリストのアプリは、ウインドウがなくても開いたままになります。",
        autoQuitExceptionsEmpty: "例外はありません",
        autoQuitAddApp: "アプリを追加…",

        uninstallerName: "アンインストーラ",
        uninstallerEnableCaption: "アプリを、それが残すキャッシュ、環境設定、ログ、残存ファイルもろとも削除します。",
        uninstallerStep1: "アプリを設定にドラッグするか、リストから1つ選びます。",
        uninstallerStep2: "見つかったファイルと、それらが占める容量を確認します。",
        uninstallerStep3: "必要なものをゴミ箱に移動します。完全には削除されません。",
        uninstallerMenuItem: "アプリをアンインストール…",
        uninstallerDropTitle: "ここにアプリをドラッグ",
        uninstallerDropSubtitle: "またはスキャンするアプリを選択",
        uninstallerChoose: "アプリを選択…",
        uninstallerEmptyNote: "確認なしに削除されるものはありません。",
        uninstallerFDANote: "より徹底的にスキャンするにはフルディスクアクセスを許可してください。",
        uninstallerFDAGrant: "アクセスを許可…",
        uninstallerFDAHint: "リストで Vorssaint をオンにします。表示されない場合は + をクリックし、アプリケーションから Vorssaint を選びます。アクセス権はアプリを再度開いた後に有効になります。",
        uninstallerFDARelaunch: "今すぐ再起動",
        uninstallerScanning: "ファイルをスキャン中…",
        uninstallerRemoving: "ゴミ箱に移動中…",
        uninstallerFoundTitle: "件見つかりました",
        uninstallerSelectedFormat: "%d／%d 件を選択中",
        uninstallerRemove: "ゴミ箱に移動",
        uninstallerCancel: "キャンセル",
        uninstallerDoneTitle: "完了！",
        uninstallerFreedFormat: "%@ を回復しました",
        uninstallerSomeFailed: "一部の項目をゴミ箱に移動できませんでした。",
        uninstallerAnother: "別のアプリをアンインストール",
        uninstallerCatApp: "アプリケーション",
        uninstallerCatSupport: "サポート",
        uninstallerCatCaches: "キャッシュ",
        uninstallerCatPreferences: "環境設定",
        uninstallerCatContainers: "コンテナ",
        uninstallerCatLogs: "ログ",
        uninstallerCatState: "保存された状態",
        uninstallerCatOther: "その他",

        shelfName: "シェルフ",
        shelfEnable: "ファイルをドラッグする一時置き場",
        shelfEnableCaption: "ファイル、画像、テキストを集めておき、あとからどこへでもドラッグできるフローティングの置き場です。",
        shelfHowTitle: "使いかた",
        shelfStep1: "⌃⌥⌘D を押すか、ドラッグ中にマウスを振って開きます。",
        shelfStep2: "ファイル、画像、リンク、テキストをドロップして保持します。",
        shelfStep3: "必要なときに、各項目をどのアプリへでもドラッグして取り出します。",
        shelfShakeToggle: "ドラッグ中にマウスを振って開く",
        shelfShakeCaption: "項目を持ったままポインタをすばやく振ると、カーソルの近くに呼び出せます。",
        shelfHotkeyLabel: "ショートカット",
        shelfOpenNow: "今すぐ開く",
        shelfNoPermission: "アクセス権は不要です。",
        shelfMenuItem: "シェルフを開く",
        shelfTitle: "シェルフ",
        shelfEmpty: "ここに項目をドラッグ",
        shelfClearAll: "すべてを消去",
        shelfRemoveSelected: "選択した項目を削除",
        shelfSelectedFormat: "%d 件を選択中",
        shelfHint: "クリックで選択。外へドラッグして使用。",
        shelfItemImage: "画像",

        breakdownMeasuring: "計測中…",

        mixerSection: "音量ミキサー",
        mixerEmpty: "オーディオを使用するアプリがここに表示されます",
        mixerUnavailable: "macOS 14.4 以降で利用できます",
        mixerPermissionBody: "アプリごとの音量を調整するには、システム設定で「画面とシステムオーディオ収録」を許可してください。オーディオが記録されることはありません。",
        mixerResetTooltip: "100% にリセット",

        updatesSection: "アップデート",
        autoCheckToggle: "アップデートを自動的に確認",
        checkNowButton: "今すぐ確認",
        updateChecking: "確認中…",
        updateUpToDate: "最新バージョンを使用しています。",
        updateAvailablePrefix: "アップデートが利用できます：",
        updateInstallButton: "ダウンロードしてインストール",
        updateDownloading: "アップデートをダウンロード中…",
        updateInstalling: "インストールして再起動中…",
        updateFailedPrefix: "確認できませんでした：",
        updateLastChecked: "前回の確認：",
        updateNotifyTitle: "Vorssaint のアップデート",
        menuCheckUpdates: "アップデートを確認…",

        permissionRequired: "アクセス権が必要です",
        permissionAccessibility: "アクセシビリティ",
        permissionScreenRecording: "画面収録",
        permissionGranted: "許可済み",
        permissionMissing: "未許可",
        permissionOpenSettings: "システム設定を開く…",
        permissionRequest: "アクセス権を要求",
        permissionRestartNote: "許可後、macOS がアプリの再オープンを求めることがあります。",

        aboutDescription: "あなたの Mac のためのユーティリティハブ。\n省エネルギー、システムモニタ、スクロール、ウインドウスイッチャーを、メニューバーから。",
        versionPrefix: "バージョン",
        reviewIntro: "はじめにを見直す",
        viewOnGitHub: "GitHub で見る",

        obContinue: "続ける",
        obBack: "戻る",
        obSkipStep: "このステップをスキップ",
        obStart: "Vorssaint を開く",
        obStepWelcomeTitle: "Vorssaint へようこそ",
        obStepWelcomeBody: "日々の macOS をもっと快適にする、控えめなメニューバーユーティリティです。",
        obWelcomeBullet1Title: "省エネルギーを思いどおりに",
        obWelcomeBullet1Body: "ふたを閉じたままでも、好きなだけ Mac をスリープさせずに使えます。",
        obWelcomeBullet2Title: "システムをひと目で把握",
        obWelcomeBullet2Body: "CPU・GPU・バッテリーの温度、ハードウェア使用状況、メモリプレッシャーをリアルタイムで。",
        obWelcomeBullet3Title: "マウスとウインドウを自分流に",
        obWelcomeBullet3Body: "マウスのスクロール反転と、サムネール付きのウインドウスイッチャー。",
        obLanguageLabel: "言語",
        obStepAccessibilityTitle: "アクセシビリティ",
        obStepAccessibilityBody: "マウスのスクロールを反転したり、ウインドウスイッチャーがキーボードに反応したりするために必要です。",
        obAccessibilityWhy: "アプリが監視するのはマウスホイールとスイッチャーのショートカットだけです。記録したり、どこかに送信したりすることはありません。",
        obStepRecordingTitle: "画面収録",
        obStepRecordingBody: "スイッチャーで、アイコンだけでなく実際のウインドウのサムネールを表示できるようになります。",
        obRecordingWhy: "サムネールはその場で生成され、メモリ内にとどまり、Mac の外に出ることはありません。許可しなくても、スイッチャーはアイコンで動作します。",
        obStepMonitorTitle: "システムモニタ",
        obStepMonitorBody: "パネルに CPU・GPU・バッテリーの温度、ハードウェア使用状況、メモリプレッシャーが表示されます。",
        obMonitorNoPermission: "アクセス権は不要です。センサーはシステムから直接読み取られます。",
        obStepOptionalTitle: "オプション機能",
        obStepOptionalBody: "今すぐ使いたいものをオンにしてください。すべて後から設定で変更できます。",
        obPasswordlessToggle: "パスワードを求めずにふたを閉じたモード",
        obPasswordlessCaption: "「pmset disablesleep」に限定したシステムルールを作成します。管理者パスワードは今、一度だけ求められます。",
        obStepStatusTitle: "チェック",
        obStepStatusBody: "使いたい機能の準備がすべて整っているか確認します。",
        obStatusRecheck: "もう一度確認",
        obStepDoneTitle: "準備完了！",
        obStepDoneBody: "Vorssaint はすでにあなたの Mac を見守っています。",
        obDoneHint: "画面右上のメニューバーで、ブラックホールを探してください。",
        obWhatsNewTitle: "このバージョンの新機能",
        obLanguageUpdateTitle: "あなたの言語に対応",
        obLanguageUpdateBody: "Vorssaint が複数の言語に対応しました。使いたい言語を選んでください。設定でいつでも変更できます。",

        tabMonitor: "モニタ",
        monitorMenuBarSection: "メニューバー",
        monitorMenuBarCaption: "メニューバーのアイコンの横に表示する項目を選びます。",
        monitorShowCPU: "CPU",
        monitorShowMemory: "メモリ",
        monitorShowNetwork: "ネットワーク",
        monitorShowPowerLabel: "電源",
        monitorIntervalLabel: "更新間隔",
        monitorInterval1: "1秒",
        monitorInterval2: "2秒",
        monitorInterval5: "5秒",
        monitorPanelSection: "パネル",

        networkSection: "ネットワーク",
        networkDownload: "ダウンロード",
        networkUpload: "アップロード",
        networkThisSession: "このセッション",
        networkMeasuring: "計測中…",

        powerSection: "電源",
        powerSystem: "システム",
        powerAdapter: "アダプタ",
        powerBattery: "バッテリー",
        powerCharging: "充電中",
        powerOnBattery: "バッテリー駆動",
        powerPluggedIn: "電源に接続",
        powerUnavailable: "この Mac では電源の計測値を利用できません",
        powerAdapterMaxFormat: "最大 %@",
        monitorShowGPU: "GPU",
        monitorGraphsSection: "グラフ",
        monitorGraphsCaption: "経過に応じてグラフを表示する項目を選びます。",

        updateBannerTitle: "アップデートが利用できます",
        updateBannerAction: "アップデート",
        obStepMenuBarTitle: "メニューバーの計測値",
        obStepMenuBarBody: "アイコンの横に表示する項目を選びます。上のプレビューがリアルタイムで更新されます。",
        obStepMenuBarNote: "新機能：パネルのネットワークと電源のブロック、そしてグラフ。すべて後から設定 › モニタで微調整できます。",
        monitorMemoryStyleLabel: "メモリの表示",
        memoryStyleDot: "ドット",
        memoryStylePercent: "%",
        memoryStyleBoth: "両方",

        systemUptime: "稼働時間",
        powerHealth: "バッテリーの状態",
        powerCycles: "回",
        speedTestRun: "速度テスト",
        speedTestAgain: "もう一度テスト",
        speedTestLatency: "レイテンシ",
        speedTestTesting: "テスト中…",
        speedTestFailed: "テストに失敗しました",

        monitorShowInPanel: "パネルに表示",
        monitorItemUptime: "稼働時間",
        monitorItemNetSpeed: "リアルタイム速度",
        monitorItemNetTotals: "セッション合計",
        monitorItemNetTest: "速度テスト",
        monitorPanelConfigHint: "ブロックを開いて、表示する内容を選びます。",
        monitorOrderSection: "セクションの並び順",
        monitorOrderHint: "ドラッグしてパネルのセクションを並べ替えます。パネル内の各セクションのシェブロンで折りたためます。",
        obStepPanelTitle: "パネルに表示する内容",
        obStepPanelBody: "各ブロックを開いて、アイコンをクリックしたときに表示する内容を細かく選びます。",

        cleaningMenuItem: "クリーニングモード",
        cleaningOverlayTitle: "クリーニングのためキーボードをロック中",
        cleaningOverlaySubtitle: "同じキーを5回押すとロックを解除します",
        cleaningOverlayUnlock: "ロックを解除",
        cleaningOverlayMouseHint: "マウスとトラックパッドはそのまま使えます",
        cleaningNeedsAxTitle: "アクセシビリティが必要です",
        cleaningNeedsAxBody: "キーボードを安全にロックするには、Vorssaint にアクセシビリティのアクセス権が必要です。システム設定で許可して、もう一度お試しください。",

        tabSupport: "支援",
        donateHeading: "Vorssaint を支援する",
        donateMessage: "わたしの公開プロジェクトはすべて、これからもずっと完全無料です。サブスクリプションも広告もありません。それを支え続けられるのは、コミュニティの応援だけです。Vorssaint がお役に立っているなら、一杯のコーヒーが本当に力になります。",
        donateButton: "Buy me a coffee",
        donateThanks: "来てくれてありがとう。🖤",
        obStepDonateTitle: "Vorssaint を気に入ってもらえましたか？🖤",
        showMenuBarIcon: "メニューバーにアイコンを表示",
        showMenuBarIconCaption: "Vorssaint のアイコンが消えた場合（メニューバーに空きがなくなると macOS がアイコンを隠すことがあり、ノッチのある Mac でよく起こります）、アプリケーションまたは Spotlight から Vorssaint を開き直してください。アイコンが再作成され、それでも隠れている場合はこのウインドウが開きます。ここまでたどり着けるなら、上のボタンでも同じことができます。メニューバーのアイコンを減らすか、Vorssaint の計測値を減らすと、起こりにくくなります。"
    )
}
