// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// Deutsch — translated and hand-checked, not machine output.
extension Strings {
    static let de = Strings(
        statusIdleTooltip: "Vorssaint: normaler Ruhezustand",
        statusActiveUntil: "Vorssaint: aktiv bis",
        statusActiveIndefinite: "Vorssaint: dauerhaft aktiv",
        menuEnableAwake: "Wachhalten aktivieren",
        menuDisableAwake: "Wachhalten deaktivieren",
        menuActivateFor: "Aktivieren für…",
        menuSettings: "Einstellungen…",
        menuAbout: "Über Vorssaint",
        menuQuit: "Vorssaint beenden",
        menuHide: "Vorssaint ausblenden",
        menuHideOthers: "Andere ausblenden",
        menuShowAll: "Alle einblenden",
        menuEdit: "Bearbeiten",
        menuUndo: "Widerrufen",
        menuRedo: "Wiederholen",
        menuCut: "Ausschneiden",
        menuCopy: "Kopieren",
        menuPaste: "Einsetzen",
        menuSelectAll: "Alles auswählen",
        menuWindow: "Fenster",
        menuMinimize: "Im Dock ablegen",
        menuZoom: "Zoomen",
        menuClose: "Schließen",

        minutes15: "15 Minuten",
        minutes30: "30 Minuten",
        hour1: "1 Stunde",
        hours2: "2 Stunden",
        hours4: "4 Stunden",
        hours8: "8 Stunden",
        indefinitely: "Dauerhaft",
        indefinite: "Unbegrenzt",

        panelAwake: "Mac wach",
        panelNormalSleep: "Normaler Ruhezustand",
        panelSettings: "Einstellungen",
        panelQuit: "Beenden",
        panelHotkeyHint: "Kurzbefehl schaltet um",

        keepAwakeTitle: "Wachhalten",
        keepAwakeEndsIn: "Endet in",
        keepAwakeUntilDisabled: "Aktiv, bis du es ausschaltest",
        keepAwakeNormalRules: "Der Mac folgt seinen normalen Energieregeln",
        keepAwakeOptions: "Optionen",
        keepAwakeMouseJiggle: "Zeiger leicht bewegen",
        keepAwakeMouseJiggleCaption: "Bewegt den Zeiger während einer Sitzung im gewählten Intervall leicht.",
        keepAwakeMouseJiggleInterval: "Intervall",
        keepAwakeIconTintLabel: "Farbe des aktiven Symbols",
        keepAwakeIconTintOrange: "Orange",
        keepAwakeIconTintGreen: "Grün",
        keepAwakeIconTintBlue: "Blau",
        keepAwakeIconTintPurple: "Lila",
        keepAwakeIconTintPink: "Pink",
        keepAwakeIconTintNone: "Keine Farbe",
        durationLabel: "Dauer",
        clamshellTitle: "Bei zugeklapptem Mac weiterlaufen",
        clamshellOnCaption: "Ruhezustand komplett deaktiviert. Auf den Akku achten",
        clamshellNeedsSession: "Gilt immer, wenn „Wachhalten“ aktiv ist",
        clamshellReady: "Bereit. Schaltet ohne Passwort um",
        clamshellNeedsPassword: "Fragt einmalig nach dem Administratorpasswort",

        systemSection: "System",
        temperatures: "Temperaturen",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "Batterie",
        usageSection: "Hardware-Auslastung",
        memorySection: "Speicher",
        memoryPressure: "Speicherdruck",
        pressureNormal: "Normal",
        pressureWarning: "Erhöht",
        pressureCritical: "Kritisch",
        monitorUnavailable: "Sensoren auf diesem Mac nicht verfügbar",
        energyAppsTitle: "Hoher Energieverbrauch",
        energyAppsIdle: "Kein hoher Energieverbrauch",

        notifySessionEndedTitle: "Sitzung beendet",
        notifySessionEndedBody: "Die Zeit ist abgelaufen. Der Mac wechselt wieder normal in den Ruhezustand.",
        notifyBatteryTitle: "Vorssaint deaktiviert",
        notifyBatteryBody: "Niedriger Batteriestand. Der normale Ruhezustand wurde wiederhergestellt, um die Ladung zu schonen.",
        adminPromptClamshellOn: "Vorssaint benötigt dein Passwort, um bei zugeklapptem Mac weiterzulaufen.",
        adminPromptClamshellOff: "Vorssaint benötigt dein Passwort, um den normalen Ruhezustand des Mac wiederherzustellen.",
        adminPromptRecover: "Vorssaint wurde beendet, während der Ruhezustand des Mac deaktiviert war. Gib das Passwort ein, um den normalen Ruhezustand wiederherzustellen.",
        adminPromptSudoersInstall: "Vorssaint legt eine eingeschränkte Regel an (nur pmset disablesleep), um den Modus bei geschlossenem Display ohne Passwortabfrage umzuschalten. Nur dieses eine Mal wird das Passwort benötigt.",
        adminPromptSudoersRemove: "Vorssaint entfernt die passwortfreie Regel für das geschlossene Display.",

        settingsTitle: "Vorssaint-Einstellungen",
        tabGeneral: "Allgemein",
        tabEnergy: "Energie",
        tabMouse: "Maus",
        tabSwitcher: "Umschalter",
        tabAdvanced: "Erweitert",
        tabAbout: "Über",
        tabReleaseNotes: "Neues",
        releaseNotesOnUpdateToggle: "Neuigkeiten nach Update anzeigen",
        whatsNewDontShowAgain: "Nicht mehr anzeigen",
        previewSizeLabel: "Vorschaugröße",
        previewSizeNormal: "Normal",
        previewSizeLarge: "Groß",
        previewSizeXLarge: "Sehr groß",
        settingsGroupFeatures: "Funktionen",
        advancedResetSection: "Berechtigungen",
        advancedResetDescription: "Entfernt alle Berechtigungen, die du Vorssaint erteilt hast (Bedienungshilfen, Bildschirmaufnahme, Festplattenvollzugriff und weitere), das Anmeldeobjekt und die Regel für das geschlossene Display. Praktisch für einen Neustart oder vor dem Deinstallieren. Die App bleibt installiert.",
        advancedClearButton: "Alle Berechtigungen zurücksetzen",
        advancedCleared: "Berechtigungen zurückgesetzt.",
        advancedClearConfirmTitle: "Alle Berechtigungen zurücksetzen?",
        advancedClearConfirmBody: "Funktionen, die Berechtigungen benötigen, arbeiten erst wieder, wenn du sie erneut erteilst. Deine Einstellungen bleiben erhalten.",
        advancedUninstallSection: "Deinstallieren",
        advancedUninstallDescription: "Macht alles oben Genannte, entfernt dann die Einstellungen und bewegt Vorssaint in den Papierkorb, ohne Rückstände zu hinterlassen. Die App beendet sich danach. Du kannst sie jederzeit neu installieren.",
        advancedUninstallButton: "Vorssaint vollständig deinstallieren",
        advancedUninstallConfirmTitle: "Vorssaint deinstallieren?",
        advancedUninstallConfirmBody: "Vorssaint setzt seine Berechtigungen zurück, entfernt seine Einstellungen und wandert in den Papierkorb, dann beendet es sich. Das lässt sich aus der App nicht rückgängig machen, doch sie bleibt im Papierkorb, bis du ihn leerst.",

        launchAtLogin: "Beim Anmelden öffnen",
        languageLabel: "Sprache",
        menuBarSection: "Menüleiste",
        showCountdown: "Verbleibende Zeit neben dem Symbol anzeigen",
        globalHotkeySection: "Globaler Kurzbefehl",
        hotkeyToggle: "Kurzbefehl für „Wachhalten“ aktivieren",
        hotkeyCaption: "Funktioniert in jeder App, ohne zusätzliche Berechtigungen.",

        sessionSection: "Sitzung",
        defaultDurationLabel: "Standarddauer",
        keepAwakeAutoStart: "Beim Öffnen der App aktivieren",
        keepAwakeAutoStartCaption: "Startet „Wach halten“ automatisch.",
        batteryProtectionSection: "Batterieschutz",
        batteryDisableBelow: "Deaktivieren bei Batterie unter",
        batteryNever: "Nie",
        batteryProtectionCaption: "Verhindert, dass eine vergessene Sitzung die Batterie des MacBook entlädt.",
        clamshellSection: "Zugeklappt",
        configuring: "Wird konfiguriert…",
        sudoersFailed: "Modus bei geschlossenem Display konnte nicht aktiviert werden. Erneut versuchen.",
        clamshellExplanation: "„Bei zugeklapptem Mac weiterlaufen“ deaktiviert den Ruhezustand vollständig, solange „Wachhalten“ aktiv ist, und wird automatisch zurückgesetzt, sobald die Sitzung endet oder die App beendet wird. Nutze es am besten am Netzteil.",

        scrollSection: "Scrollen",
        invertMouseScroll: "Mausscrollen umkehren",
        invertMouseScrollCaption: "Kehrt die Richtung des Mausrads um.",
        scrollTrackpadNote: "Das Trackpad bleibt unverändert: Es behält das natürliche Scrollen von macOS bei.",
        scrollActiveNow: "Mausscrollen wird gerade umgekehrt",

        switcherSection: "App-Umschalter",
        switcherEnable: "Vorssaint-Umschalter verwenden",
        switcherEnableCaption: "Wechsle Fenster mit echten Vorschaubildern, auch zwischen mehreren Fenstern derselben App.",
        switcherUsageHint: "Halte den Kurzbefehl zum Navigieren; loslassen, um das Fenster zu aktivieren. Umschalt oder ← geht zurück; Q beendet die ausgewählte App; Esc bricht ab.",
        switcherNoWindows: "Keine geöffneten Fenster",
        switcherMergeTabs: "Einen Eintrag pro App anzeigen",
        switcherMergeTabsCaption: "Fasst alle Fenster einer App zu einem Eintrag im Umschalter zusammen, statt einen Eintrag pro Fenster.",
        switcherShowFinder: "Finder ohne Fenster anzeigen",
        switcherShowFinderCaption: "Zeigt Finder im Umschalter auch dann an, wenn kein Finder-Fenster geöffnet ist.",
        dockPreviewName: "Dock Preview",
        dockPreviewEnable: "Fenster im Dock vorab anzeigen",
        dockPreviewEnableCaption: "Zeige auf eine geöffnete App im Dock, um ihre Fenster zu sehen und kurz einzublenden.",
        dockPreviewActiveNow: "Im Dock aktiv",
        dockPreviewMagnificationBlocked: "Deaktiviere die Dock-Vergrößerung, um dies zu nutzen.",
        dockPreviewDockUnavailable: "Dock-Elemente konnten nicht gelesen werden.",
        dockPreviewAutohideBeta: "Beta. Es können noch Fehler auftreten.",
        dockPreviewCloseWindow: "Fenster schließen",
        dockPreviewIntroPeek: "Zeige auf ein Vorschaubild, um kurz hineinzusehen. Klicke, um das Fenster zu öffnen.",
        dockPreviewIntroSettingsHint: "Du kannst das später in Einstellungen › Switcher ändern.",
        dockPreviewIntroLater: "Jetzt nicht",
        dockPreviewIntroEnable: "Dock Preview aktivieren",
        dockPreviewIntroMagnificationAction: "Deaktiviere die Dock-Vergrößerung, um es zu aktivieren.",

        cutPasteName: "Ausschneiden & Einsetzen",
        cutPasteEnable: "Dateien im Finder ausschneiden & einsetzen",
        cutPasteEnableCaption: "Verwende ⌘X zum Ausschneiden und ⌘V, um Dateien und Ordner im Finder zu bewegen.",
        cutPasteHowTitle: "So geht's",
        cutPasteStep1: "Wähle Objekte im Finder aus und drücke ⌘X, um sie auszuschneiden.",
        cutPasteStep2: "Öffne den Zielordner und drücke ⌘V, um sie dorthin zu bewegen.",
        cutPasteTextNote: "In Textfeldern (etwa beim Umbenennen) funktionieren ⌘X und ⌘V weiterhin wie gewohnt.",
        cutPasteActiveNow: "Bereit zum Ausschneiden im Finder",
        cutPasteAutomationNote: "Beim ersten Mal fragt macOS um Erlaubnis, den Finder zu steuern.",
        cutReadyTitle: "Ausgeschnitten",
        cutReadyHint: "im Zielordner zum Bewegen",
        cutCancel: "Ausschneiden abbrechen",
        cutDoneTitle: "Bewegt!",
        cutMovedSingular: "1 Objekt bewegt",
        cutMovedPluralFormat: "%d Objekte bewegt",
        cutSomeFailed: "Einige Objekte konnten nicht bewegt werden",

        autoQuitName: "Beim Schließen beenden",
        autoQuitEnable: "App beenden, wenn ihr letztes Fenster schließt",
        autoQuitEnableCaption: "Das Schließen des letzten Fensters einer App beendet sie auch.",
        autoQuitActiveNow: "Aktiv und überwacht Fenster",
        autoQuitHowTitle: "So funktioniert's",
        autoQuitStep1: "Schließe das letzte Fenster einer App (⌘W oder der rote Knopf).",
        autoQuitStep2: "Die App beendet sich von selbst. „Sichern?“-Dialoge erscheinen weiterhin.",
        autoQuitPredictableNote: "Apps, die normalerweise ohne Fenster laufen, werden nie beendet.",
        autoQuitExceptionsTitle: "Ausnahmen",
        autoQuitExceptionsCaption: "Apps in dieser Liste bleiben auch ohne Fenster geöffnet.",
        autoQuitExceptionsEmpty: "Keine Ausnahmen",
        autoQuitAddApp: "App hinzufügen…",

        uninstallerName: "Deinstallationsprogramm",
        uninstallerEnableCaption: "Entfernt eine App samt der Caches, Einstellungen, Protokolle und Rückstände, die sie hinterlässt.",
        uninstallerStep1: "Ziehe eine App in die Einstellungen oder wähle eine aus der Liste.",
        uninstallerStep2: "Prüfe die gefundenen Dateien und wie viel Platz sie belegen.",
        uninstallerStep3: "Bewege in den Papierkorb, was du möchtest. Nichts wird endgültig gelöscht.",
        uninstallerMenuItem: "Eine App deinstallieren…",
        uninstallerDropTitle: "Ziehe eine App hierher",
        uninstallerDropSubtitle: "oder wähle eine zur Analyse",
        uninstallerChoose: "App auswählen…",
        uninstallerPickerTitle: "App auswählen",
        uninstallerPickerSearch: "Apps suchen",
        uninstallerPickerEmpty: "Keine Apps gefunden",
        uninstallerEmptyNote: "Ohne deine Bestätigung wird nichts entfernt.",
        uninstallerFDANote: "Erteile Festplattenvollzugriff für eine gründlichere Analyse.",
        uninstallerFDAGrant: "Zugriff erteilen…",
        uninstallerFDAHint: "Aktiviere Vorssaint in der Liste. Fehlt es dort, klicke auf + und wähle Vorssaint unter „Programme“. Der Zugriff gilt erst, nachdem du die App erneut öffnest.",
        uninstallerFDARelaunch: "Jetzt neu öffnen",
        uninstallerScanning: "Dateien werden analysiert…",
        uninstallerRemoving: "Wird in den Papierkorb bewegt…",
        uninstallerFoundTitle: "gefunden",
        uninstallerSelectedFormat: "%d von %d ausgewählt",
        uninstallerRemove: "In den Papierkorb legen",
        uninstallerCancel: "Abbrechen",
        uninstallerDoneTitle: "Fertig!",
        uninstallerFreedFormat: "%@ freigegeben",
        uninstallerSomeFailed: "Einige Objekte konnten nicht in den Papierkorb bewegt werden.",
        uninstallerAnother: "Weitere deinstallieren",
        uninstallerCatApp: "Programm",
        uninstallerCatSupport: "Unterstützung",
        uninstallerCatCaches: "Caches",
        uninstallerCatPreferences: "Einstellungen",
        uninstallerCatContainers: "Container",
        uninstallerCatLogs: "Protokolle",
        uninstallerCatState: "Gesicherter Zustand",
        uninstallerCatOther: "Sonstiges",

        urlCleanerName: "URL bereinigen",
        urlCleanerEnable: "Kopierte URLs bereinigen",
        urlCleanerEnableCaption: "Entfernt Tracking-Parameter aus kopierten Links.",
        urlCleanerActiveNow: "Aktiv und beobachtet die Zwischenablage",
        urlCleanerManualTitle: "Jetzt bereinigen",
        urlCleanerInputPlaceholder: "URL einfügen",
        urlCleanerOutputPlaceholder: "Die bereinigte URL erscheint hier",
        urlCleanerCleanButton: "Bereinigen",
        urlCleanerPasteButton: "Einfügen",
        urlCleanerCopyButton: "Kopieren",
        urlCleanerClearButton: "Feld leeren",
        urlCleanerNoURL: "Füge eine gültige URL ein.",
        urlCleanerNoChange: "Nichts zu bereinigen.",
        urlCleanerCleaned: "URL bereinigt.",
        urlCleanerCopied: "Kopiert.",
        urlCleanerLocalNote: "Lokal. Kein Netzwerk.",

        homebrewName: "Homebrew",
        homebrewEnableCaption: "Suche, installiere und entferne Formeln und Casks.",
        homebrewMissingTitle: "Homebrew nicht gefunden",
        homebrewMissingBody: "Vorssaint kann Terminal mit dem offiziellen Homebrew-Installer öffnen. Terminal zeigt die Schritte und fragt bei Bedarf nach deinem Passwort.",
        homebrewInstallHomebrew: "Homebrew installieren",
        homebrewInstallHomebrewCaption: "Wenn Terminal fertig ist, komm zurück und klicke auf Aktualisieren.",
        homebrewInstallHomebrewOpened: "Installer in Terminal geöffnet.",
        homebrewShellSetupTitle: "Terminal-Konfiguration abschließen",
        homebrewShellSetupBody: "Homebrew ist installiert, aber Terminal findet den Befehl brew vielleicht noch nicht. Vorssaint kann Terminal mit dem Konfigurationsbefehl öffnen.",
        homebrewShellSetupButton: "Terminal konfigurieren",
        homebrewShellSetupOpened: "Befehl in Terminal geöffnet. Komm danach zurück und klicke auf Aktualisieren.",
        homebrewRefresh: "Aktualisieren",
        homebrewSearchPlaceholder: "Pakete suchen",
        homebrewKeyboardHint: "Leertaste oder Eingabe schließt das macOS-Panel. Nutze die Suchtaste.",
        homebrewSearchButton: "Suchen",
        homebrewSearchResults: "Ergebnisse",
        homebrewInstalled: "Installiert",
        homebrewAll: "Alle",
        homebrewFormulas: "Formeln",
        homebrewCasks: "Casks",
        homebrewNoPackages: "Keine Pakete gefunden",
        homebrewNoSelection: "Wähle ein installiertes Paket oder suche ein neues.",
        homebrewDetailsTitle: "Paketdetails",
        homebrewInstall: "Installieren",
        homebrewUninstall: "Deinstallieren",
        homebrewOpenTerminal: "Terminal öffnen",
        homebrewCancelOperation: "Abbrechen",
        homebrewClearLog: "Protokoll leeren",
        homebrewLogTitle: "Protokoll",
        homebrewVersion: "Version",
        homebrewDescription: "Typ",
        homebrewHomepage: "Website öffnen",
        homebrewPopularity: "Beliebtheit",
        homebrewPopularityFormat: "%@ Installationen in %@ Tagen",
        homebrewInstalledBadge: "Installiert",
        homebrewNotInstalledBadge: "Nicht installiert",
        homebrewConfirmInstallTitle: "Mit Homebrew installieren?",
        homebrewConfirmInstallBodyFormat: "Homebrew lädt %@ herunter und installiert es. Abhängigkeiten können ebenfalls installiert werden.",
        homebrewConfirmUninstallTitle: "Mit Homebrew deinstallieren?",
        homebrewConfirmUninstallBodyFormat: "Homebrew deinstalliert %@. Konfigurationsdateien können im System bleiben.",
        homebrewTerminalFallback: "Diese Aktion benötigt Terminal, um nach dem Administratorpasswort zu fragen. Vorssaint erfasst keine Passwörter.",
        homebrewLoading: "Laden…",
        homebrewSearchEmpty: "Keine Ergebnisse",
        homebrewOperationInstallFormat: "%@ wird installiert",
        homebrewOperationUninstallFormat: "%@ wird deinstalliert",
        homebrewOperationInstalledFormat: "%@ installiert.",
        homebrewOperationUninstalledFormat: "%@ deinstalliert.",
        homebrewOperationFailedFormat: "%@ konnte nicht abgeschlossen werden.",
        homebrewOperationCancelled: "Aktion abgebrochen.",
        homebrewOperationPreparing: "Vorbereiten...",
        homebrewOperationDownloading: "Dateien werden geladen...",
        homebrewOperationInstalling: "Dateien werden installiert...",
        homebrewOperationUninstalling: "Dateien werden entfernt...",
        homebrewOperationFinalizing: "Abschließen...",
        homebrewOperationRefreshing: "Liste wird aktualisiert...",
        homebrewOperationTerminal: "Im Terminal fortfahren.",
        homebrewOperationElapsedFormat: "%@ vergangen",
        homebrewOperationShowDetails: "Details anzeigen",
        homebrewOperationHideDetails: "Details ausblenden",
        homebrewOperationTechnicalLog: "Technische Details",
        homebrewOperationProgressUnknown: "Homebrew hat noch keinen Prozentsatz gemeldet.",

        mediaName: "Medien",
        mediaEnableCaption: "Komprimiere Videos und Bilder, erstelle GIFs und extrahiere Text lokal.",
        mediaLocalNote: "Lokal. Kein Netzwerk.",
        mediaToolVideo: "Video",
        mediaToolGIF: "GIF",
        mediaToolImage: "Bild",
        mediaToolText: "Text",
        mediaSelectFile: "Datei wählen",
        mediaDropHint: "Ziehe eine Datei hierher oder klicke zum Auswählen.",
        mediaOutput: "Ausgabe",
        mediaOutputAutomatic: "Automatisch",
        mediaChooseOutput: "Ziel",
        mediaStartVideo: "Video komprimieren",
        mediaStartGIF: "GIF erstellen",
        mediaStartImage: "Bild komprimieren",
        mediaStartText: "Text extrahieren",
        mediaCancel: "Abbrechen",
        mediaStartTime: "Start",
        mediaEndTime: "Ende",
        mediaQuality: "Komprimierung",
        mediaCompressionLow: "Niedrig",
        mediaCompressionMedium: "Mittel",
        mediaCompressionHigh: "Hoch",
        mediaMaxSize: "Größe",
        mediaWidth: "Breite",
        mediaFPS: "FPS",
        mediaKeepAudio: "Audio behalten",
        mediaCodec: "Codec",
        mediaFormat: "Format",
        mediaStripMetadata: "Metadaten entfernen",
        mediaLoopGIF: "GIF wiederholen",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "Genau",
        mediaOCRFast: "Schnell",
        mediaLanguageCorrection: "Sprachkorrektur",
        mediaTextOutputNote: "Extrahierter Text kann kopiert und als TXT gespeichert werden.",
        mediaRunning: "Verarbeitung",
        mediaCompleted: "Fertig",
        mediaCancelled: "Abgebrochen.",
        mediaOpenInFinder: "Anzeigen",
        mediaCopyText: "Text kopieren",
        mediaRunAgain: "Erneut ausführen",
        mediaEmptyText: "Kein Text gefunden.",
        mediaResultSavedFormat: "Gespeichert als %@",
        mediaResultSizeFormat: "%@ zu %@",
        mediaErrorNoFile: "Wähle zuerst eine Datei.",
        mediaErrorNoVideo: "Diese Datei hat keine Videospur.",
        mediaErrorSameOutput: "Wähle ein Ziel, das nicht die Originaldatei ist.",
        mediaErrorUnsupported: "Format wird von macOS nicht unterstützt.",

        shelfName: "Ablage",
        shelfEnable: "Temporäre Ablage zum Ziehen von Dateien",
        shelfEnableCaption: "Ein schwebender Ort, um Dateien, Bilder und Text zu sammeln und später überallhin zu ziehen.",
        shelfHowTitle: "So geht's",
        shelfStep1: "Öffne sie mit dem Kurzbefehl oder indem du die Maus während des Ziehens schüttelst.",
        shelfStep2: "Lege Dateien, Bilder, Links oder Text darauf ab, um sie zu verwahren.",
        shelfStep3: "Ziehe jedes Objekt wieder in eine beliebige App, wenn du es brauchst.",
        shelfShakeToggle: "Durch Schütteln der Maus beim Ziehen öffnen",
        shelfShakeCaption: "Schüttle den Zeiger schnell, während du ein Objekt hältst, um die Ablage beim Cursor erscheinen zu lassen.",
        shelfHotkeyLabel: "Kurzbefehl",
        shelfOpenNow: "Jetzt öffnen",
        shelfNoPermission: "Benötigt keine Berechtigungen.",
        shelfMenuItem: "Ablage öffnen",
        shelfTitle: "Ablage",
        shelfEmpty: "Ziehe Objekte hierher",
        shelfClearAll: "Alle entfernen",
        shelfRemoveSelected: "Ausgewählte entfernen",
        shelfSelectedFormat: "%d ausgewählt",
        shelfHint: "Klicken zum Auswählen. Herausziehen zum Verwenden.",
        shelfItemImage: "Bild",

        breakdownMeasuring: "Wird gemessen…",

        mixerSection: "Lautstärkemixer",
        mixerEmpty: "Apps, die Audio nutzen, erscheinen hier",
        mixerUnavailable: "Verfügbar ab macOS 14.4",
        mixerPermissionBody: "Um die Lautstärke je App anzupassen, erlaube „Aufnahme von Bildschirm und Systemaudio“ in den Systemeinstellungen. Audio wird nie aufgenommen.",
        mixerResetTooltip: "Auf 100 % zurücksetzen",
        mixerOutputDefault: "Standard",
        mixerOutputCurrent: "aktuell",
        mixerOutputUnavailable: "Ausgabe nicht verfügbar",
        mixerOutputFallback: "Standard wird verwendet, bis dieses Gerät zurück ist.",
        mixerOutputTooltip: "Ausgabe wählen",
        mixerSystemOutputTitle: "Ausgabe",
        mixerSystemOutputNoDevices: "Keine Ausgabe gefunden",
        mixerSystemOutputTooltip: "Systemausgabe wählen",
        mixerSystemOutputErrorFormat: "Wechsel fehlgeschlagen: %@",
        mixerLowerOnHeadphonesDisconnect: "Lautstärke senken, wenn Kopfhörer getrennt werden",
        mixerLowerOnHeadphonesDisconnectCaption: "Setzt die Ausgabe auf 0%, wenn kabelgebundene oder Bluetooth-Kopfhörer getrennt werden.",
        soundOutputSwitcherTitle: "Ausgabeumschalter",
        soundOutputSwitcherEnable: "Ausgaben per Kurzbefehl wechseln",
        soundOutputSwitcherCaption: "Wähle Ausgaben und nutze den Kurzbefehl für die nächste verfügbare.",
        soundOutputSwitcherDevices: "Ausgaben im Wechsel",
        soundOutputSwitcherNoAvailableSelection: "Wähle mindestens eine verfügbare Ausgabe.",
        mixerInputTitle: "Mikrofon",
        mixerInputNoDevices: "Kein Mikrofon gefunden",
        mixerInputUnavailable: "Mikrofon nicht verfügbar",
        mixerInputFallback: "Standard wird verwendet, bis dieses Mikrofon zurück ist.",
        mixerInputTooltip: "Mikrofon wählen",
        mixerInputErrorFormat: "Wechsel fehlgeschlagen: %@",

        updatesSection: "Updates",
        autoCheckToggle: "Automatisch nach Updates suchen",
        checkNowButton: "Jetzt suchen",
        updateChecking: "Wird gesucht…",
        updateUpToDate: "Du verwendest die neueste Version.",
        updateAvailablePrefix: "Update verfügbar:",
        updateInstallButton: "Laden und installieren",
        updateDownloading: "Update wird geladen…",
        updateInstalling: "Wird installiert und neu gestartet…",
        updateFailedPrefix: "Suche fehlgeschlagen:",
        updateLastChecked: "Zuletzt gesucht:",
        updateNotifyTitle: "Vorssaint-Update",
        menuCheckUpdates: "Nach Updates suchen…",

        permissionRequired: "Berechtigung erforderlich",
        permissionAccessibility: "Bedienungshilfen",
        permissionScreenRecording: "Bildschirmaufnahme",
        permissionGranted: "Erteilt",
        permissionMissing: "Nicht erteilt",
        permissionOpenSettings: "Systemeinstellungen öffnen…",
        permissionRequest: "Zugriff erlauben",
        permissionRestartNote: "macOS bittet nach dem Erteilen möglicherweise darum, die App erneut zu öffnen.",

        aboutDescription: "Eine Werkzeugzentrale für deinen Mac.\nEnergie, Systemüberwachung, Scrollen und ein Fensterumschalter, direkt in der Menüleiste.",
        versionPrefix: "Version",
        reviewIntro: "Einführung erneut ansehen",
        viewOnGitHub: "Auf GitHub ansehen",

        obContinue: "Fortfahren",
        obBack: "Zurück",
        obSkipStep: "Diesen Schritt überspringen",
        obStart: "Vorssaint öffnen",
        obStepWelcomeTitle: "Willkommen bei Vorssaint",
        obStepWelcomeBody: "Ein dezentes Menüleisten-Werkzeug, das den macOS-Alltag praktischer macht.",
        obWelcomeBullet1Title: "Energie unter Kontrolle",
        obWelcomeBullet1Body: "Halte den Mac so lange wach, wie du möchtest, sogar wenn der Mac zugeklappt ist.",
        obWelcomeBullet2Title: "Klarer Blick aufs System",
        obWelcomeBullet2Body: "Temperaturen, CPU- und GPU-Auslastung und Speicherauslastung in Echtzeit.",
        obWelcomeBullet3Title: "Maus und Fenster nach deinem Geschmack",
        obWelcomeBullet3Body: "Umgekehrtes Mausscrollen und ein Fensterumschalter mit Vorschaubildern.",
        obLanguageLabel: "Sprache",
        obStepAccessibilityTitle: "Bedienungshilfen",
        obStepAccessibilityBody: "Erforderlich, um das Mausscrollen umzukehren und damit der Fensterumschalter auf die Tastatur reagiert.",
        obAccessibilityWhy: "Die App beobachtet nur das Mausrad und den Kurzbefehl des Umschalters. Nichts wird aufgezeichnet oder irgendwohin gesendet.",
        obStepRecordingTitle: "Bildschirmaufnahme",
        obStepRecordingBody: "Ermöglicht es dem Umschalter, echte Fenstervorschauen statt nur Symbole anzuzeigen.",
        obRecordingWhy: "Die Vorschaubilder werden im Moment erzeugt, bleiben im Speicher und verlassen deinen Mac nie. Ohne sie funktioniert der Umschalter weiterhin mit Symbolen.",
        obStepMonitorTitle: "Systemüberwachung",
        obStepMonitorBody: "Das Panel zeigt die Temperaturen von CPU, GPU und Batterie, die Hardware-Auslastung und die Speicherauslastung.",
        obMonitorNoPermission: "Keine Berechtigung nötig. Die Sensoren werden direkt aus dem System gelesen.",
        obStepOptionalTitle: "Optionale Funktionen",
        obStepOptionalBody: "Aktiviere jetzt, was du nutzen möchtest. Alles lässt sich später in den Einstellungen ändern.",
        obStepStatusTitle: "Überprüfung",
        obStepStatusBody: "Vergewissere dich, dass für die gewünschten Funktionen alles bereit ist.",
        obStatusRecheck: "Erneut prüfen",
        obStepDoneTitle: "Alles bereit!",
        obStepDoneBody: "Vorssaint kümmert sich bereits um deinen Mac.",
        obDoneHint: "Halte Ausschau nach dem schwarzen Loch in der Menüleiste, oben rechts auf dem Bildschirm.",
        obWhatsNewTitle: "Neu in dieser Version",
        obWhatsNewFallback: "Dieses Update enthält die neuesten Korrekturen und Verbesserungen.",
        obLanguageUpdateTitle: "Jetzt in deiner Sprache",
        obLanguageUpdateBody: "Vorssaint spricht jetzt mehrere Sprachen. Wähle die, die du verwenden möchtest; du kannst sie jederzeit in den Einstellungen ändern.",

        tabMonitor: "Überwachung",
        monitorMenuBarSection: "In der Menüleiste",
        monitorMenuBarCaption: "Wähle, was neben dem Symbol in der Menüleiste erscheint.",
        monitorCombineTemperatures: "Auslastung und Temperatur kombinieren",
        monitorCombineTemperaturesCaption: "Wenn Auslastung und Temperatur desselben Elements aktiv sind, erscheinen sie in einem Block.",
        monitorSeparateMenuBarMetrics: "Messwerte in eigene Elemente trennen",
        monitorSeparateMenuBarMetricsCaption: "Trennt aktive Blöcke in der Menüleiste und hält Auslastung und Temperatur zusammen, wenn Kombinieren aktiv ist.",
        monitorShowCPU: "CPU",
        monitorShowMemory: "Speicher",
        monitorShowNetwork: "Netzwerk",
        monitorShowPowerLabel: "Energie",
        monitorIntervalLabel: "Aktualisieren alle",
        monitorInterval1: "1 Sekunde",
        monitorInterval2: "2 Sekunden",
        monitorInterval5: "5 Sekunden",
        monitorPanelSection: "Im Panel",
        panelNavigationMode: "Panel nach Bereichen navigieren",
        panelNavigationCaption: "Zeigt jeweils einen Bereich und platziert die Navigation unten im Panel.",
        panelFooterSections: "Bereiche",
        panelFooterList: "Liste",
        fanControlBetaShow: "Fan Control (Beta) im Panel anzeigen",
        fanControlBetaSection: "Fan Control",
        fanControlBetaTitle: "Fan Control",
        fanControlBetaStatus: "Automatisch",
        fanControlBetaCaption: "Beta. Die manuelle Steuerung bleibt deaktiviert, bis jedes Mac-Modell validiert ist.",
        fanControlModeAutomatic: "Automatisch",
        fanControlModeManual: "Manuell",
        betaBadge: "BETA",
        betaFeatureWarning: "Beta. Es können noch Fehler auftreten.",

        networkSection: "Netzwerk",
        networkDownload: "Download",
        networkUpload: "Upload",
        networkThisSession: "Diese Sitzung",
        networkMeasuring: "Wird gemessen…",

        diskSection: "Festplatten",
        diskUsed: "belegt",
        diskFree: "frei",
        diskInternal: "Intern",
        diskExternal: "Extern",
        diskSelect: "Festplatte wählen",
        diskRead: "Lesen",
        diskWrite: "Schreiben",
        diskSMARTStatus: "Status",
        diskSMARTUnavailable: "SMART für dieses Laufwerk nicht verfügbar",
        diskTotalRead: "Insgesamt gelesen",
        diskTotalWritten: "Insgesamt geschrieben",
        diskTemperature: "Temperatur",
        diskHealth: "Gesundheit",
        diskPowerCycles: "Einschaltzyklen",
        diskPowerOnHours: "Betriebsstunden",
        diskUnsafeShutdowns: "Unsichere Abschaltungen",
        diskMediaErrors: "Medienfehler",
        diskEject: "Auswerfen",
        diskEjectAll: "Alle auswerfen",
        diskEjecting: "Wird ausgeworfen…",
        diskReadyToRemove: "Bereit zum Entfernen",
        diskEjectFailed: "Auswerfen fehlgeschlagen",
        diskProtectionCaption: "Vor dem Abziehen auswerfen.",
        diskNoExternal: "Kein externes Laufwerk zum Auswerfen bereit.",
        diskOpenInFinder: "Öffnen",
        diskStorageSettings: "Speicher",
        diskNoDisks: "Keine eingebundenen Laufwerke gefunden.",

        powerSection: "Energie",
        powerSystem: "System",
        powerAdapter: "Netzteil",
        powerBattery: "Batterie",
        powerCharging: "Wird geladen",
        powerOnBattery: "Im Batteriebetrieb",
        powerPluggedIn: "Am Netzteil",
        powerUnavailable: "Energiedaten auf diesem Mac nicht verfügbar",
        powerAdapterMaxFormat: "max. %@",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "CPU-Temperatur",
        monitorShowGPUTemperature: "GPU-Temperatur",
        monitorShowBatteryTemperature: "Batterietemperatur",
        monitorGraphsSection: "Diagramme",
        monitorGraphsCaption: "Wähle, welche Werte ein Diagramm über die Zeit anzeigen.",

        updateBannerTitle: "Update verfügbar",
        updateBannerAction: "Aktualisieren",
        obStepMenuBarTitle: "Werte in der Menüleiste",
        obStepMenuBarBody: "Wähle, was neben dem Symbol angezeigt wird. Die Vorschau oben aktualisiert sich live.",
        obStepMenuBarNote: "Neu: Blöcke für Netzwerk und Energie sowie Diagramme im Panel. Stelle alles später unter Einstellungen › Überwachung fein ein.",
        monitorMenuBarPresetLabel: "Stil",
        menuBarPresetReadable: "Lesbar",
        menuBarPresetDense: "Dicht",
        monitorLabelStyleLabel: "Beschriftungen",
        menuBarLabelStyleCompact: "Kompakt",
        menuBarLabelStyleClassic: "Klassisch",
        monitorMemoryStyleLabel: "Speicher anzeigen als",
        monitorMemoryPressureDot: "Speicherdruckpunkt",
        memoryStyleDot: "Punkt",
        memoryStylePercent: "%",
        memoryStyleBoth: "Beides",

        systemUptime: "Aktiv seit",
        powerHealth: "Batteriezustand",
        powerCycles: "Zyklen",
        speedTestRun: "Geschwindigkeitstest",
        speedTestAgain: "Erneut testen",
        speedTestLatency: "Latenz",
        speedTestTesting: "Wird getestet…",
        speedTestFailed: "Test fehlgeschlagen",

        monitorShowInPanel: "Im Panel anzeigen",
        panelHideItem: "Im Panel ausblenden",
        panelShowItem: "Im Panel anzeigen",
        panelHiddenItem: "Ausgeblendet",
        monitorItemUptime: "Betriebszeit",
        monitorItemNetSpeed: "Live-Geschwindigkeit",
        monitorItemNetTotals: "Sitzungssummen",
        monitorItemNetTest: "Geschwindigkeitstest",
        monitorItemDiskUsage: "Festplattennutzung",
        monitorItemDiskActivity: "Live-Aktivität",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "Externer Schutz",
        monitorItemDiskTools: "Werkzeuge",
        monitorPanelConfigHint: "Öffne einen Block, um zu wählen, was er anzeigt.",
        monitorOrderSection: "Reihenfolge der Bereiche",
        monitorOrderHint: "Ziehen, um die Panel-Bereiche neu anzuordnen, und mit dem Auge jeden ein- oder ausblenden.",
        obStepPanelTitle: "Was im Panel erscheint",
        obStepPanelBody: "Öffne jeden Block und wähle genau, was angezeigt wird, wenn du auf das Symbol klickst.",
        obStepPanelNavigationTitle: "Panel nach Bereichen",
        obStepPanelNavigationBody: "Das Panel kann jetzt jeweils einen Bereich anzeigen, mit der Navigation unten. Die Option ist in diesem Update aktiviert, damit du sie testen kannst.",

        cleaningMenuItem: "Reinigungsmodus",
        utilitiesSection: "Dienstprogramme",
        quickControlsSection: "Steuerung",
        windowMaximizeName: "Fenster maximieren",
        windowMaximizeCaption: "Der grüne Knopf maximiert, ohne einen weiteren Space zu erstellen.",
        windowMaximizeActiveNow: "Grüner Knopf aktiv",
        windowMaximizeNeedsAccessibility: "Benötigt Bedienungshilfen, um zu funktionieren.",
        cleaningPanelCaption: "Sperrt die Tastatur, damit du sicher reinigen kannst.",
        cleaningOverlayTitle: "Tastatur zum Reinigen gesperrt",
        cleaningOverlaySubtitle: "Dieselbe Taste 5-mal drücken zum Entsperren",
        cleaningOverlayUnlock: "Entsperren",
        cleaningOverlayMouseHint: "Maus und Trackpad funktionieren weiterhin",
        cleaningNeedsAxTitle: "Bedienungshilfen erforderlich",
        cleaningNeedsAxBody: "Um die Tastatur sicher zu sperren, benötigt Vorssaint die Berechtigung für Bedienungshilfen. Erteile sie in den Systemeinstellungen und versuche es erneut.",

        tabSupport: "Unterstützen",
        donateHeading: "Vorssaint unterstützen",
        donateMessage: "Alle meine öffentlichen Projekte sind und bleiben vollständig kostenlos: kein Abo, keine Werbung. Die Unterstützung der Community ist das Einzige, was sie am Leben hält. Wenn dir Vorssaint hilft, macht ein Kaffee wirklich einen Unterschied.",
        donateButton: "Buy me a coffee",
        donateThanks: "Danke, dass du hier bist. 🖤",
        supportIntroTitle: "Vorssaint ist 100% kostenlos und bleibt es immer",
        supportIntroMessage: "Ich kümmere mich in meiner freien Zeit weiter um die App. Wenn sie dir hilft, kannst du mir ganz einfach helfen, indem du sie teilst, einen Stern auf GitHub gibst oder mir einen Kaffee spendierst. Das hilft mir sehr, weiter Verbesserungen zu bringen.",
        supportIntroStarButton: "Einen Stern geben",
        supportIntroCoffeeButton: "Buy me a coffee",
        supportIntroLaterButton: "Jetzt nicht",
        showMenuBarIcon: "Menüleistensymbol anzeigen",
        showMenuBarIconCaption: "Falls das Symbol von Vorssaint verschwindet (macOS kann Menüleistensymbole ausblenden, wenn der Platz in der Leiste knapp wird, häufig bei Macs mit Notch), öffne Vorssaint erneut über „Programme“ oder Spotlight: Das stellt das Symbol wieder her und öffnet, falls es weiterhin ausgeblendet ist, dieses Fenster. Der Knopf oben bewirkt dasselbe, wenn du bereits hierher gelangst. Weniger Symbole in der Menüleiste oder weniger Vorssaint-Werte machen es deutlich unwahrscheinlicher.",
        shortcutRecording: "Neuen Kurzbefehl drücken",
        shortcutReset: "Zurücksetzen",
        shortcutInvalid: "Verwende mindestens Control, Option oder Command mit einer Taste.",
        shortcutConflictFormat: "Dieser Kurzbefehl wird bereits von %@ verwendet.",
        shortcutUnavailable: "macOS hat diesen Kurzbefehl abgelehnt. Wähle einen anderen.",
        shelfShortcutToggle: "Shelf-Kurzbefehl",
        switcherUsageHintFormat: "Halte %@ zum Navigieren; loslassen, um das Fenster zu aktivieren. Umschalt oder ← geht zurück; Q beendet die ausgewählte App; Esc bricht ab."
    )
}
