// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// 日本語 — translated and hand-checked, not machine output.
extension Strings {
    static let ja = Strings(
        statusIdleTooltip: "Vorssaint：通常のスリープ",
        statusActiveUntil: "Vorssaint：次の時刻までスリープしない",
        statusActiveIndefinite: "Vorssaint：解除するまでスリープしない",
        menuEnableAwake: "スリープ防止をオン",
        menuDisableAwake: "スリープ防止をオフ",
        menuActivateFor: "時間を指定してオン…",
        menuSettings: "設定…",
        menuAbout: "Vorssaint について",
        menuQuit: "Vorssaint を終了",
        menuHide: "Vorssaint を隠す",
        menuHideOthers: "ほかを隠す",
        menuShowAll: "すべてを表示",
        menuEdit: "編集",
        menuUndo: "取り消す",
        menuRedo: "やり直す",
        menuCut: "カット",
        menuCopy: "コピー",
        menuPaste: "ペースト",
        menuSelectAll: "すべてを選択",
        menuWindow: "ウインドウ",
        menuMinimize: "しまう",
        menuZoom: "拡大／縮小",
        menuClose: "閉じる",

        minutes15: "15分",
        minutes30: "30分",
        hour1: "1時間",
        hours2: "2時間",
        hours4: "4時間",
        hours8: "8時間",
        indefinitely: "無期限",
        indefinite: "無期限",

        panelAwake: "Mac はスリープしません",
        panelNormalSleep: "通常のスリープ",
        panelSettings: "設定",
        panelQuit: "終了",
        panelHotkeyHint: "ショートカットで切り替え",

        keepAwakeTitle: "スリープ防止",
        keepAwakeEndsIn: "残り",
        keepAwakeUntilDisabled: "オフにするまで継続",
        keepAwakeNormalRules: "Mac は通常の省エネルギー設定に従います",
        keepAwakeOptions: "オプション",
        keepAwakeMouseJiggle: "ポインタを少し動かす",
        keepAwakeMouseJiggleCaption: "セッション中、選んだ間隔でポインタを少し動かします。",
        keepAwakeMouseJiggleInterval: "間隔",
        keepAwakeIconTintLabel: "アクティブ時のアイコン色",
        keepAwakeIconTintOrange: "オレンジ",
        keepAwakeIconTintGreen: "緑",
        keepAwakeIconTintBlue: "青",
        keepAwakeIconTintPurple: "紫",
        keepAwakeIconTintPink: "ピンク",
        keepAwakeIconTintNone: "色なし",
        durationLabel: "継続時間",
        clamshellTitle: "ふたを閉じても続ける",
        clamshellOnCaption: "スリープを完全に無効化中。電源にご注意ください",
        clamshellNeedsSession: "「スリープ防止」がオンのあいだ常に適用されます",
        clamshellReady: "準備完了。パスワードなしで切り替えられます",
        clamshellNeedsPassword: "管理者パスワードは一度だけ求められます",

        systemSection: "システム",
        temperatures: "温度",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "バッテリー",
        usageSection: "ハードウェア使用状況",
        memorySection: "メモリ",
        memoryPressure: "プレッシャー",
        pressureNormal: "標準",
        pressureWarning: "注意",
        pressureCritical: "危険",
        monitorUnavailable: "この Mac ではセンサーを利用できません",
        energyAppsTitle: "大きなエネルギー使用",
        energyAppsIdle: "大きなエネルギー使用なし",

        notifySessionEndedTitle: "セッションが終了しました",
        notifySessionEndedBody: "時間になりました。Mac は再び通常どおりスリープします。",
        notifyBatteryTitle: "Vorssaint をオフにしました",
        notifyBatteryBody: "バッテリー残量が少なくなりました。充電を保護するため通常のスリープに戻しました。",
        adminPromptClamshellOn: "ふたを閉じても続けるには、Vorssaint にパスワードが必要です。",
        adminPromptClamshellOff: "Mac の通常のスリープを元に戻すにはパスワードが必要です。",
        adminPromptRecover: "Mac のスリープを無効化したまま Vorssaint が終了しました。通常のスリープに戻すにはパスワードを入力してください。",
        adminPromptSudoersInstall: "ふたを閉じたモードをパスワードなしで切り替えられるよう、Vorssaint が制限付きルール（pmset disablesleep のみ）を作成します。パスワードが必要なのはこの一度きりです。",
        adminPromptSudoersRemove: "パスワード不要のふたを閉じたモードのルールを Vorssaint が削除します。",

        settingsTitle: "Vorssaint 設定",
        tabGeneral: "一般",
        tabEnergy: "省エネルギー",
        tabMouse: "マウス",
        tabSwitcher: "スイッチャー",
        tabAdvanced: "詳細",
        tabAbout: "情報",
        tabReleaseNotes: "新機能",
        releaseNotesOnUpdateToggle: "アップデート後に新機能を表示",
        whatsNewDontShowAgain: "今後表示しない",
        previewSizeLabel: "プレビューのサイズ",
        previewSizeNormal: "標準",
        previewSizeLarge: "大",
        previewSizeXLarge: "特大",
        settingsGroupFeatures: "機能",
        advancedResetSection: "アクセス権",
        advancedResetDescription: "Vorssaint に許可したすべてのアクセス権（アクセシビリティ、画面収録、フルディスクアクセスなど）、ログイン項目、ふたを閉じたモードのルールを削除します。最初からやり直すときや、アンインストールの前に便利です。アプリはインストールされたまま残ります。",
        advancedClearButton: "すべてのアクセス権を消去",
        advancedCleared: "アクセス権を消去しました。",
        advancedClearConfirmTitle: "すべてのアクセス権を消去しますか？",
        advancedClearConfirmBody: "アクセス権が必要な機能は、再度許可するまで動作しなくなります。設定はそのまま保持されます。",
        advancedUninstallSection: "アンインストール",
        advancedUninstallDescription: "上記をすべて実行したうえで、環境設定を削除し、Vorssaint をゴミ箱に移動して、何も残しません。完了後にアプリは終了します。いつでも再インストールできます。",
        advancedUninstallButton: "Vorssaint を完全にアンインストール",
        advancedUninstallConfirmTitle: "Vorssaint をアンインストールしますか？",
        advancedUninstallConfirmBody: "Vorssaint はアクセス権を消去し、環境設定を削除し、ゴミ箱に移動してから終了します。この操作はアプリからは取り消せませんが、ゴミ箱を空にするまではゴミ箱に残ります。",

        launchAtLogin: "ログイン時に起動",
        languageLabel: "言語",
        menuBarSection: "メニューバー",
        showCountdown: "アイコンの横に残り時間を表示",
        globalHotkeySection: "グローバルショートカット",
        hotkeyToggle: "「スリープ防止」のショートカットを有効にする",
        hotkeyCaption: "追加のアクセス権なしで、どのアプリでも使えます。",

        sessionSection: "セッション",
        defaultDurationLabel: "デフォルトの継続時間",
        keepAwakeAutoStart: "アプリ起動時にオンにする",
        keepAwakeAutoStartCaption: "「スリープ防止」を自動的に開始します。",
        batteryProtectionSection: "バッテリー保護",
        batteryDisableBelow: "バッテリーが次の値を下回ったらオフにする",
        batteryNever: "しない",
        batteryProtectionCaption: "オンのままになったセッションが MacBook のバッテリーを消耗させるのを防ぎます。",
        clamshellSection: "ふたを閉じたモード",
        configuring: "設定中…",
        sudoersFailed: "ふたを閉じたモードを有効にできませんでした。もう一度お試しください。",
        clamshellExplanation: "「ふたを閉じても続ける」は、「スリープ防止」がオンのあいだスリープを完全に無効化し、セッションの終了時またはアプリの終了時に自動的に元に戻ります。電源に接続した状態での使用をおすすめします。",

        scrollSection: "スクロール",
        invertMouseScroll: "マウスのスクロールを反転",
        invertMouseScrollCaption: "マウスホイールのスクロール方向を逆にします。",
        scrollTrackpadNote: "トラックパッドはそのままで、macOS のナチュラルなスクロールを維持します。",
        scrollActiveNow: "現在マウスのスクロールを反転中",

        switcherSection: "アプリスイッチャー",
        switcherEnable: "Vorssaint のスイッチャーを使う",
        switcherEnableCaption: "実際のサムネールを見ながらウインドウを切り替えられます。同じアプリの複数ウインドウ間でも切り替えできます。",
        switcherUsageHint: "ショートカットを押したまま移動し、放すとウインドウがアクティブになります。Shift または ← で戻る、Q で選択中のアプリを終了、Esc でキャンセルします。",
        switcherNoWindows: "開いているウインドウはありません",
        switcherMergeTabs: "アプリごとに1つにまとめて表示",
        switcherMergeTabsCaption: "スイッチャーで、アプリのすべてのウインドウをウインドウごとではなく1つの項目にまとめます。",
        switcherShowFinder: "ウインドウなしの Finder を表示",
        switcherShowFinderCaption: "Finder のウインドウが開いていない場合でも、スイッチャーに Finder を表示します。",
        dockPreviewName: "Dock Preview",
        dockPreviewEnable: "Dock でウインドウをプレビュー",
        dockPreviewEnableCaption: "Dock の開いているアプリにポインタを重ねると、ウインドウを確認して一時表示できます。",
        dockPreviewActiveNow: "Dock で有効",
        dockPreviewMagnificationBlocked: "使用するには Dock の拡大をオフにしてください。",
        dockPreviewDockUnavailable: "Dock の項目を読み取れませんでした。",
        dockPreviewAutohideBeta: "ベータ版です。一部の不具合が残っている場合があります。",
        dockPreviewCloseWindow: "ウインドウを閉じる",
        dockPreviewIntroPeek: "サムネールにポインタを重ねると一時表示できます。クリックするとそのウインドウを開きます。",
        dockPreviewIntroSettingsHint: "あとから設定 › Switcher で変更できます。",
        dockPreviewIntroLater: "今はしない",
        dockPreviewIntroEnable: "Dock Preview を有効にする",
        dockPreviewIntroMagnificationAction: "有効にするには Dock の拡大をオフにしてください。",

        cutPasteName: "カット＆ペースト",
        cutPasteEnable: "Finder でファイルをカット＆ペースト",
        cutPasteEnableCaption: "⌘X でカット、⌘V で Finder のファイルやフォルダを移動できます。",
        cutPasteHowTitle: "使いかた",
        cutPasteStep1: "Finder で項目を選択し、⌘X を押してカットします。",
        cutPasteStep2: "移動先のフォルダを開き、⌘V を押してそこへ移動します。",
        cutPasteTextNote: "テキストフィールド内では（名前の変更時など）、⌘X と ⌘V はこれまでどおり動作します。",
        cutPasteActiveNow: "Finder でカットできます",
        cutPasteAutomationNote: "初回は、macOS が Finder を制御する許可を求めます。",
        cutReadyTitle: "カットしました",
        cutReadyHint: "移動先のフォルダで",
        cutCancel: "カットをキャンセル",
        cutDoneTitle: "移動しました！",
        cutMovedSingular: "1項目を移動しました",
        cutMovedPluralFormat: "%d項目を移動しました",
        cutSomeFailed: "一部の項目を移動できませんでした",

        autoQuitName: "閉じたら終了",
        autoQuitEnable: "最後のウインドウを閉じたらアプリを終了",
        autoQuitEnableCaption: "アプリの最後のウインドウを閉じると、そのアプリも終了します。",
        autoQuitActiveNow: "オンにして、ウインドウを監視中",
        autoQuitHowTitle: "しくみ",
        autoQuitStep1: "アプリの最後のウインドウを閉じます（⌘W または赤いボタン）。",
        autoQuitStep2: "アプリは自動的に終了します。「変更を保存しますか？」のダイアログは引き続き表示されます。",
        autoQuitPredictableNote: "通常ウインドウなしで動作するアプリは、終了されることはありません。",
        autoQuitExceptionsTitle: "例外",
        autoQuitExceptionsCaption: "このリストのアプリは、ウインドウがなくても開いたままになります。",
        autoQuitExceptionsEmpty: "例外はありません",
        autoQuitAddApp: "アプリを追加…",

        uninstallerName: "アンインストーラ",
        uninstallerEnableCaption: "アプリを、それが残すキャッシュ、環境設定、ログ、残存ファイルもろとも削除します。",
        uninstallerStep1: "アプリを設定にドラッグするか、リストから1つ選びます。",
        uninstallerStep2: "見つかったファイルと、それらが占める容量を確認します。",
        uninstallerStep3: "必要なものをゴミ箱に移動します。完全には削除されません。",
        uninstallerMenuItem: "アプリをアンインストール…",
        uninstallerDropTitle: "ここにアプリをドラッグ",
        uninstallerDropSubtitle: "またはスキャンするアプリを選択",
        uninstallerChoose: "アプリを選択…",
        uninstallerPickerTitle: "アプリを選択",
        uninstallerPickerSearch: "アプリを検索",
        uninstallerPickerEmpty: "アプリが見つかりません",
        uninstallerEmptyNote: "確認なしに削除されるものはありません。",
        uninstallerFDANote: "より徹底的にスキャンするにはフルディスクアクセスを許可してください。",
        uninstallerFDAGrant: "アクセスを許可…",
        uninstallerFDAHint: "リストで Vorssaint をオンにします。表示されない場合は + をクリックし、アプリケーションから Vorssaint を選びます。アクセス権はアプリを再度開いた後に有効になります。",
        uninstallerFDARelaunch: "今すぐ再起動",
        uninstallerScanning: "ファイルをスキャン中…",
        uninstallerRemoving: "ゴミ箱に移動中…",
        uninstallerFoundTitle: "件見つかりました",
        uninstallerSelectedFormat: "%d／%d 件を選択中",
        uninstallerRemove: "ゴミ箱に移動",
        uninstallerCancel: "キャンセル",
        uninstallerDoneTitle: "完了！",
        uninstallerFreedFormat: "%@ を回復しました",
        uninstallerSomeFailed: "一部の項目をゴミ箱に移動できませんでした。",
        uninstallerAnother: "別のアプリをアンインストール",
        uninstallerCatApp: "アプリケーション",
        uninstallerCatSupport: "サポート",
        uninstallerCatCaches: "キャッシュ",
        uninstallerCatPreferences: "環境設定",
        uninstallerCatContainers: "コンテナ",
        uninstallerCatLogs: "ログ",
        uninstallerCatState: "保存された状態",
        uninstallerCatOther: "その他",

        urlCleanerName: "URL をクリーン",
        urlCleanerEnable: "コピーした URL をクリーン",
        urlCleanerEnableCaption: "コピーしたリンクからトラッキング用パラメータを削除します。",
        urlCleanerActiveNow: "有効。クリップボードを監視中",
        urlCleanerManualTitle: "今すぐクリーン",
        urlCleanerInputPlaceholder: "URL をペースト",
        urlCleanerOutputPlaceholder: "クリーンな URL がここに表示されます",
        urlCleanerCleanButton: "クリーン",
        urlCleanerPasteButton: "ペースト",
        urlCleanerCopyButton: "コピー",
        urlCleanerClearButton: "欄をクリア",
        urlCleanerNoURL: "有効な URL をペーストしてください。",
        urlCleanerNoChange: "削除するものはありません。",
        urlCleanerCleaned: "URL をクリーンしました。",
        urlCleanerCopied: "コピーしました。",
        urlCleanerLocalNote: "ローカル。通信なし。",

        homebrewName: "Homebrew",
        homebrewEnableCaption: "formula と cask を検索、インストール、削除します。",
        homebrewMissingTitle: "Homebrew が見つかりません",
        homebrewMissingBody: "Vorssaint は公式 Homebrew インストーラを Terminal で開けます。Terminal に手順が表示され、必要ならパスワードを求められます。",
        homebrewInstallHomebrew: "Homebrew をインストール",
        homebrewInstallHomebrewCaption: "Terminal が終わったら、ここに戻って更新をクリックしてください。",
        homebrewInstallHomebrewOpened: "インストーラを Terminal で開きました。",
        homebrewShellSetupTitle: "Terminal 設定を完了",
        homebrewShellSetupBody: "Homebrew はインストールされていますが、Terminal がまだ brew コマンドを見つけられない場合があります。Vorssaint は設定コマンドを Terminal で開けます。",
        homebrewShellSetupButton: "Terminal を設定",
        homebrewShellSetupOpened: "コマンドを Terminal で開きました。終わったら戻って更新をクリックしてください。",
        homebrewRefresh: "更新",
        homebrewSearchPlaceholder: "パッケージを検索",
        homebrewKeyboardHint: "スペースまたは Return で macOS パネルが閉じます。検索ボタンを使用してください。",
        homebrewSearchButton: "検索",
        homebrewSearchResults: "結果",
        homebrewInstalled: "インストール済み",
        homebrewAll: "すべて",
        homebrewFormulas: "Formula",
        homebrewCasks: "Cask",
        homebrewNoPackages: "パッケージが見つかりません",
        homebrewNoSelection: "インストール済みパッケージを選択するか、新しいものを検索してください。",
        homebrewDetailsTitle: "パッケージ詳細",
        homebrewInstall: "インストール",
        homebrewUninstall: "アンインストール",
        homebrewOpenTerminal: "Terminal を開く",
        homebrewCancelOperation: "キャンセル",
        homebrewClearLog: "ログをクリア",
        homebrewLogTitle: "ログ",
        homebrewVersion: "バージョン",
        homebrewDescription: "種類",
        homebrewHomepage: "サイトを開く",
        homebrewPopularity: "人気度",
        homebrewPopularityFormat: "%@ 件のインストール、%@ 日間",
        homebrewInstalledBadge: "インストール済み",
        homebrewNotInstalledBadge: "未インストール",
        homebrewConfirmInstallTitle: "Homebrew でインストールしますか？",
        homebrewConfirmInstallBodyFormat: "Homebrew が %@ をダウンロードしてインストールします。依存関係もインストールされる場合があります。",
        homebrewConfirmUninstallTitle: "Homebrew でアンインストールしますか？",
        homebrewConfirmUninstallBodyFormat: "Homebrew が %@ をアンインストールします。設定ファイルがシステムに残る場合があります。",
        homebrewTerminalFallback: "この操作では管理者パスワードを求めるために Terminal が必要です。Vorssaint はパスワードを取得しません。",
        homebrewLoading: "読み込み中…",
        homebrewSearchEmpty: "結果なし",
        homebrewOperationInstallFormat: "%@ をインストール中",
        homebrewOperationUninstallFormat: "%@ をアンインストール中",
        homebrewOperationInstalledFormat: "%@ をインストールしました。",
        homebrewOperationUninstalledFormat: "%@ をアンインストールしました。",
        homebrewOperationFailedFormat: "%@ を完了できませんでした。",
        homebrewOperationCancelled: "操作をキャンセルしました。",
        homebrewOperationPreparing: "準備中...",
        homebrewOperationDownloading: "ファイルをダウンロード中...",
        homebrewOperationInstalling: "ファイルをインストール中...",
        homebrewOperationUninstalling: "ファイルを削除中...",
        homebrewOperationFinalizing: "完了処理中...",
        homebrewOperationRefreshing: "一覧を更新中...",
        homebrewOperationTerminal: "Terminal で続行してください。",
        homebrewOperationElapsedFormat: "%@ 経過",
        homebrewOperationShowDetails: "詳細を表示",
        homebrewOperationHideDetails: "詳細を隠す",
        homebrewOperationTechnicalLog: "技術的な詳細",
        homebrewOperationProgressUnknown: "Homebrew はまだ割合を報告していません。",

        mediaName: "メディア",
        mediaEnableCaption: "動画と画像を圧縮し、GIF を作成し、テキストをローカルで抽出します。",
        mediaLocalNote: "ローカル。ネットワークなし。",
        mediaToolVideo: "動画",
        mediaToolGIF: "GIF",
        mediaToolImage: "画像",
        mediaToolText: "テキスト",
        mediaSelectFile: "ファイルを選択",
        mediaDropHint: "ここにファイルをドロップするか、クリックして選択します。",
        mediaOutput: "出力",
        mediaOutputAutomatic: "自動",
        mediaChooseOutput: "保存先",
        mediaStartVideo: "動画を圧縮",
        mediaStartGIF: "GIF を作成",
        mediaStartImage: "画像を圧縮",
        mediaStartText: "テキストを抽出",
        mediaCancel: "キャンセル",
        mediaStartTime: "開始",
        mediaEndTime: "終了",
        mediaQuality: "圧縮",
        mediaCompressionLow: "低",
        mediaCompressionMedium: "中",
        mediaCompressionHigh: "高",
        mediaMaxSize: "サイズ",
        mediaWidth: "幅",
        mediaFPS: "FPS",
        mediaKeepAudio: "音声を保持",
        mediaCodec: "コーデック",
        mediaFormat: "形式",
        mediaStripMetadata: "メタデータを削除",
        mediaLoopGIF: "GIF をループ",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "高精度",
        mediaOCRFast: "高速",
        mediaLanguageCorrection: "言語補正",
        mediaTextOutputNote: "抽出したテキストはコピーして TXT として保存できます。",
        mediaRunning: "処理中",
        mediaCompleted: "完了",
        mediaCancelled: "キャンセルしました。",
        mediaOpenInFinder: "表示",
        mediaCopyText: "テキストをコピー",
        mediaRunAgain: "もう一度実行",
        mediaEmptyText: "テキストが見つかりません。",
        mediaResultSavedFormat: "%@ として保存しました",
        mediaResultSizeFormat: "%@ から %@",
        mediaErrorNoFile: "先にファイルを選択してください。",
        mediaErrorNoVideo: "このファイルには動画トラックがありません。",
        mediaErrorSameOutput: "元のファイルとは別の保存先を選んでください。",
        mediaErrorUnsupported: "macOS が対応していない形式です。",

        shelfName: "シェルフ",
        shelfEnable: "ファイルをドラッグする一時置き場",
        shelfEnableCaption: "ファイル、画像、テキストを集めておき、あとからどこへでもドラッグできるフローティングの置き場です。",
        shelfHowTitle: "使いかた",
        shelfStep1: "ショートカットを押すか、ドラッグ中にマウスを振って開きます。",
        shelfStep2: "ファイル、画像、リンク、テキストをドロップして保持します。",
        shelfStep3: "必要なときに、各項目をどのアプリへでもドラッグして取り出します。",
        shelfShakeToggle: "ドラッグ中にマウスを振って開く",
        shelfShakeCaption: "項目を持ったままポインタをすばやく振ると、カーソルの近くに呼び出せます。",
        shelfHotkeyLabel: "ショートカット",
        shelfOpenNow: "今すぐ開く",
        shelfNoPermission: "アクセス権は不要です。",
        shelfMenuItem: "シェルフを開く",
        shelfTitle: "シェルフ",
        shelfEmpty: "ここに項目をドラッグ",
        shelfClearAll: "すべてを消去",
        shelfRemoveSelected: "選択した項目を削除",
        shelfSelectedFormat: "%d 件を選択中",
        shelfHint: "クリックで選択。外へドラッグして使用。",
        shelfItemImage: "画像",

        breakdownMeasuring: "計測中…",

        mixerSection: "音量ミキサー",
        mixerEmpty: "オーディオを使用するアプリがここに表示されます",
        mixerUnavailable: "macOS 14.4 以降で利用できます",
        mixerPermissionBody: "アプリごとの音量を調整するには、システム設定で「画面とシステムオーディオ収録」を許可してください。オーディオが記録されることはありません。",
        mixerResetTooltip: "100% にリセット",
        mixerOutputDefault: "デフォルト",
        mixerOutputCurrent: "現在",
        mixerOutputUnavailable: "出力を利用できません",
        mixerOutputFallback: "このデバイスが戻るまでデフォルトを使用します。",
        mixerOutputTooltip: "出力を選択",
        mixerSystemOutputTitle: "出力",
        mixerSystemOutputNoDevices: "出力が見つかりません",
        mixerSystemOutputTooltip: "システム出力を選択",
        mixerSystemOutputErrorFormat: "変更できませんでした: %@",
        mixerLowerOnHeadphonesDisconnect: "ヘッドフォン切断時に音量を下げる",
        mixerLowerOnHeadphonesDisconnectCaption: "有線またはBluetoothヘッドフォンが切断されたら出力を0%にします。",
        soundOutputSwitcherTitle: "出力切り替え",
        soundOutputSwitcherEnable: "ショートカットで出力を切り替える",
        soundOutputSwitcherCaption: "出力を選び、ショートカットで次に利用可能な出力へ切り替えます。",
        soundOutputSwitcherDevices: "切り替える出力",
        soundOutputSwitcherNoAvailableSelection: "利用可能な出力を1つ以上選択してください。",
        mixerInputTitle: "マイク",
        mixerInputNoDevices: "マイクが見つかりません",
        mixerInputUnavailable: "マイクを利用できません",
        mixerInputFallback: "このマイクが戻るまでデフォルトを使用します。",
        mixerInputTooltip: "マイクを選択",
        mixerInputErrorFormat: "変更できませんでした: %@",

        updatesSection: "アップデート",
        autoCheckToggle: "アップデートを自動的に確認",
        checkNowButton: "今すぐ確認",
        updateChecking: "確認中…",
        updateUpToDate: "最新バージョンを使用しています。",
        updateAvailablePrefix: "アップデートが利用できます：",
        updateInstallButton: "ダウンロードしてインストール",
        updateDownloading: "アップデートをダウンロード中…",
        updateInstalling: "インストールして再起動中…",
        updateFailedPrefix: "確認できませんでした：",
        updateLastChecked: "前回の確認：",
        updateNotifyTitle: "Vorssaint のアップデート",
        menuCheckUpdates: "アップデートを確認…",

        permissionRequired: "アクセス権が必要です",
        permissionAccessibility: "アクセシビリティ",
        permissionScreenRecording: "画面収録",
        permissionGranted: "許可済み",
        permissionMissing: "未許可",
        permissionOpenSettings: "システム設定を開く…",
        permissionRequest: "アクセスを許可",
        permissionRestartNote: "許可後、macOS がアプリの再オープンを求めることがあります。",

        aboutDescription: "あなたの Mac のためのユーティリティハブ。\n省エネルギー、システムモニタ、スクロール、ウインドウスイッチャーを、メニューバーから。",
        versionPrefix: "バージョン",
        reviewIntro: "はじめにを見直す",
        viewOnGitHub: "GitHub で見る",

        obContinue: "続ける",
        obBack: "戻る",
        obSkipStep: "このステップをスキップ",
        obStart: "Vorssaint を開く",
        obStepWelcomeTitle: "Vorssaint へようこそ",
        obStepWelcomeBody: "日々の macOS をもっと快適にする、控えめなメニューバーユーティリティです。",
        obWelcomeBullet1Title: "省エネルギーを思いどおりに",
        obWelcomeBullet1Body: "ふたを閉じたままでも、好きなだけ Mac をスリープさせずに使えます。",
        obWelcomeBullet2Title: "システムをひと目で把握",
        obWelcomeBullet2Body: "CPU・GPU・バッテリーの温度、ハードウェア使用状況、メモリプレッシャーをリアルタイムで。",
        obWelcomeBullet3Title: "マウスとウインドウを自分流に",
        obWelcomeBullet3Body: "マウスのスクロール反転と、サムネール付きのウインドウスイッチャー。",
        obLanguageLabel: "言語",
        obStepAccessibilityTitle: "アクセシビリティ",
        obStepAccessibilityBody: "マウスのスクロールを反転したり、ウインドウスイッチャーがキーボードに反応したりするために必要です。",
        obAccessibilityWhy: "アプリが監視するのはマウスホイールとスイッチャーのショートカットだけです。記録したり、どこかに送信したりすることはありません。",
        obStepRecordingTitle: "画面収録",
        obStepRecordingBody: "スイッチャーで、アイコンだけでなく実際のウインドウのサムネールを表示できるようになります。",
        obRecordingWhy: "サムネールはその場で生成され、メモリ内にとどまり、Mac の外に出ることはありません。許可しなくても、スイッチャーはアイコンで動作します。",
        obStepMonitorTitle: "システムモニタ",
        obStepMonitorBody: "パネルに CPU・GPU・バッテリーの温度、ハードウェア使用状況、メモリプレッシャーが表示されます。",
        obMonitorNoPermission: "アクセス権は不要です。センサーはシステムから直接読み取られます。",
        obStepOptionalTitle: "オプション機能",
        obStepOptionalBody: "今すぐ使いたいものをオンにしてください。すべて後から設定で変更できます。",
        obStepStatusTitle: "チェック",
        obStepStatusBody: "使いたい機能の準備がすべて整っているか確認します。",
        obStatusRecheck: "もう一度確認",
        obStepDoneTitle: "準備完了！",
        obStepDoneBody: "Vorssaint はすでにあなたの Mac を見守っています。",
        obDoneHint: "画面右上のメニューバーで、ブラックホールを探してください。",
        obWhatsNewTitle: "このバージョンの新機能",
        obWhatsNewFallback: "このアップデートには最新の修正と改善が含まれています。",
        obLanguageUpdateTitle: "あなたの言語に対応",
        obLanguageUpdateBody: "Vorssaint が複数の言語に対応しました。使いたい言語を選んでください。設定でいつでも変更できます。",

        tabMonitor: "モニタ",
        monitorMenuBarSection: "メニューバー",
        monitorMenuBarCaption: "メニューバーのアイコンの横に表示する項目を選びます。",
        monitorCombineTemperatures: "使用率と温度をまとめる",
        monitorCombineTemperaturesCaption: "同じ項目の使用率と温度が有効な場合、1つのブロックにまとめて表示します。",
        monitorSeparateMenuBarMetrics: "メトリクスを個別の項目に分ける",
        monitorSeparateMenuBarMetricsCaption: "有効なブロックをメニューバーで分け、結合がオンなら使用率と温度は一緒に表示します。",
        monitorShowCPU: "CPU",
        monitorShowMemory: "メモリ",
        monitorShowNetwork: "ネットワーク",
        monitorShowPowerLabel: "電源",
        monitorIntervalLabel: "更新間隔",
        monitorInterval1: "1秒",
        monitorInterval2: "2秒",
        monitorInterval5: "5秒",
        monitorPanelSection: "パネル",
        panelNavigationMode: "パネルをセクションごとに移動",
        panelNavigationCaption: "1つのセクションだけを表示し、ナビゲーションをパネル下部に置きます。",
        panelFooterSections: "セクション",
        panelFooterList: "リスト",
        fanControlBetaShow: "Fan Control (Beta) をパネルに表示",
        fanControlBetaSection: "Fan Control",
        fanControlBetaTitle: "Fan Control",
        fanControlBetaStatus: "自動",
        fanControlBetaCaption: "Beta. 手動制御はMacモデルごとの検証が完了するまで無効です。",
        fanControlModeAutomatic: "自動",
        fanControlModeManual: "手動",
        betaBadge: "BETA",
        betaFeatureWarning: "ベータ版です。一部の不具合が残っている場合があります。",

        networkSection: "ネットワーク",
        networkDownload: "ダウンロード",
        networkUpload: "アップロード",
        networkThisSession: "このセッション",
        networkMeasuring: "計測中…",

        diskSection: "ディスク",
        diskUsed: "使用済み",
        diskFree: "空き",
        diskInternal: "内蔵",
        diskExternal: "外部",
        diskSelect: "ディスクを選択",
        diskRead: "読み込み",
        diskWrite: "書き込み",
        diskSMARTStatus: "状態",
        diskSMARTUnavailable: "このディスクでは SMART を利用できません",
        diskTotalRead: "総読み込み",
        diskTotalWritten: "総書き込み",
        diskTemperature: "温度",
        diskHealth: "健康状態",
        diskPowerCycles: "電源投入回数",
        diskPowerOnHours: "通電時間",
        diskUnsafeShutdowns: "安全でない終了",
        diskMediaErrors: "メディアエラー",
        diskEject: "取り出す",
        diskEjectAll: "すべて取り出す",
        diskEjecting: "取り出し中…",
        diskReadyToRemove: "取り外せます",
        diskEjectFailed: "取り出せませんでした",
        diskProtectionCaption: "抜く前に取り出します。",
        diskNoExternal: "取り出せる外部ディスクはありません。",
        diskOpenInFinder: "開く",
        diskStorageSettings: "ストレージ",
        diskNoDisks: "マウント済みディスクが見つかりません。",

        powerSection: "電源",
        powerSystem: "システム",
        powerAdapter: "アダプタ",
        powerBattery: "バッテリー",
        powerCharging: "充電中",
        powerOnBattery: "バッテリー駆動",
        powerPluggedIn: "電源に接続",
        powerUnavailable: "この Mac では電源の計測値を利用できません",
        powerAdapterMaxFormat: "最大 %@",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "CPU温度",
        monitorShowGPUTemperature: "GPU温度",
        monitorShowBatteryTemperature: "バッテリー温度",
        monitorGraphsSection: "グラフ",
        monitorGraphsCaption: "経過に応じてグラフを表示する項目を選びます。",

        updateBannerTitle: "アップデートが利用できます",
        updateBannerAction: "アップデート",
        obStepMenuBarTitle: "メニューバーの計測値",
        obStepMenuBarBody: "アイコンの横に表示する項目を選びます。上のプレビューがリアルタイムで更新されます。",
        obStepMenuBarNote: "新機能：パネルのネットワークと電源のブロック、そしてグラフ。すべて後から設定 › モニタで微調整できます。",
        monitorMenuBarPresetLabel: "スタイル",
        menuBarPresetReadable: "読みやすい",
        menuBarPresetDense: "高密度",
        monitorLabelStyleLabel: "ラベル",
        menuBarLabelStyleCompact: "短縮",
        menuBarLabelStyleClassic: "標準",
        monitorMemoryStyleLabel: "メモリの表示",
        monitorMemoryPressureDot: "メモリ圧力ドット",
        memoryStyleDot: "ドット",
        memoryStylePercent: "%",
        memoryStyleBoth: "両方",

        systemUptime: "稼働時間",
        powerHealth: "バッテリーの状態",
        powerCycles: "回",
        speedTestRun: "速度テスト",
        speedTestAgain: "もう一度テスト",
        speedTestLatency: "レイテンシ",
        speedTestTesting: "テスト中…",
        speedTestFailed: "テストに失敗しました",

        monitorShowInPanel: "パネルに表示",
        panelHideItem: "パネルで非表示",
        panelShowItem: "パネルに表示",
        panelHiddenItem: "非表示",
        monitorItemUptime: "稼働時間",
        monitorItemNetSpeed: "リアルタイム速度",
        monitorItemNetTotals: "セッション合計",
        monitorItemNetTest: "速度テスト",
        monitorItemDiskUsage: "ディスク使用量",
        monitorItemDiskActivity: "ライブ活動",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "外部保護",
        monitorItemDiskTools: "ツール",
        monitorPanelConfigHint: "ブロックを開いて、表示する内容を選びます。",
        monitorOrderSection: "セクションの並び順",
        monitorOrderHint: "ドラッグしてパネルのセクションを並べ替え、目のアイコンで各セクションを表示/非表示にできます。",
        obStepPanelTitle: "パネルに表示する内容",
        obStepPanelBody: "各ブロックを開いて、アイコンをクリックしたときに表示する内容を細かく選びます。",
        obStepPanelNavigationTitle: "セクション式パネル",
        obStepPanelNavigationBody: "パネルで1つのセクションだけを表示し、下部から移動できるようになりました。この更新では試せるようにオンになっています。",

        cleaningMenuItem: "クリーニングモード",
        utilitiesSection: "ユーティリティ",
        quickControlsSection: "コントロール",
        windowMaximizeName: "ウインドウを最大化",
        windowMaximizeCaption: "緑のボタンで別のスペースを作らず最大化します。",
        windowMaximizeActiveNow: "緑のボタンで有効",
        windowMaximizeNeedsAccessibility: "動作にはアクセシビリティが必要です。",
        cleaningPanelCaption: "安全に掃除できるようキーボードをロックします。",
        cleaningOverlayTitle: "クリーニングのためキーボードをロック中",
        cleaningOverlaySubtitle: "同じキーを5回押すとロックを解除します",
        cleaningOverlayUnlock: "ロックを解除",
        cleaningOverlayMouseHint: "マウスとトラックパッドはそのまま使えます",
        cleaningNeedsAxTitle: "アクセシビリティが必要です",
        cleaningNeedsAxBody: "キーボードを安全にロックするには、Vorssaint にアクセシビリティのアクセス権が必要です。システム設定で許可して、もう一度お試しください。",

        tabSupport: "支援",
        donateHeading: "Vorssaint を支援する",
        donateMessage: "わたしの公開プロジェクトはすべて、これからもずっと完全無料です。サブスクリプションも広告もありません。それを支え続けられるのは、コミュニティの応援だけです。Vorssaint がお役に立っているなら、一杯のコーヒーが本当に力になります。",
        donateButton: "Buy me a coffee",
        donateThanks: "来てくれてありがとう。🖤",
        supportIntroTitle: "Vorssaint は100%無料でこれからも無料です",
        supportIntroMessage: "空いた時間でこのアプリを少しずつ育てています。役に立っているなら、共有したり、GitHubでスターを付けたり、コーヒーを1杯おごってくれるとうれしいです。これからも改善を続ける大きな力になります。",
        supportIntroStarButton: "スターを付ける",
        supportIntroCoffeeButton: "Buy me a coffee",
        supportIntroLaterButton: "今はしない",
        showMenuBarIcon: "メニューバーにアイコンを表示",
        showMenuBarIconCaption: "Vorssaint のアイコンが消えた場合（メニューバーに空きがなくなると macOS がアイコンを隠すことがあり、ノッチのある Mac でよく起こります）、アプリケーションまたは Spotlight から Vorssaint を開き直してください。アイコンが再作成され、それでも隠れている場合はこのウインドウが開きます。ここまでたどり着けるなら、上のボタンでも同じことができます。メニューバーのアイコンを減らすか、Vorssaint の計測値を減らすと、起こりにくくなります。",
        shortcutRecording: "新しいショートカットを押してください",
        shortcutReset: "リセット",
        shortcutInvalid: "Control、Option、Command のいずれかとキーを組み合わせてください。",
        shortcutConflictFormat: "このショートカットはすでに %@ で使われています。",
        shortcutUnavailable: "macOS がこのショートカットを拒否しました。別のものを選んでください。",
        shelfShortcutToggle: "Shelf ショートカット",
        switcherUsageHintFormat: "%@ を押したまま移動し、放すとウインドウがアクティブになります。Shift または ← で戻る、Q で選択中のアプリを終了、Esc でキャンセルします。"
    )
}
