// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// 简体中文 — translated and hand-checked, not machine output.
extension Strings {
    static let zhHans = Strings(
        statusIdleTooltip: "Vorssaint：正常睡眠",
        statusActiveUntil: "Vorssaint：唤醒至",
        statusActiveIndefinite: "Vorssaint：持续唤醒",
        menuEnableAwake: "开启保持唤醒",
        menuDisableAwake: "关闭保持唤醒",
        menuActivateFor: "启用时长…",
        menuSettings: "设置…",
        menuAbout: "关于 Vorssaint",
        menuQuit: "退出 Vorssaint",
        menuHide: "隐藏 Vorssaint",
        menuHideOthers: "隐藏其他",
        menuShowAll: "全部显示",
        menuEdit: "编辑",
        menuUndo: "撤销",
        menuRedo: "重做",
        menuCut: "剪切",
        menuCopy: "拷贝",
        menuPaste: "粘贴",
        menuSelectAll: "全选",
        menuWindow: "窗口",
        menuMinimize: "最小化",
        menuZoom: "缩放",
        menuClose: "关闭",

        minutes15: "15 分钟",
        minutes30: "30 分钟",
        hour1: "1 小时",
        hours2: "2 小时",
        hours4: "4 小时",
        hours8: "8 小时",
        indefinitely: "持续不限",
        indefinite: "不限时",

        panelAwake: "Mac 已唤醒",
        panelNormalSleep: "正常睡眠",
        panelActiveBadge: "已启用",
        panelSettings: "设置",
        panelQuit: "退出",
        panelHotkeyHint: "⌃⌥⌘K 切换",

        keepAwakeTitle: "保持唤醒",
        keepAwakeEndsIn: "剩余时间",
        keepAwakeUntilDisabled: "保持启用直到你手动关闭",
        keepAwakeNormalRules: "Mac 遵循正常的能源规则",
        durationLabel: "时长",
        clamshellTitle: "合盖后继续运行",
        clamshellOnCaption: "已完全禁用睡眠，请注意电量",
        clamshellNeedsSession: "每当“保持唤醒”启用时生效",
        clamshellReady: "已就绪，切换时无需密码",
        clamshellNeedsPassword: "启用时会要求输入管理员密码",

        systemSection: "系统",
        temperatures: "温度",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "电池",
        usageSection: "硬件占用",
        memorySection: "内存",
        memoryPressure: "压力",
        pressureNormal: "正常",
        pressureWarning: "注意",
        pressureCritical: "严重",
        monitorUnavailable: "此 Mac 上无可用传感器",

        notifySessionEndedTitle: "会话已结束",
        notifySessionEndedBody: "时间到。Mac 将恢复正常睡眠。",
        notifyBatteryTitle: "Vorssaint 已关闭",
        notifyBatteryBody: "电量过低。已恢复正常睡眠以保护电量。",

        adminPromptClamshellOn: "Vorssaint 需要你的密码才能在合盖时保持 Mac 唤醒。可在 App 的介绍中免去此提示（设置 › 关于）。",
        adminPromptClamshellOff: "Vorssaint 需要你的密码才能恢复 Mac 的正常睡眠。",
        adminPromptRecover: "Vorssaint 在 Mac 睡眠被禁用时退出了。请输入密码以恢复正常睡眠。",
        adminPromptSudoersInstall: "Vorssaint 将创建一条受限规则（仅限 pmset disablesleep），用于切换合盖模式时无需输入密码。这是唯一一次需要密码。",
        adminPromptSudoersRemove: "Vorssaint 将移除免密码的合盖规则。",

        settingsTitle: "Vorssaint 设置",
        tabGeneral: "通用",
        tabEnergy: "能源",
        tabMouse: "鼠标",
        tabSwitcher: "切换器",
        tabAdvanced: "高级",
        tabAbout: "关于",
        settingsGroupFeatures: "功能",
        advancedResetSection: "权限",
        advancedResetDescription: "移除你授予 Vorssaint 的所有权限（辅助功能、屏幕录制、完全磁盘访问权限等）、登录项以及合盖规则。适合重新开始或卸载前使用。App 仍保持安装状态。",
        advancedClearButton: "清除所有权限",
        advancedCleared: "权限已清除。",
        advancedClearConfirmTitle: "清除所有权限？",
        advancedClearConfirmBody: "依赖权限的功能将停止工作，直到你重新授予。你的设置会保留。",
        advancedUninstallSection: "卸载",
        advancedUninstallDescription: "执行以上全部操作，然后移除偏好设置并将 Vorssaint 移到废纸篓，不留任何痕迹。完成后 App 会退出。你可以随时重新安装。",
        advancedUninstallButton: "完全卸载 Vorssaint",
        advancedUninstallConfirmTitle: "卸载 Vorssaint？",
        advancedUninstallConfirmBody: "Vorssaint 将清除其权限、移除偏好设置并移到废纸篓，然后退出。此操作无法从 App 内撤销，但在你清倒废纸篓之前它仍会留在其中。",

        launchAtLogin: "登录时启动",
        languageLabel: "语言",
        menuBarSection: "菜单栏",
        showCountdown: "在图标旁显示剩余时间",
        globalHotkeySection: "全局快捷键",
        hotkeyToggle: "用 ⌃⌥⌘K 切换“保持唤醒”",
        hotkeyCaption: "在任何 App 中都有效，无需额外权限。",

        sessionSection: "会话",
        defaultDurationLabel: "默认时长",
        batteryProtectionSection: "电池保护",
        batteryDisableBelow: "电量低于以下值时关闭",
        batteryNever: "从不",
        batteryProtectionCaption: "避免被遗忘的会话耗尽 MacBook 的电量。",
        clamshellSection: "合盖",
        configuring: "配置中…",
        sudoersFailed: "无法完成。请检查密码后重试。",
        clamshellExplanation: "“合盖后继续运行”会在“保持唤醒”启用期间完全禁用睡眠，并在会话结束或 App 退出时自动恢复。建议在接通电源时使用。",

        scrollSection: "滚动",
        invertMouseScroll: "反转鼠标滚动",
        invertMouseScrollCaption: "反转鼠标滚轮的方向。",
        scrollTrackpadNote: "触控板不受影响：仍保持 macOS 的自然滚动。",
        scrollActiveNow: "正在反转鼠标滚动",

        switcherSection: "App 切换器",
        switcherEnable: "用 Vorssaint 切换器替换 ⌘Tab",
        switcherEnableCaption: "通过真实缩略图切换窗口，包括同一 App 的多个窗口之间。",
        switcherUsageHint: "按住 ⌘ 并点按 Tab 进行浏览；松开即可激活窗口。Shift 或 ← 返回；Q 退出所选 App；Esc 取消。",
        switcherNoWindows: "没有打开的窗口",
        switcherMergeTabs: "每个 App 仅显示一项",
        switcherMergeTabsCaption: "将一个 App 的所有窗口合并为切换器中的一项，而不是每个窗口一项。",

        cutPasteName: "剪切和粘贴",
        cutPasteEnable: "在访达中剪切和粘贴文件",
        cutPasteEnableCaption: "在访达中用 ⌘X 剪切、用 ⌘V 移动文件和文件夹。",
        cutPasteHowTitle: "使用方法",
        cutPasteStep1: "在访达中选择项目，按 ⌘X 将其剪切。",
        cutPasteStep2: "打开目标文件夹，按 ⌘V 将其移动到那里。",
        cutPasteTextNote: "在文本字段中（例如重命名时），⌘X 和 ⌘V 仍照常工作。",
        cutPasteActiveNow: "已可在访达中剪切",
        cutPasteAutomationNote: "首次使用时，macOS 会请求控制访达的权限。",
        cutReadyTitle: "已剪切",
        cutReadyHint: "在目标文件夹中粘贴以移动",
        cutDoneTitle: "已移动！",
        cutMovedSingular: "已移动 1 个项目",
        cutMovedPluralFormat: "已移动 %d 个项目",
        cutSomeFailed: "部分项目无法移动",

        autoQuitName: "关闭时退出",
        autoQuitEnable: "App 最后一个窗口关闭时退出该 App",
        autoQuitEnableCaption: "关闭 App 的最后一个窗口也会退出该 App。",
        autoQuitActiveNow: "已启用并正在监视窗口",
        autoQuitHowTitle: "工作原理",
        autoQuitStep1: "关闭某个 App 的最后一个窗口（⌘W 或红色按钮）。",
        autoQuitStep2: "该 App 会自行退出。“是否存储更改？”对话框仍会出现。",
        autoQuitPredictableNote: "通常无窗口运行的 App 永远不会被退出。",
        autoQuitExceptionsTitle: "例外",
        autoQuitExceptionsCaption: "此列表中的 App 即使没有窗口也会保持打开。",
        autoQuitExceptionsEmpty: "没有例外",
        autoQuitAddApp: "添加 App…",

        uninstallerName: "卸载器",
        uninstallerEnableCaption: "在移除 App 的同时，清除它遗留的缓存、偏好设置、日志和残留文件。",
        uninstallerStep1: "将一个 App 拖到设置中，或从列表中选择一个。",
        uninstallerStep2: "查看找到的文件以及它们占用的空间。",
        uninstallerStep3: "把想移除的内容移到废纸篓。不会永久删除任何内容。",
        uninstallerMenuItem: "卸载某个 App…",
        uninstallerDropTitle: "将 App 拖到这里",
        uninstallerDropSubtitle: "或选择一个进行扫描",
        uninstallerChoose: "选择 App…",
        uninstallerEmptyNote: "未经你确认，不会移除任何内容。",
        uninstallerFDANote: "授予完全磁盘访问权限可进行更彻底的扫描。",
        uninstallerFDAGrant: "授予访问权限…",
        uninstallerFDAHint: "在列表中开启 Vorssaint。如果列表中没有，点按 + 并从“应用程序”中选择 Vorssaint。访问权限须在你重新打开 App 后才会生效。",
        uninstallerFDARelaunch: "立即重新打开",
        uninstallerScanning: "正在扫描文件…",
        uninstallerRemoving: "正在移到废纸篓…",
        uninstallerFoundTitle: "已找到",
        uninstallerSelectedFormat: "已选择 %d 项，共 %d 项",
        uninstallerRemove: "移到废纸篓",
        uninstallerCancel: "取消",
        uninstallerDoneTitle: "完成！",
        uninstallerFreedFormat: "已释放 %@",
        uninstallerSomeFailed: "部分项目无法移到废纸篓。",
        uninstallerAnother: "卸载另一个",
        uninstallerCatApp: "应用程序",
        uninstallerCatSupport: "支持文件",
        uninstallerCatCaches: "缓存",
        uninstallerCatPreferences: "偏好设置",
        uninstallerCatContainers: "容器",
        uninstallerCatLogs: "日志",
        uninstallerCatState: "已存储状态",
        uninstallerCatOther: "其他",

        shelfName: "暂存架",
        shelfEnable: "用于拖放文件的临时区域",
        shelfEnableCaption: "一个浮动空间，用来收集文件、图像和文本，稍后再拖到任何 App 中。",
        shelfHowTitle: "使用方法",
        shelfStep1: "用 ⌃⌥⌘D 打开它，或在拖动时晃动鼠标打开。",
        shelfStep2: "把文件、图像、链接或文本拖放到上面以暂存。",
        shelfStep3: "需要时再把每个项目拖回任何 App。",
        shelfShakeToggle: "拖动时晃动鼠标打开",
        shelfShakeCaption: "按住某个项目时快速晃动指针，即可在光标附近呼出暂存架。",
        shelfHotkeyLabel: "快捷键",
        shelfOpenNow: "立即打开",
        shelfNoPermission: "无需任何权限。",
        shelfMenuItem: "打开暂存架",
        shelfTitle: "暂存架",
        shelfEmpty: "将项目拖到这里",
        shelfClearAll: "全部清除",
        shelfRemoveSelected: "移除所选",
        shelfSelectedFormat: "已选择 %d 项",
        shelfHint: "点按以选择，拖出即可使用。",
        shelfItemImage: "图像",

        breakdownMeasuring: "测量中…",

        mixerSection: "音量混音器",
        mixerEmpty: "使用音频的 App 会显示在这里",
        mixerUnavailable: "需 macOS 14.4 及更高版本",
        mixerPermissionBody: "若要调整各 App 的音量，请在“系统设置”中允许“屏幕与系统音频录制”。绝不会录制音频。",
        mixerResetTooltip: "重置为 100%",

        updatesSection: "更新",
        autoCheckToggle: "自动检查更新",
        checkNowButton: "立即检查",
        updateChecking: "检查中…",
        updateUpToDate: "你已是最新版本。",
        updateAvailablePrefix: "有可用更新：",
        updateInstallButton: "下载并安装",
        updateDownloading: "正在下载更新…",
        updateInstalling: "正在安装并重新启动…",
        updateFailedPrefix: "无法检查：",
        updateLastChecked: "上次检查：",
        updateNotifyTitle: "Vorssaint 更新",
        menuCheckUpdates: "检查更新…",

        permissionRequired: "需要权限",
        permissionAccessibility: "辅助功能",
        permissionScreenRecording: "屏幕录制",
        permissionGranted: "已授予",
        permissionMissing: "未授予",
        permissionOpenSettings: "打开系统设置…",
        permissionRequest: "请求权限",
        permissionRestartNote: "授予后，macOS 可能会要求重新打开 App。",

        aboutDescription: "你的 Mac 实用工具中心。\n能源、系统监视、滚动和窗口切换器，尽在菜单栏中。",
        versionPrefix: "版本",
        reviewIntro: "重看介绍",
        viewOnGitHub: "在 GitHub 上查看",

        obContinue: "继续",
        obBack: "返回",
        obSkipStep: "跳过此步骤",
        obStart: "打开 Vorssaint",
        obStepWelcomeTitle: "欢迎使用 Vorssaint",
        obStepWelcomeBody: "一款低调的菜单栏实用工具，让日常使用 macOS 更顺手。",
        obWelcomeBullet1Title: "掌控能源",
        obWelcomeBullet1Body: "让 Mac 想唤醒多久就唤醒多久，合盖也不例外。",
        obWelcomeBullet2Title: "清晰掌握系统状态",
        obWelcomeBullet2Body: "实时查看 CPU、GPU 和电池温度、硬件占用以及内存压力。",
        obWelcomeBullet3Title: "鼠标和窗口，随你所愿",
        obWelcomeBullet3Body: "反转鼠标滚动，以及带缩略图的窗口切换器。",
        obLanguageLabel: "语言",
        obStepAccessibilityTitle: "辅助功能",
        obStepAccessibilityBody: "用于反转鼠标滚动，并让窗口切换器响应键盘操作。",
        obAccessibilityWhy: "App 只会监视鼠标滚轮和切换器快捷键。不会录制任何内容，也不会发送到任何地方。",
        obStepRecordingTitle: "屏幕录制",
        obStepRecordingBody: "让切换器显示真实的窗口缩略图，而不仅是图标。",
        obRecordingWhy: "缩略图实时生成，仅保留在内存中，绝不会离开你的 Mac。即使没有它，切换器仍可用图标工作。",
        obStepMonitorTitle: "系统监视",
        obStepMonitorBody: "面板会显示 CPU、GPU 和电池温度、硬件占用以及内存压力。",
        obMonitorNoPermission: "无需任何权限。传感器直接从系统读取。",
        obStepOptionalTitle: "可选功能",
        obStepOptionalBody: "现在开启你想用的功能。一切都可以稍后在设置中更改。",
        obPasswordlessToggle: "合盖时无需密码提示",
        obPasswordlessCaption: "创建一条仅限于“pmset disablesleep”的系统规则。管理员密码只需现在输入一次。",
        obStepStatusTitle: "检查",
        obStepStatusBody: "确认你想使用的功能都已就绪。",
        obStatusRecheck: "重新检查",
        obStepDoneTitle: "全部就绪！",
        obStepDoneBody: "Vorssaint 已开始照看你的 Mac。",
        obDoneHint: "在菜单栏（屏幕右上角）寻找那个黑洞图标。",
        obWhatsNewTitle: "此版本的新功能",
        obLanguageUpdateTitle: "现在支持你的语言",
        obLanguageUpdateBody: "Vorssaint 现在支持多种语言。选择你想使用的语言，随时可在设置中更改。",

        tabMonitor: "监视",
        monitorMenuBarSection: "在菜单栏中",
        monitorMenuBarCaption: "选择菜单栏中图标旁显示的内容。",
        monitorShowCPU: "CPU",
        monitorShowMemory: "内存",
        monitorShowNetwork: "网络",
        monitorShowPowerLabel: "电源",
        monitorIntervalLabel: "更新间隔",
        monitorInterval1: "1 秒",
        monitorInterval2: "2 秒",
        monitorInterval5: "5 秒",
        monitorPanelSection: "在面板中",

        networkSection: "网络",
        networkDownload: "下载",
        networkUpload: "上传",
        networkThisSession: "本次会话",
        networkMeasuring: "测量中…",

        powerSection: "电源",
        powerSystem: "系统",
        powerAdapter: "电源适配器",
        powerBattery: "电池",
        powerCharging: "充电中",
        powerOnBattery: "使用电池",
        powerPluggedIn: "已接通电源",
        powerUnavailable: "此 Mac 上无可用电源指标",
        powerAdapterMaxFormat: "最高 %@",
        monitorShowGPU: "GPU",
        monitorGraphsSection: "图表",
        monitorGraphsCaption: "选择哪些指标显示随时间变化的图表。",

        updateBannerTitle: "有可用更新",
        updateBannerAction: "更新",
        obStepMenuBarTitle: "菜单栏中的指标",
        obStepMenuBarBody: "选择图标旁要显示的内容。上方预览会实时更新。",
        obStepMenuBarNote: "新增：面板中的网络和电源模块及图表。稍后可在设置 › 监视中细致调整。",
        monitorMemoryStyleLabel: "内存显示方式",
        memoryStyleDot: "圆点",
        memoryStylePercent: "%",
        memoryStyleBoth: "两者",

        systemUptime: "已运行",
        powerHealth: "电池健康度",
        powerCycles: "次循环",
        speedTestRun: "测速",
        speedTestAgain: "再次测速",
        speedTestLatency: "延迟",
        speedTestTesting: "测试中…",
        speedTestFailed: "测试失败",

        monitorShowInPanel: "在面板中显示",
        monitorItemUptime: "运行时间",
        monitorItemNetSpeed: "实时速度",
        monitorItemNetTotals: "会话总量",
        monitorItemNetTest: "测速",
        monitorPanelConfigHint: "打开某个模块以选择它显示的内容。",
        monitorOrderSection: "分区顺序",
        monitorOrderHint: "拖动以重新排列面板分区。点按面板中各分区的折叠箭头可将其收起。",
        obStepPanelTitle: "面板中显示的内容",
        obStepPanelBody: "打开每个模块，精确选择点按图标时显示的内容。",

        cleaningMenuItem: "清洁模式",
        cleaningOverlayTitle: "键盘已锁定以便清洁",
        cleaningOverlaySubtitle: "连按同一个键 5 次以解锁",
        cleaningOverlayUnlock: "解锁",
        cleaningOverlayMouseHint: "你的鼠标和触控板仍可使用",
        cleaningNeedsAxTitle: "需要辅助功能",
        cleaningNeedsAxBody: "为安全地锁定键盘，Vorssaint 需要辅助功能权限。请在“系统设置”中授予后重试。",

        tabSupport: "支持",
        donateHeading: "支持 Vorssaint",
        donateMessage: "我的每一个公开项目现在是、将来也永远会完全免费：没有订阅，没有广告。社区的支持是它得以延续的唯一动力。如果 Vorssaint 帮到了你，一杯咖啡真的会带来不同。",
        donateButton: "Buy me a coffee",
        donateThanks: "谢谢你的到来。🖤",
        obStepDonateTitle: "喜欢 Vorssaint 吗？🖤",
        showMenuBarIcon: "显示菜单栏图标",
        showMenuBarIconCaption: "如果 Vorssaint 的图标消失了（当菜单栏空间不足时，macOS 可能会隐藏图标，这在带刘海的 Mac 上很常见），请从“应用程序”或 Spotlight 重新打开 Vorssaint：这会重建图标，如果它仍被隐藏，则会打开此窗口。当你已经能进入这里时，上方按钮的作用相同。让菜单栏中的图标更少，或 Vorssaint 的指标更少，会大大降低这种情况发生的几率。"
    )
}
