// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// Italiano — translated and hand-checked, not machine output.
extension Strings {
    static let it = Strings(
        statusIdleTooltip: "Vorssaint: stop normale",
        statusActiveUntil: "Vorssaint: attivo fino alle",
        statusActiveIndefinite: "Vorssaint: attivo a tempo indeterminato",
        menuEnableAwake: "Attiva mantieni attivo",
        menuDisableAwake: "Disattiva mantieni attivo",
        menuActivateFor: "Attiva per…",
        menuSettings: "Impostazioni…",
        menuAbout: "Informazioni su Vorssaint",
        menuQuit: "Esci da Vorssaint",
        menuHide: "Nascondi Vorssaint",
        menuHideOthers: "Nascondi gli altri",
        menuShowAll: "Mostra tutto",
        menuEdit: "Modifica",
        menuUndo: "Annulla",
        menuRedo: "Ripristina",
        menuCut: "Taglia",
        menuCopy: "Copia",
        menuPaste: "Incolla",
        menuSelectAll: "Seleziona tutto",
        menuWindow: "Finestra",
        menuMinimize: "Riduci",
        menuZoom: "Zoom",
        menuClose: "Chiudi",

        minutes15: "15 minuti",
        minutes30: "30 minuti",
        hour1: "1 ora",
        hours2: "2 ore",
        hours4: "4 ore",
        hours8: "8 ore",
        indefinitely: "A tempo indeterminato",
        indefinite: "Indeterminato",

        panelAwake: "Mac attivo",
        panelNormalSleep: "Stop normale",
        panelSettings: "Impostazioni",
        panelQuit: "Esci",
        panelHotkeyHint: "La scorciatoia attiva/disattiva",

        keepAwakeTitle: "Mantieni attivo",
        keepAwakeEndsIn: "Termina tra",
        keepAwakeUntilDisabled: "Attivo finché non lo disattivi",
        keepAwakeNormalRules: "Il Mac segue le normali regole di risparmio energia",
        keepAwakeOptions: "Opzioni",
        keepAwakeMouseJiggle: "Muovi leggermente il puntatore",
        keepAwakeMouseJiggleCaption: "Durante una sessione, muove un po' il puntatore all'intervallo scelto.",
        keepAwakeMouseJiggleInterval: "Intervallo",
        keepAwakeIconTintLabel: "Colore icona attiva",
        keepAwakeIconTintOrange: "Arancione",
        keepAwakeIconTintGreen: "Verde",
        keepAwakeIconTintBlue: "Blu",
        keepAwakeIconTintPurple: "Viola",
        keepAwakeIconTintPink: "Rosa",
        keepAwakeIconTintNone: "Nessun colore",
        durationLabel: "Durata",
        clamshellTitle: "Continua con il coperchio chiuso",
        clamshellOnCaption: "Stop completamente disattivato. Attenzione alla carica",
        clamshellNeedsSession: "Si applica ogni volta che «Mantieni attivo» è attivo",
        clamshellReady: "Pronto. Si attiva e disattiva senza password",
        clamshellNeedsPassword: "Richiede la password di amministratore una volta",

        systemSection: "Sistema",
        temperatures: "Temperature",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "Batteria",
        usageSection: "Utilizzo hardware",
        memorySection: "Memoria",
        memoryPressure: "Pressione",
        pressureNormal: "Normale",
        pressureWarning: "Attenzione",
        pressureCritical: "Critica",
        monitorUnavailable: "Sensori non disponibili su questo Mac",
        energyAppsTitle: "Consumo energia rilevante",
        energyAppsIdle: "Nessun consumo energia rilevante",

        notifySessionEndedTitle: "Sessione terminata",
        notifySessionEndedBody: "Il tempo è scaduto. Il Mac tornerà allo stop normale.",
        notifyBatteryTitle: "Vorssaint disattivato",
        notifyBatteryBody: "Batteria scarica. Lo stop normale è stato ripristinato per preservare la carica.",
        adminPromptClamshellOn: "Vorssaint ha bisogno della password per continuare con il coperchio chiuso.",
        adminPromptClamshellOff: "Vorssaint ha bisogno della password per ripristinare lo stop normale del Mac.",
        adminPromptRecover: "Vorssaint è stato chiuso mentre lo stop del Mac era disattivato. Inserisci la password per ripristinare lo stop normale.",
        adminPromptSudoersInstall: "Vorssaint creerà una regola limitata (solo pmset disablesleep) per attivare la modalità a coperchio chiuso senza chiedere la password. È l'unica volta che la password è necessaria.",
        adminPromptSudoersRemove: "Vorssaint rimuoverà la regola del coperchio chiuso senza password.",

        settingsTitle: "Impostazioni di Vorssaint",
        tabGeneral: "Generali",
        tabEnergy: "Energia",
        tabMouse: "Mouse",
        tabSwitcher: "Commutatore",
        tabAdvanced: "Avanzate",
        tabAbout: "Informazioni",
        tabReleaseNotes: "Novità",
        releaseNotesOnUpdateToggle: "Mostra le novità dopo l'aggiornamento",
        whatsNewDontShowAgain: "Non mostrare più",
        previewSizeLabel: "Dimensione anteprime",
        previewSizeNormal: "Normale",
        previewSizeLarge: "Grande",
        previewSizeXLarge: "Molto grande",
        settingsGroupFeatures: "Funzioni",
        advancedResetSection: "Autorizzazioni",
        advancedResetDescription: "Rimuove tutte le autorizzazioni concesse a Vorssaint (Accessibilità, Registrazione schermo, Accesso completo al disco e altre), l'elemento di login e la regola del coperchio chiuso. Utile per ripartire da zero o prima di disinstallare. L'app resta installata.",
        advancedClearButton: "Cancella tutte le autorizzazioni",
        advancedCleared: "Autorizzazioni cancellate.",
        advancedClearConfirmTitle: "Cancellare tutte le autorizzazioni?",
        advancedClearConfirmBody: "Le funzioni che richiedono autorizzazioni smetteranno di funzionare finché non le concederai di nuovo. Le tue impostazioni vengono mantenute.",
        advancedUninstallSection: "Disinstalla",
        advancedUninstallDescription: "Fa tutto quanto sopra, poi rimuove le preferenze e sposta Vorssaint nel Cestino, senza lasciare tracce. L'app si chiude al termine. Puoi reinstallarla quando vuoi.",
        advancedUninstallButton: "Disinstalla completamente Vorssaint",
        advancedUninstallConfirmTitle: "Disinstallare Vorssaint?",
        advancedUninstallConfirmBody: "Vorssaint cancellerà le autorizzazioni, rimuoverà le preferenze e si sposterà nel Cestino, poi si chiuderà. Questa azione non può essere annullata dall'app, ma resta nel Cestino finché non lo svuoti.",

        launchAtLogin: "Apri al login",
        languageLabel: "Lingua",
        menuBarSection: "Barra dei menu",
        showCountdown: "Mostra il tempo rimanente accanto all'icona",
        globalHotkeySection: "Scorciatoia globale",
        hotkeyToggle: "Abilita scorciatoia per «Mantieni attivo»",
        hotkeyCaption: "Funziona in qualsiasi app, senza autorizzazioni aggiuntive.",

        sessionSection: "Sessione",
        defaultDurationLabel: "Durata predefinita",
        keepAwakeAutoStart: "Attiva all'apertura dell'app",
        keepAwakeAutoStartCaption: "Avvia «Mantieni attivo» automaticamente.",
        batteryProtectionSection: "Protezione della batteria",
        batteryDisableBelow: "Disattiva quando la batteria scende sotto",
        batteryNever: "Mai",
        batteryProtectionCaption: "Evita che una sessione dimenticata scarichi la batteria del MacBook.",
        clamshellSection: "Coperchio chiuso",
        configuring: "Configurazione…",
        sudoersFailed: "Impossibile attivare il coperchio chiuso. Riprova.",
        clamshellExplanation: "«Continua con il coperchio chiuso» disattiva completamente lo stop mentre «Mantieni attivo» è attivo e viene ripristinato automaticamente al termine della sessione o alla chiusura dell'app. È preferibile usarlo collegato all'alimentazione.",

        scrollSection: "Scorrimento",
        invertMouseScroll: "Inverti lo scorrimento del mouse",
        invertMouseScrollCaption: "Inverte la direzione della rotellina del mouse.",
        scrollTrackpadNote: "Il trackpad resta invariato: mantiene lo scorrimento naturale di macOS.",
        scrollActiveNow: "Scorrimento del mouse invertito ora",

        switcherSection: "Commutatore app",
        switcherEnable: "Usa il commutatore di Vorssaint",
        switcherEnableCaption: "Passa da una finestra all'altra con miniature reali, anche tra più finestre della stessa app.",
        switcherUsageHint: "Tieni premuta la scorciatoia per spostarti; rilascia per attivare la finestra. Maiuscole o ← torna indietro; Q chiude l'app selezionata; Esc annulla.",
        switcherNoWindows: "Nessuna finestra aperta",
        switcherMergeTabs: "Mostra una voce per app",
        switcherMergeTabsCaption: "Raggruppa tutte le finestre di un'app in un'unica voce nel commutatore, anziché una per finestra.",
        switcherShowFinder: "Mostra Finder senza finestre",
        switcherShowFinderCaption: "Mostra Finder nel commutatore anche quando non ci sono finestre del Finder aperte.",
        dockPreviewName: "Dock Preview",
        dockPreviewEnable: "Anteprima finestre dal Dock",
        dockPreviewEnableCaption: "Passa il mouse su un'app aperta nel Dock per vedere e mostrare al volo le sue finestre.",
        dockPreviewActiveNow: "Attivo nel Dock",
        dockPreviewMagnificationBlocked: "Disattiva l'ingrandimento del Dock per usarlo.",
        dockPreviewDockUnavailable: "Impossibile leggere gli elementi del Dock.",
        dockPreviewAutohideBeta: "Beta. Potresti riscontrare alcuni bug.",
        dockPreviewCloseWindow: "Chiudi finestra",
        dockPreviewIntroPeek: "Passa il mouse su una miniatura per dare un'occhiata. Clicca per aprire la finestra.",
        dockPreviewIntroSettingsHint: "Puoi cambiarlo più tardi in Impostazioni › Switcher.",
        dockPreviewIntroLater: "Non ora",
        dockPreviewIntroEnable: "Attiva Dock Preview",
        dockPreviewIntroMagnificationAction: "Disattiva l'ingrandimento del Dock per attivarlo.",

        cutPasteName: "Taglia e incolla",
        cutPasteEnable: "Taglia e incolla i file nel Finder",
        cutPasteEnableCaption: "Usa ⌘X per tagliare e ⌘V per spostare file e cartelle nel Finder.",
        cutPasteHowTitle: "Come si usa",
        cutPasteStep1: "Seleziona elementi nel Finder e premi ⌘X per tagliarli.",
        cutPasteStep2: "Apri la cartella di destinazione e premi ⌘V per spostarli lì.",
        cutPasteTextNote: "Nei campi di testo (ad esempio quando rinomini), ⌘X e ⌘V continuano a funzionare normalmente.",
        cutPasteActiveNow: "Pronto a tagliare nel Finder",
        cutPasteAutomationNote: "La prima volta, macOS chiede l'autorizzazione a controllare il Finder.",
        cutReadyTitle: "Tagliato",
        cutReadyHint: "nella cartella di destinazione per spostare",
        cutCancel: "Annulla taglio",
        cutDoneTitle: "Spostato!",
        cutMovedSingular: "1 elemento spostato",
        cutMovedPluralFormat: "%d elementi spostati",
        cutSomeFailed: "Impossibile spostare alcuni elementi",

        autoQuitName: "Esci alla chiusura",
        autoQuitEnable: "Esci da un'app quando si chiude la sua ultima finestra",
        autoQuitEnableCaption: "Chiudere l'ultima finestra di un'app la fa anche uscire.",
        autoQuitActiveNow: "Attivo, monitoraggio delle finestre in corso",
        autoQuitHowTitle: "Come funziona",
        autoQuitStep1: "Chiudi l'ultima finestra di un'app (⌘W o il pulsante rosso).",
        autoQuitStep2: "L'app esce da sola. I dialoghi «Salvare le modifiche?» continuano ad apparire.",
        autoQuitPredictableNote: "Le app che di norma funzionano senza finestre non vengono mai chiuse.",
        autoQuitExceptionsTitle: "Eccezioni",
        autoQuitExceptionsCaption: "Le app in questo elenco restano aperte anche senza finestre.",
        autoQuitExceptionsEmpty: "Nessuna eccezione",
        autoQuitAddApp: "Aggiungi app…",

        uninstallerName: "Disinstallatore",
        uninstallerEnableCaption: "Rimuove un'app insieme a cache, preferenze, log e residui che lascia in giro.",
        uninstallerStep1: "Trascina un'app nelle Impostazioni oppure scegline una dall'elenco.",
        uninstallerStep2: "Controlla i file trovati e quanto spazio occupano.",
        uninstallerStep3: "Sposta ciò che vuoi nel Cestino. Nulla viene eliminato in modo definitivo.",
        uninstallerMenuItem: "Disinstalla un'app…",
        uninstallerDropTitle: "Trascina qui un'app",
        uninstallerDropSubtitle: "oppure scegline una da analizzare",
        uninstallerChoose: "Scegli app…",
        uninstallerPickerTitle: "Scegli app",
        uninstallerPickerSearch: "Cerca app",
        uninstallerPickerEmpty: "Nessuna app trovata",
        uninstallerEmptyNote: "Nulla viene rimosso senza la tua conferma.",
        uninstallerFDANote: "Concedi l'Accesso completo al disco per un'analisi più approfondita.",
        uninstallerFDAGrant: "Concedi accesso…",
        uninstallerFDAHint: "Attiva Vorssaint nell'elenco. Se non c'è, fai clic su + e scegli Vorssaint da Applicazioni. L'accesso ha effetto solo dopo aver riaperto l'app.",
        uninstallerFDARelaunch: "Riavvia ora",
        uninstallerScanning: "Analisi dei file…",
        uninstallerRemoving: "Spostamento nel Cestino…",
        uninstallerFoundTitle: "trovati",
        uninstallerSelectedFormat: "%d di %d selezionati",
        uninstallerRemove: "Sposta nel Cestino",
        uninstallerCancel: "Annulla",
        uninstallerDoneTitle: "Fatto!",
        uninstallerFreedFormat: "%@ recuperati",
        uninstallerSomeFailed: "Impossibile spostare alcuni elementi nel Cestino.",
        uninstallerAnother: "Disinstalla un'altra",
        uninstallerCatApp: "Applicazione",
        uninstallerCatSupport: "Supporto",
        uninstallerCatCaches: "Cache",
        uninstallerCatPreferences: "Preferenze",
        uninstallerCatContainers: "Container",
        uninstallerCatLogs: "Log",
        uninstallerCatState: "Stato salvato",
        uninstallerCatOther: "Altro",

        urlCleanerName: "Pulisci URL",
        urlCleanerEnable: "Pulisci URL copiati",
        urlCleanerEnableCaption: "Rimuove i parametri di tracciamento dai link copiati.",
        urlCleanerActiveNow: "Attivo e osserva gli appunti",
        urlCleanerManualTitle: "Pulisci ora",
        urlCleanerInputPlaceholder: "Incolla un URL",
        urlCleanerOutputPlaceholder: "L'URL pulito appare qui",
        urlCleanerCleanButton: "Pulisci",
        urlCleanerPasteButton: "Incolla",
        urlCleanerCopyButton: "Copia",
        urlCleanerClearButton: "Svuota campo",
        urlCleanerNoURL: "Incolla un URL valido.",
        urlCleanerNoChange: "Niente da pulire.",
        urlCleanerCleaned: "URL pulito.",
        urlCleanerCopied: "Copiato.",
        urlCleanerLocalNote: "Locale. Senza rete.",

        homebrewName: "Homebrew",
        homebrewEnableCaption: "Cerca, installa e rimuovi formule e cask.",
        homebrewMissingTitle: "Homebrew non trovato",
        homebrewMissingBody: "Vorssaint può aprire Terminale con l'installer ufficiale di Homebrew. Terminale mostra i passaggi e chiede la password se serve.",
        homebrewInstallHomebrew: "Installa Homebrew",
        homebrewInstallHomebrewCaption: "Quando Terminale ha finito, torna qui e fai clic su Aggiorna.",
        homebrewInstallHomebrewOpened: "Installer aperto in Terminale.",
        homebrewShellSetupTitle: "Completa configurazione Terminale",
        homebrewShellSetupBody: "Homebrew è installato, ma Terminale potrebbe non trovare ancora il comando brew. Vorssaint può aprire Terminale con il comando di configurazione.",
        homebrewShellSetupButton: "Configura Terminale",
        homebrewShellSetupOpened: "Comando aperto in Terminale. Poi torna qui e fai clic su Aggiorna.",
        homebrewRefresh: "Aggiorna",
        homebrewSearchPlaceholder: "Cerca pacchetti",
        homebrewKeyboardHint: "Spazio o Invio chiude il pannello macOS. Usa il pulsante di ricerca.",
        homebrewSearchButton: "Cerca",
        homebrewSearchResults: "Risultati",
        homebrewInstalled: "Installati",
        homebrewAll: "Tutti",
        homebrewFormulas: "Formule",
        homebrewCasks: "Cask",
        homebrewNoPackages: "Nessun pacchetto trovato",
        homebrewNoSelection: "Seleziona un pacchetto installato o cercane uno nuovo.",
        homebrewDetailsTitle: "Dettagli pacchetto",
        homebrewInstall: "Installa",
        homebrewUninstall: "Disinstalla",
        homebrewOpenTerminal: "Apri Terminale",
        homebrewCancelOperation: "Annulla",
        homebrewClearLog: "Svuota registro",
        homebrewLogTitle: "Registro",
        homebrewVersion: "Versione",
        homebrewDescription: "Tipo",
        homebrewHomepage: "Apri sito",
        homebrewPopularity: "Popolarità",
        homebrewPopularityFormat: "%@ installazioni in %@ giorni",
        homebrewInstalledBadge: "Installato",
        homebrewNotInstalledBadge: "Non installato",
        homebrewConfirmInstallTitle: "Installare con Homebrew?",
        homebrewConfirmInstallBodyFormat: "Homebrew scaricherà e installerà %@. Potrebbero essere installate anche dipendenze.",
        homebrewConfirmUninstallTitle: "Disinstallare con Homebrew?",
        homebrewConfirmUninstallBodyFormat: "Homebrew disinstallerà %@. I file di configurazione possono restare nel sistema.",
        homebrewTerminalFallback: "Questa operazione richiede Terminale per chiedere la password di amministratore. Vorssaint non acquisisce password.",
        homebrewLoading: "Caricamento…",
        homebrewSearchEmpty: "Nessun risultato",
        homebrewOperationInstallFormat: "Installazione di %@",
        homebrewOperationUninstallFormat: "Disinstallazione di %@",
        homebrewOperationInstalledFormat: "%@ installato.",
        homebrewOperationUninstalledFormat: "%@ disinstallato.",
        homebrewOperationFailedFormat: "Impossibile completare %@.",
        homebrewOperationCancelled: "Operazione annullata.",
        homebrewOperationPreparing: "Preparazione...",
        homebrewOperationDownloading: "Download dei file...",
        homebrewOperationInstalling: "Installazione dei file...",
        homebrewOperationUninstalling: "Rimozione dei file...",
        homebrewOperationFinalizing: "Completamento...",
        homebrewOperationRefreshing: "Aggiornamento lista...",
        homebrewOperationTerminal: "Continua nel Terminale.",
        homebrewOperationElapsedFormat: "%@ trascorsi",
        homebrewOperationShowDetails: "Mostra dettagli",
        homebrewOperationHideDetails: "Nascondi dettagli",
        homebrewOperationTechnicalLog: "Dettagli tecnici",
        homebrewOperationProgressUnknown: "Homebrew non ha ancora indicato una percentuale.",

        mediaName: "Media",
        mediaEnableCaption: "Comprimi video e immagini, crea GIF ed estrai testo localmente.",
        mediaLocalNote: "Locale. Nessuna rete.",
        mediaToolVideo: "Video",
        mediaToolGIF: "GIF",
        mediaToolImage: "Immagine",
        mediaToolText: "Testo",
        mediaSelectFile: "Scegli file",
        mediaDropHint: "Trascina un file qui o fai clic per scegliere.",
        mediaOutput: "Uscita",
        mediaOutputAutomatic: "Automatica",
        mediaChooseOutput: "Destinazione",
        mediaStartVideo: "Comprimi video",
        mediaStartGIF: "Crea GIF",
        mediaStartImage: "Comprimi immagine",
        mediaStartText: "Estrai testo",
        mediaCancel: "Annulla",
        mediaStartTime: "Inizio",
        mediaEndTime: "Fine",
        mediaQuality: "Compressione",
        mediaCompressionLow: "Bassa",
        mediaCompressionMedium: "Media",
        mediaCompressionHigh: "Alta",
        mediaMaxSize: "Dimensione",
        mediaWidth: "Larghezza",
        mediaFPS: "FPS",
        mediaKeepAudio: "Mantieni audio",
        mediaCodec: "Codec",
        mediaFormat: "Formato",
        mediaStripMetadata: "Rimuovi metadati",
        mediaLoopGIF: "Ripeti GIF",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "Accurato",
        mediaOCRFast: "Rapido",
        mediaLanguageCorrection: "Correzione lingua",
        mediaTextOutputNote: "Il testo estratto può essere copiato e salvato come TXT.",
        mediaRunning: "Elaborazione",
        mediaCompleted: "Completato",
        mediaCancelled: "Annullato.",
        mediaOpenInFinder: "Mostra",
        mediaCopyText: "Copia testo",
        mediaRunAgain: "Esegui di nuovo",
        mediaEmptyText: "Nessun testo trovato.",
        mediaResultSavedFormat: "Salvato come %@",
        mediaResultSizeFormat: "%@ in %@",
        mediaErrorNoFile: "Scegli prima un file.",
        mediaErrorNoVideo: "Questo file non contiene una traccia video.",
        mediaErrorSameOutput: "Scegli una destinazione diversa dal file originale.",
        mediaErrorUnsupported: "Formato non supportato da macOS.",

        shelfName: "Ripiano",
        shelfEnable: "Area temporanea per trascinare i file",
        shelfEnableCaption: "Uno spazio fluttuante per raccogliere file, immagini e testo, da trascinare poi ovunque.",
        shelfHowTitle: "Come si usa",
        shelfStep1: "Aprilo con la scorciatoia oppure scuotendo il mouse durante un trascinamento.",
        shelfStep2: "Rilascia su di esso file, immagini, link o testo per conservarli.",
        shelfStep3: "Trascina di nuovo fuori ogni elemento verso qualsiasi app quando ti serve.",
        shelfShakeToggle: "Apri scuotendo il mouse durante il trascinamento",
        shelfShakeCaption: "Scuoti rapidamente il puntatore mentre tieni un elemento per richiamarlo vicino al cursore.",
        shelfHotkeyLabel: "Scorciatoia",
        shelfOpenNow: "Apri ora",
        shelfNoPermission: "Non richiede alcuna autorizzazione.",
        shelfMenuItem: "Apri ripiano",
        shelfTitle: "Ripiano",
        shelfEmpty: "Trascina qui gli elementi",
        shelfClearAll: "Cancella tutto",
        shelfRemoveSelected: "Rimuovi selezionati",
        shelfSelectedFormat: "%d selezionati",
        shelfHint: "Fai clic per selezionare. Trascina fuori per usare.",
        shelfItemImage: "Immagine",

        breakdownMeasuring: "Misurazione…",

        mixerSection: "Mixer del volume",
        mixerEmpty: "Le app che usano l'audio compaiono qui",
        mixerUnavailable: "Disponibile su macOS 14.4 e successivi",
        mixerPermissionBody: "Per regolare il volume per ogni app, consenti «Registrazione schermo e audio di sistema» in Impostazioni di Sistema. L'audio non viene mai registrato.",
        mixerResetTooltip: "Ripristina al 100%",
        mixerOutputDefault: "Predefinita",
        mixerOutputCurrent: "attuale",
        mixerOutputUnavailable: "Uscita non disponibile",
        mixerOutputFallback: "Uso l'uscita predefinita finché questo dispositivo non torna.",
        mixerOutputTooltip: "Scegli uscita",
        mixerSystemOutputTitle: "Uscita",
        mixerSystemOutputNoDevices: "Nessuna uscita trovata",
        mixerSystemOutputTooltip: "Scegli uscita di sistema",
        mixerSystemOutputErrorFormat: "Impossibile cambiare: %@",
        mixerLowerOnHeadphonesDisconnect: "Abbassa il volume quando le cuffie si scollegano",
        mixerLowerOnHeadphonesDisconnectCaption: "Porta l'uscita a 0% quando cuffie cablate o Bluetooth si scollegano.",
        soundOutputSwitcherTitle: "Selettore uscita",
        soundOutputSwitcherEnable: "Cambia uscite con scorciatoia",
        soundOutputSwitcherCaption: "Scegli le uscite e usa la scorciatoia per passare alla prossima disponibile.",
        soundOutputSwitcherDevices: "Uscite nel ciclo",
        soundOutputSwitcherNoAvailableSelection: "Seleziona almeno un'uscita disponibile.",
        mixerInputTitle: "Microfono",
        mixerInputNoDevices: "Nessun microfono trovato",
        mixerInputUnavailable: "Microfono non disponibile",
        mixerInputFallback: "Uso il predefinito finché questo microfono non torna.",
        mixerInputTooltip: "Scegli microfono",
        mixerInputErrorFormat: "Impossibile cambiare: %@",

        updatesSection: "Aggiornamenti",
        autoCheckToggle: "Cerca aggiornamenti automaticamente",
        checkNowButton: "Cerca ora",
        updateChecking: "Ricerca…",
        updateUpToDate: "Hai la versione più recente.",
        updateAvailablePrefix: "Aggiornamento disponibile:",
        updateInstallButton: "Scarica e installa",
        updateDownloading: "Download dell'aggiornamento…",
        updateInstalling: "Installazione e riavvio…",
        updateFailedPrefix: "Impossibile verificare:",
        updateLastChecked: "Ultima verifica:",
        updateNotifyTitle: "Aggiornamento di Vorssaint",
        menuCheckUpdates: "Cerca aggiornamenti…",

        permissionRequired: "Autorizzazione richiesta",
        permissionAccessibility: "Accessibilità",
        permissionScreenRecording: "Registrazione schermo",
        permissionGranted: "Concessa",
        permissionMissing: "Non concessa",
        permissionOpenSettings: "Apri Impostazioni di Sistema…",
        permissionRequest: "Concedi accesso",
        permissionRestartNote: "macOS potrebbe chiedere di riaprire l'app dopo la concessione.",

        aboutDescription: "Un centro di utilità per il tuo Mac.\nEnergia, monitoraggio del sistema, scorrimento e un commutatore di finestre, direttamente nella barra dei menu.",
        versionPrefix: "Versione",
        reviewIntro: "Rivedi l'introduzione",
        viewOnGitHub: "Vedi su GitHub",

        obContinue: "Continua",
        obBack: "Indietro",
        obSkipStep: "Salta questo passaggio",
        obStart: "Apri Vorssaint",
        obStepWelcomeTitle: "Ti diamo il benvenuto in Vorssaint",
        obStepWelcomeBody: "Un'utilità discreta nella barra dei menu che rende macOS più pratico ogni giorno.",
        obWelcomeBullet1Title: "Energia sotto controllo",
        obWelcomeBullet1Body: "Mantieni il Mac attivo per tutto il tempo che vuoi, anche con il coperchio chiuso.",
        obWelcomeBullet2Title: "Una visione chiara del sistema",
        obWelcomeBullet2Body: "Temperature di CPU, GPU e batteria, utilizzo dell'hardware e pressione della memoria in tempo reale.",
        obWelcomeBullet3Title: "Mouse e finestre come piacciono a te",
        obWelcomeBullet3Body: "Scorrimento invertito del mouse e un commutatore di finestre con miniature.",
        obLanguageLabel: "Lingua",
        obStepAccessibilityTitle: "Accessibilità",
        obStepAccessibilityBody: "Necessaria per invertire lo scorrimento del mouse e perché il commutatore di finestre risponda alla tastiera.",
        obAccessibilityWhy: "L'app si limita a osservare la rotellina del mouse e la scorciatoia del commutatore. Nulla viene registrato o inviato altrove.",
        obStepRecordingTitle: "Registrazione schermo",
        obStepRecordingBody: "Consente al commutatore di mostrare miniature reali delle finestre invece delle sole icone.",
        obRecordingWhy: "Le miniature vengono generate al momento, restano in memoria e non lasciano mai il tuo Mac. Senza, il commutatore funziona comunque con le icone.",
        obStepMonitorTitle: "Monitoraggio del sistema",
        obStepMonitorBody: "Il pannello mostra le temperature di CPU, GPU e batteria, l'utilizzo dell'hardware e la pressione della memoria.",
        obMonitorNoPermission: "Nessuna autorizzazione necessaria. I sensori vengono letti direttamente dal sistema.",
        obStepOptionalTitle: "Funzioni opzionali",
        obStepOptionalBody: "Attiva ora ciò che vuoi usare. Puoi cambiare tutto in seguito nelle Impostazioni.",
        obStepStatusTitle: "Controllo",
        obStepStatusBody: "Assicurati che sia tutto pronto per le funzioni che vuoi usare.",
        obStatusRecheck: "Controlla di nuovo",
        obStepDoneTitle: "Tutto pronto!",
        obStepDoneBody: "Vorssaint si sta già prendendo cura del tuo Mac.",
        obDoneHint: "Cerca il buco nero nella barra dei menu, in alto a destra dello schermo.",
        obWhatsNewTitle: "Novità di questa versione",
        obWhatsNewFallback: "Questo aggiornamento include le correzioni e i miglioramenti più recenti.",
        obLanguageUpdateTitle: "Ora nella tua lingua",
        obLanguageUpdateBody: "Vorssaint ora parla diverse lingue. Scegli quella che vuoi usare; puoi cambiarla quando vuoi nelle Impostazioni.",

        tabMonitor: "Monitoraggio",
        monitorMenuBarSection: "Nella barra dei menu",
        monitorMenuBarCaption: "Scegli cosa appare accanto all'icona nella barra dei menu.",
        monitorCombineTemperatures: "Combina uso e temperatura",
        monitorCombineTemperaturesCaption: "Quando uso e temperatura dello stesso elemento sono attivi, vengono mostrati in un solo blocco.",
        monitorSeparateMenuBarMetrics: "Separa le metriche in elementi propri",
        monitorSeparateMenuBarMetricsCaption: "Separa i blocchi attivi nella barra dei menu e tiene insieme utilizzo e temperatura quando combina è attivo.",
        monitorShowCPU: "CPU",
        monitorShowMemory: "Memoria",
        monitorShowNetwork: "Rete",
        monitorShowPowerLabel: "Energia",
        monitorIntervalLabel: "Aggiorna ogni",
        monitorInterval1: "1 secondo",
        monitorInterval2: "2 secondi",
        monitorInterval5: "5 secondi",
        monitorPanelSection: "Nel pannello",
        panelNavigationMode: "Naviga il pannello per sezioni",
        panelNavigationCaption: "Mostra una sezione alla volta e posiziona la navigazione in basso nel pannello.",
        panelFooterSections: "Sezioni",
        panelFooterList: "Lista",
        fanControlBetaShow: "Mostra Fan Control (Beta) nel pannello",
        fanControlBetaSection: "Fan Control",
        fanControlBetaTitle: "Fan Control",
        fanControlBetaStatus: "Automatico",
        fanControlBetaCaption: "Beta. Il controllo manuale resta disattivato finché ogni modello di Mac non viene validato.",
        fanControlModeAutomatic: "Automatico",
        fanControlModeManual: "Manuale",
        betaBadge: "BETA",
        betaFeatureWarning: "Beta. Potresti riscontrare alcuni bug.",

        networkSection: "Rete",
        networkDownload: "Download",
        networkUpload: "Upload",
        networkThisSession: "In questa sessione",
        networkMeasuring: "Misurazione…",

        diskSection: "Dischi",
        diskUsed: "usato",
        diskFree: "libero",
        diskInternal: "Interno",
        diskExternal: "Esterno",
        diskSelect: "Scegli disco",
        diskRead: "Lettura",
        diskWrite: "Scrittura",
        diskSMARTStatus: "Stato",
        diskSMARTUnavailable: "SMART non disponibile per questo disco",
        diskTotalRead: "Totale letto",
        diskTotalWritten: "Totale scritto",
        diskTemperature: "Temperatura",
        diskHealth: "Salute",
        diskPowerCycles: "Cicli",
        diskPowerOnHours: "Ore acceso",
        diskUnsafeShutdowns: "Spegnimenti non sicuri",
        diskMediaErrors: "Errori supporto",
        diskEject: "Espelli",
        diskEjectAll: "Espelli tutti",
        diskEjecting: "Espulsione…",
        diskReadyToRemove: "Pronto da rimuovere",
        diskEjectFailed: "Impossibile espellere",
        diskProtectionCaption: "Espelli prima di scollegare.",
        diskNoExternal: "Nessun disco esterno pronto da espellere.",
        diskOpenInFinder: "Apri",
        diskStorageSettings: "Archiviazione",
        diskNoDisks: "Nessun disco montato trovato.",

        powerSection: "Energia",
        powerSystem: "Sistema",
        powerAdapter: "Alimentatore",
        powerBattery: "Batteria",
        powerCharging: "In carica",
        powerOnBattery: "A batteria",
        powerPluggedIn: "Collegato",
        powerUnavailable: "Metriche di energia non disponibili su questo Mac",
        powerAdapterMaxFormat: "%@ max",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "Temperatura CPU",
        monitorShowGPUTemperature: "Temperatura GPU",
        monitorShowBatteryTemperature: "Temperatura batteria",
        monitorGraphsSection: "Grafici",
        monitorGraphsCaption: "Scegli quali metriche mostrano un grafico nel tempo.",

        updateBannerTitle: "Aggiornamento disponibile",
        updateBannerAction: "Aggiorna",
        obStepMenuBarTitle: "Metriche nella barra dei menu",
        obStepMenuBarBody: "Scegli cosa mostrare accanto all'icona. L'anteprima qui sopra si aggiorna in tempo reale.",
        obStepMenuBarNote: "Novità: blocchi Rete ed Energia e grafici nel pannello. Regola tutto in seguito in Impostazioni › Monitoraggio.",
        monitorMenuBarPresetLabel: "Stile",
        menuBarPresetReadable: "Leggibile",
        menuBarPresetDense: "Denso",
        monitorLabelStyleLabel: "Etichette",
        menuBarLabelStyleCompact: "Compatte",
        menuBarLabelStyleClassic: "Classiche",
        monitorMemoryStyleLabel: "Mostra la memoria come",
        monitorMemoryPressureDot: "Punto pressione",
        memoryStyleDot: "Punto",
        memoryStylePercent: "%",
        memoryStyleBoth: "Entrambi",

        systemUptime: "Attivo da",
        powerHealth: "Stato batteria",
        powerCycles: "cicli",
        speedTestRun: "Test velocità",
        speedTestAgain: "Ripeti il test",
        speedTestLatency: "Latenza",
        speedTestTesting: "Test in corso…",
        speedTestFailed: "Test non riuscito",

        monitorShowInPanel: "Mostra nel pannello",
        panelHideItem: "Nascondi dal pannello",
        panelShowItem: "Mostra nel pannello",
        panelHiddenItem: "Nascosto",
        monitorItemUptime: "Tempo di attività",
        monitorItemNetSpeed: "Velocità in tempo reale",
        monitorItemNetTotals: "Totali della sessione",
        monitorItemNetTest: "Test velocità",
        monitorItemDiskUsage: "Uso disco",
        monitorItemDiskActivity: "Attività in tempo reale",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "Protezione esterna",
        monitorItemDiskTools: "Strumenti",
        monitorPanelConfigHint: "Apri un blocco per scegliere cosa mostra.",
        monitorOrderSection: "Ordine delle sezioni",
        monitorOrderHint: "Trascina per riordinare le sezioni del pannello e usa l'occhio per mostrarne o nasconderne ognuna.",
        obStepPanelTitle: "Cosa appare nel pannello",
        obStepPanelBody: "Apri ogni blocco e scegli esattamente cosa mostrare quando fai clic sull'icona.",
        obStepPanelNavigationTitle: "Pannello per sezioni",
        obStepPanelNavigationBody: "Il pannello ora può mostrare una sezione alla volta, con la navigazione in basso. L'opzione è attiva in questo aggiornamento così puoi provarla.",

        cleaningMenuItem: "Modalità pulizia",
        utilitiesSection: "Utilità",
        quickControlsSection: "Controlli",
        windowMaximizeName: "Massimizza finestre",
        windowMaximizeCaption: "Il pulsante verde massimizza senza creare un altro Spazio.",
        windowMaximizeActiveNow: "Pulsante verde attivo",
        windowMaximizeNeedsAccessibility: "Richiede Accessibilità per funzionare.",
        cleaningPanelCaption: "Blocca la tastiera per pulire in sicurezza.",
        cleaningOverlayTitle: "Tastiera bloccata per la pulizia",
        cleaningOverlaySubtitle: "Premi 5 volte lo stesso tasto per sbloccare",
        cleaningOverlayUnlock: "Sblocca",
        cleaningOverlayMouseHint: "Mouse e trackpad continuano a funzionare",
        cleaningNeedsAxTitle: "Serve l'Accessibilità",
        cleaningNeedsAxBody: "Per bloccare la tastiera in sicurezza, Vorssaint ha bisogno dell'autorizzazione di Accessibilità. Concedila in Impostazioni di Sistema e riprova.",

        tabSupport: "Sostieni",
        donateHeading: "Sostieni Vorssaint",
        donateMessage: "Ogni mio progetto pubblico è, e sarà sempre, completamente gratuito: nessun abbonamento, nessuna pubblicità. Il sostegno della community è l'unica cosa che lo tiene in vita. Se Vorssaint ti è utile, un caffè fa davvero la differenza.",
        donateButton: "Buy me a coffee",
        donateThanks: "Grazie di essere qui. 🖤",
        supportIntroTitle: "Vorssaint è gratis al 100% e lo sarà sempre",
        supportIntroMessage: "Continuo a prendermi cura dell'app nel mio tempo libero. Se ti aiuta, puoi aiutarmi in modo semplice condividendola, lasciando una stella su GitHub o offrendomi un caffè. Mi aiuta tantissimo a continuare a migliorarla.",
        supportIntroStarButton: "Lascia una stella",
        supportIntroCoffeeButton: "Buy me a coffee",
        supportIntroLaterButton: "Non ora",
        showMenuBarIcon: "Mostra l'icona nella barra dei menu",
        showMenuBarIconCaption: "Se l'icona di Vorssaint scompare (macOS può nascondere le icone della barra dei menu quando lo spazio finisce, cosa comune sui Mac con notch), riapri Vorssaint da Applicazioni o da Spotlight: questo ricrea l'icona e, se è ancora nascosta, apre questa finestra. Il pulsante qui sopra fa lo stesso quando riesci già ad arrivare fin qui. Tenere meno icone nella barra dei menu, o meno metriche in Vorssaint, riduce di molto questa eventualità.",
        shortcutRecording: "Premi la nuova scorciatoia",
        shortcutReset: "Ripristina",
        shortcutInvalid: "Usa almeno Control, Option o Command insieme a un tasto.",
        shortcutConflictFormat: "Questa scorciatoia è già usata da %@.",
        shortcutUnavailable: "macOS ha rifiutato questa scorciatoia. Scegline un'altra.",
        shelfShortcutToggle: "Scorciatoia Shelf",
        switcherUsageHintFormat: "Tieni premuto %@ per spostarti; rilascia per attivare la finestra. Maiuscole o ← torna indietro; Q chiude l'app selezionata; Esc annulla."
    )
}
