// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// Français — translated and hand-checked, not machine output.
extension Strings {
    static let fr = Strings(
        statusIdleTooltip: "Vorssaint : veille normale",
        statusActiveUntil: "Vorssaint : éveillé jusqu’à",
        statusActiveIndefinite: "Vorssaint : éveillé indéfiniment",
        menuEnableAwake: "Activer le maintien éveillé",
        menuDisableAwake: "Désactiver le maintien éveillé",
        menuActivateFor: "Activer pour…",
        menuSettings: "Réglages…",
        menuAbout: "À propos de Vorssaint",
        menuQuit: "Quitter Vorssaint",
        menuHide: "Masquer Vorssaint",
        menuHideOthers: "Masquer les autres",
        menuShowAll: "Tout afficher",
        menuEdit: "Édition",
        menuUndo: "Annuler",
        menuRedo: "Rétablir",
        menuCut: "Couper",
        menuCopy: "Copier",
        menuPaste: "Coller",
        menuSelectAll: "Tout sélectionner",
        menuWindow: "Fenêtre",
        menuMinimize: "Réduire",
        menuZoom: "Zoom",
        menuClose: "Fermer",

        minutes15: "15 minutes",
        minutes30: "30 minutes",
        hour1: "1 heure",
        hours2: "2 heures",
        hours4: "4 heures",
        hours8: "8 heures",
        indefinitely: "Indéfiniment",
        indefinite: "Indéfinie",

        panelAwake: "Mac éveillé",
        panelNormalSleep: "Veille normale",
        panelActiveBadge: "ACTIF",
        panelSettings: "Réglages",
        panelQuit: "Quitter",
        panelHotkeyHint: "⌃⌥⌘K bascule",

        keepAwakeTitle: "Garder éveillé",
        keepAwakeEndsIn: "Se termine dans",
        keepAwakeUntilDisabled: "Actif jusqu’à ce que vous le désactiviez",
        keepAwakeNormalRules: "Le Mac suit ses règles d’énergie normales",
        durationLabel: "Durée",
        clamshellTitle: "Continuer écran rabattu",
        clamshellOnCaption: "Veille entièrement désactivée. Attention à l’énergie",
        clamshellNeedsSession: "Appliqué dès que « Garder éveillé » est actif",
        clamshellReady: "Prêt. Bascule sans mot de passe",
        clamshellNeedsPassword: "Demandera le mot de passe administrateur à l’activation",

        systemSection: "Système",
        temperatures: "Températures",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "Batterie",
        usageSection: "Utilisation du matériel",
        memorySection: "Mémoire",
        memoryPressure: "Pression",
        pressureNormal: "Normale",
        pressureWarning: "Attention",
        pressureCritical: "Critique",
        monitorUnavailable: "Capteurs indisponibles sur ce Mac",

        notifySessionEndedTitle: "Session terminée",
        notifySessionEndedBody: "Le temps est écoulé. Le Mac se remettra en veille normalement.",
        notifyBatteryTitle: "Vorssaint désactivé",
        notifyBatteryBody: "Batterie faible. La veille normale a été rétablie pour préserver la charge.",

        adminPromptClamshellOn: "Vorssaint a besoin de votre mot de passe pour garder le Mac éveillé écran rabattu. Désactivez cette demande dans l’introduction de l’app (Réglages › À propos).",
        adminPromptClamshellOff: "Vorssaint a besoin de votre mot de passe pour rétablir la veille normale du Mac.",
        adminPromptRecover: "Vorssaint a quitté alors que la veille du Mac était désactivée. Saisissez le mot de passe pour rétablir la veille normale.",
        adminPromptSudoersInstall: "Vorssaint va créer une règle restreinte (pmset disablesleep uniquement) pour basculer le mode écran rabattu sans demander de mot de passe. C’est la seule fois où le mot de passe est nécessaire.",
        adminPromptSudoersRemove: "Vorssaint va supprimer la règle d’écran rabattu sans mot de passe.",

        settingsTitle: "Réglages de Vorssaint",
        tabGeneral: "Général",
        tabEnergy: "Énergie",
        tabMouse: "Souris",
        tabSwitcher: "Sélecteur",
        tabAdvanced: "Avancé",
        tabAbout: "À propos",
        settingsGroupFeatures: "Fonctionnalités",
        advancedResetSection: "Autorisations",
        advancedResetDescription: "Retire toutes les autorisations que vous avez accordées à Vorssaint (Accessibilité, Enregistrement de l’écran, Accès complet au disque et autres), l’élément d’ouverture et la règle d’écran rabattu. Utile pour repartir de zéro ou avant de désinstaller. L’app reste installée.",
        advancedClearButton: "Effacer toutes les autorisations",
        advancedCleared: "Autorisations effacées.",
        advancedClearConfirmTitle: "Effacer toutes les autorisations ?",
        advancedClearConfirmBody: "Les fonctionnalités qui nécessitent des autorisations cesseront de fonctionner jusqu’à ce que vous les accordiez à nouveau. Vos réglages sont conservés.",
        advancedUninstallSection: "Désinstaller",
        advancedUninstallDescription: "Fait tout ce qui précède, puis supprime les préférences et place Vorssaint dans la corbeille, sans rien laisser. L’app quitte une fois terminé. Vous pouvez réinstaller à tout moment.",
        advancedUninstallButton: "Désinstaller complètement Vorssaint",
        advancedUninstallConfirmTitle: "Désinstaller Vorssaint ?",
        advancedUninstallConfirmBody: "Vorssaint va effacer ses autorisations, supprimer ses préférences et se placer dans la corbeille, puis quitter. L’app ne peut pas annuler cette action, mais elle reste dans la corbeille jusqu’à ce que vous la vidiez.",

        launchAtLogin: "Ouvrir à l’ouverture de session",
        languageLabel: "Langue",
        menuBarSection: "Barre des menus",
        showCountdown: "Afficher le temps restant à côté de l’icône",
        globalHotkeySection: "Raccourci global",
        hotkeyToggle: "Basculer « Garder éveillé » avec ⌃⌥⌘K",
        hotkeyCaption: "Fonctionne dans toutes les apps, sans autorisation supplémentaire.",

        sessionSection: "Session",
        defaultDurationLabel: "Durée par défaut",
        batteryProtectionSection: "Protection de la batterie",
        batteryDisableBelow: "Désactiver lorsque la batterie passe sous",
        batteryNever: "Jamais",
        batteryProtectionCaption: "Empêche une session oubliée de vider la batterie du MacBook.",
        clamshellSection: "Écran rabattu",
        configuring: "Configuration…",
        sudoersFailed: "Impossible de terminer. Vérifiez le mot de passe et réessayez.",
        clamshellExplanation: "« Continuer écran rabattu » désactive entièrement la veille tant que « Garder éveillé » est actif et se rétablit automatiquement à la fin de la session ou quand l’app quitte. À privilégier branché sur secteur.",

        scrollSection: "Défilement",
        invertMouseScroll: "Inverser le défilement de la souris",
        invertMouseScrollCaption: "Inverse le sens de la molette de la souris.",
        scrollTrackpadNote: "Le trackpad n’est pas affecté : il conserve le défilement naturel de macOS.",
        scrollActiveNow: "Inversion du défilement de la souris en cours",

        switcherSection: "Sélecteur d’apps",
        switcherEnable: "Remplacer ⌘Tab par le sélecteur Vorssaint",
        switcherEnableCaption: "Changez de fenêtre avec de vraies miniatures, y compris entre plusieurs fenêtres de la même app.",
        switcherUsageHint: "Maintenez ⌘ et appuyez sur Tab pour naviguer ; relâchez pour activer la fenêtre. Maj ou ← revient en arrière ; Q quitte l’app sélectionnée ; Échap annule.",
        switcherNoWindows: "Aucune fenêtre ouverte",
        switcherMergeTabs: "Afficher une seule entrée par app",
        switcherMergeTabsCaption: "Regroupe toutes les fenêtres d’une app en une seule entrée dans le sélecteur, au lieu d’une entrée par fenêtre.",

        cutPasteName: "Couper-coller",
        cutPasteEnable: "Couper-coller des fichiers dans le Finder",
        cutPasteEnableCaption: "Utilisez ⌘X pour couper et ⌘V pour déplacer des fichiers et des dossiers dans le Finder.",
        cutPasteHowTitle: "Comment l’utiliser",
        cutPasteStep1: "Sélectionnez des éléments dans le Finder et appuyez sur ⌘X pour les couper.",
        cutPasteStep2: "Ouvrez le dossier de destination et appuyez sur ⌘V pour les y déplacer.",
        cutPasteTextNote: "Dans les champs de texte (comme lors d’un renommage), ⌘X et ⌘V continuent de fonctionner normalement.",
        cutPasteActiveNow: "Prêt à couper dans le Finder",
        cutPasteAutomationNote: "La première fois, macOS demande l’autorisation de contrôler le Finder.",
        cutReadyTitle: "Coupé",
        cutReadyHint: "dans le dossier de destination pour déplacer",
        cutDoneTitle: "Déplacé !",
        cutMovedSingular: "1 élément déplacé",
        cutMovedPluralFormat: "%d éléments déplacés",
        cutSomeFailed: "Certains éléments n’ont pas pu être déplacés",

        autoQuitName: "Quitter à la fermeture",
        autoQuitEnable: "Quitter une app à la fermeture de sa dernière fenêtre",
        autoQuitEnableCaption: "Fermer la dernière fenêtre d’une app la fait aussi quitter.",
        autoQuitActiveNow: "Actif et à l’écoute des fenêtres",
        autoQuitHowTitle: "Comment ça marche",
        autoQuitStep1: "Fermez la dernière fenêtre d’une app (⌘W ou le bouton rouge).",
        autoQuitStep2: "L’app quitte d’elle-même. Les fenêtres « Enregistrer les modifications ? » s’affichent toujours.",
        autoQuitPredictableNote: "Les apps qui fonctionnent normalement sans fenêtre ne quittent jamais.",
        autoQuitExceptionsTitle: "Exceptions",
        autoQuitExceptionsCaption: "Les apps de cette liste restent ouvertes même sans aucune fenêtre.",
        autoQuitExceptionsEmpty: "Aucune exception",
        autoQuitAddApp: "Ajouter une app…",

        uninstallerName: "Programme de désinstallation",
        uninstallerEnableCaption: "Retire une app avec les caches, les préférences, les journaux et les résidus qu’elle laisse derrière elle.",
        uninstallerStep1: "Glissez une app sur les Réglages, ou choisissez-en une dans la liste.",
        uninstallerStep2: "Examinez les fichiers trouvés et l’espace qu’ils occupent.",
        uninstallerStep3: "Placez ce que vous voulez dans la corbeille. Rien n’est supprimé définitivement.",
        uninstallerMenuItem: "Désinstaller une app…",
        uninstallerDropTitle: "Glissez une app ici",
        uninstallerDropSubtitle: "ou choisissez-en une à analyser",
        uninstallerChoose: "Choisir une app…",
        uninstallerEmptyNote: "Rien n’est retiré sans votre confirmation.",
        uninstallerFDANote: "Accordez l’Accès complet au disque pour une analyse plus approfondie.",
        uninstallerFDAGrant: "Accorder l’accès…",
        uninstallerFDAHint: "Activez Vorssaint dans la liste. S’il ne s’y trouve pas, cliquez sur + et choisissez Vorssaint dans Applications. L’accès ne s’applique qu’après la réouverture de l’app.",
        uninstallerFDARelaunch: "Relancer maintenant",
        uninstallerScanning: "Analyse des fichiers…",
        uninstallerRemoving: "Déplacement vers la corbeille…",
        uninstallerFoundTitle: "trouvé",
        uninstallerSelectedFormat: "%d sur %d sélectionnés",
        uninstallerRemove: "Placer dans la corbeille",
        uninstallerCancel: "Annuler",
        uninstallerDoneTitle: "Terminé !",
        uninstallerFreedFormat: "%@ récupérés",
        uninstallerSomeFailed: "Certains éléments n’ont pas pu être placés dans la corbeille.",
        uninstallerAnother: "Désinstaller une autre app",
        uninstallerCatApp: "Application",
        uninstallerCatSupport: "Assistance",
        uninstallerCatCaches: "Caches",
        uninstallerCatPreferences: "Préférences",
        uninstallerCatContainers: "Conteneurs",
        uninstallerCatLogs: "Journaux",
        uninstallerCatState: "État enregistré",
        uninstallerCatOther: "Autres",

        shelfName: "Étagère",
        shelfEnable: "Espace temporaire pour glisser des fichiers",
        shelfEnableCaption: "Un espace flottant pour rassembler fichiers, images et texte, puis les glisser ailleurs plus tard.",
        shelfHowTitle: "Comment l’utiliser",
        shelfStep1: "Ouvrez-la avec ⌃⌥⌘D, ou en secouant la souris pendant un glissement.",
        shelfStep2: "Déposez-y des fichiers, des images, des liens ou du texte pour les conserver.",
        shelfStep3: "Glissez chaque élément vers n’importe quelle app au moment voulu.",
        shelfShakeToggle: "Ouvrir en secouant la souris pendant un glissement",
        shelfShakeCaption: "Secouez rapidement le pointeur tout en tenant un élément pour faire apparaître l’étagère près du curseur.",
        shelfHotkeyLabel: "Raccourci",
        shelfOpenNow: "Ouvrir maintenant",
        shelfNoPermission: "Ne nécessite aucune autorisation.",
        shelfMenuItem: "Ouvrir l’étagère",
        shelfTitle: "Étagère",
        shelfEmpty: "Glissez des éléments ici",
        shelfClearAll: "Tout effacer",
        shelfRemoveSelected: "Retirer la sélection",
        shelfSelectedFormat: "%d sélectionnés",
        shelfHint: "Cliquez pour sélectionner. Glissez vers l’extérieur pour utiliser.",
        shelfItemImage: "Image",

        breakdownMeasuring: "Mesure…",

        mixerSection: "Mélangeur de volume",
        mixerEmpty: "Les apps qui utilisent l’audio apparaissent ici",
        mixerUnavailable: "Disponible à partir de macOS 14.4",
        mixerPermissionBody: "Pour régler le volume par app, autorisez « Enregistrement de l’écran et de l’audio du système » dans les Réglages Système. L’audio n’est jamais enregistré.",
        mixerResetTooltip: "Rétablir à 100 %",

        updatesSection: "Mises à jour",
        autoCheckToggle: "Rechercher les mises à jour automatiquement",
        checkNowButton: "Rechercher maintenant",
        updateChecking: "Recherche…",
        updateUpToDate: "Vous disposez de la dernière version.",
        updateAvailablePrefix: "Mise à jour disponible :",
        updateInstallButton: "Télécharger et installer",
        updateDownloading: "Téléchargement de la mise à jour…",
        updateInstalling: "Installation et redémarrage…",
        updateFailedPrefix: "Recherche impossible :",
        updateLastChecked: "Dernière recherche :",
        updateNotifyTitle: "Mise à jour de Vorssaint",
        menuCheckUpdates: "Rechercher les mises à jour…",

        permissionRequired: "Autorisation requise",
        permissionAccessibility: "Accessibilité",
        permissionScreenRecording: "Enregistrement de l’écran",
        permissionGranted: "Accordée",
        permissionMissing: "Non accordée",
        permissionOpenSettings: "Ouvrir les Réglages Système…",
        permissionRequest: "Demander l’autorisation",
        permissionRestartNote: "macOS peut demander de rouvrir l’app après l’avoir accordée.",

        aboutDescription: "Un centre d’utilitaires pour votre Mac.\nÉnergie, moniteur système, défilement et sélecteur de fenêtres, directement dans la barre des menus.",
        versionPrefix: "Version",
        reviewIntro: "Revoir l’introduction",
        viewOnGitHub: "Voir sur GitHub",

        obContinue: "Continuer",
        obBack: "Retour",
        obSkipStep: "Passer cette étape",
        obStart: "Ouvrir Vorssaint",
        obStepWelcomeTitle: "Bienvenue dans Vorssaint",
        obStepWelcomeBody: "Un utilitaire discret dans la barre des menus qui rend macOS plus pratique au quotidien.",
        obWelcomeBullet1Title: "Énergie maîtrisée",
        obWelcomeBullet1Body: "Gardez le Mac éveillé aussi longtemps que vous le souhaitez, même écran rabattu.",
        obWelcomeBullet2Title: "Une vue claire du système",
        obWelcomeBullet2Body: "Températures du CPU, du GPU et de la batterie, utilisation du matériel et pression de la mémoire en temps réel.",
        obWelcomeBullet3Title: "Souris et fenêtres à votre façon",
        obWelcomeBullet3Body: "Défilement de souris inversé et un sélecteur de fenêtres avec miniatures.",
        obLanguageLabel: "Langue",
        obStepAccessibilityTitle: "Accessibilité",
        obStepAccessibilityBody: "Nécessaire pour inverser le défilement de la souris et pour que le sélecteur de fenêtres réponde au clavier.",
        obAccessibilityWhy: "L’app observe seulement la molette de la souris et le raccourci du sélecteur. Rien n’est enregistré ni envoyé où que ce soit.",
        obStepRecordingTitle: "Enregistrement de l’écran",
        obStepRecordingBody: "Permet au sélecteur d’afficher de vraies miniatures de fenêtres au lieu des seules icônes.",
        obRecordingWhy: "Les miniatures sont générées à la volée, restent en mémoire et ne quittent jamais votre Mac. Sans cela, le sélecteur fonctionne tout de même avec des icônes.",
        obStepMonitorTitle: "Moniteur système",
        obStepMonitorBody: "Le panneau affiche les températures du CPU, du GPU et de la batterie, l’utilisation du matériel et la pression de la mémoire.",
        obMonitorNoPermission: "Aucune autorisation nécessaire. Les capteurs sont lus directement depuis le système.",
        obStepOptionalTitle: "Fonctionnalités optionnelles",
        obStepOptionalBody: "Activez maintenant ce que vous voulez utiliser. Tout peut être modifié plus tard dans les Réglages.",
        obPasswordlessToggle: "Écran rabattu sans demande de mot de passe",
        obPasswordlessCaption: "Crée une règle système restreinte à « pmset disablesleep ». Le mot de passe administrateur est demandé une seule fois, maintenant.",
        obStepStatusTitle: "Vérification",
        obStepStatusBody: "Assurez-vous que tout est prêt pour les fonctionnalités que vous voulez utiliser.",
        obStatusRecheck: "Vérifier à nouveau",
        obStepDoneTitle: "Tout est prêt !",
        obStepDoneBody: "Vorssaint veille déjà sur votre Mac.",
        obDoneHint: "Cherchez le trou noir dans la barre des menus, en haut à droite de l’écran.",
        obWhatsNewTitle: "Nouveautés de cette version",
        obLanguageUpdateTitle: "Maintenant dans votre langue",
        obLanguageUpdateBody: "Vorssaint parle désormais plusieurs langues. Choisissez celle que vous voulez utiliser ; vous pouvez en changer à tout moment dans les Réglages.",

        tabMonitor: "Moniteur",
        monitorMenuBarSection: "Dans la barre des menus",
        monitorMenuBarCaption: "Choisissez ce qui apparaît à côté de l’icône dans la barre des menus.",
        monitorShowCPU: "CPU",
        monitorShowMemory: "Mémoire",
        monitorShowNetwork: "Réseau",
        monitorShowPowerLabel: "Énergie",
        monitorIntervalLabel: "Actualiser toutes les",
        monitorInterval1: "1 seconde",
        monitorInterval2: "2 secondes",
        monitorInterval5: "5 secondes",
        monitorPanelSection: "Dans le panneau",

        networkSection: "Réseau",
        networkDownload: "Téléchargement",
        networkUpload: "Envoi",
        networkThisSession: "Cette session",
        networkMeasuring: "Mesure…",

        powerSection: "Énergie",
        powerSystem: "Système",
        powerAdapter: "Adaptateur",
        powerBattery: "Batterie",
        powerCharging: "En charge",
        powerOnBattery: "Sur batterie",
        powerPluggedIn: "Branché",
        powerUnavailable: "Mesures d’énergie indisponibles sur ce Mac",
        powerAdapterMaxFormat: "%@ max",
        monitorShowGPU: "GPU",
        monitorGraphsSection: "Graphiques",
        monitorGraphsCaption: "Choisissez quelles mesures affichent un graphique dans le temps.",

        updateBannerTitle: "Mise à jour disponible",
        updateBannerAction: "Mettre à jour",
        obStepMenuBarTitle: "Mesures dans la barre des menus",
        obStepMenuBarBody: "Choisissez ce qui s’affiche à côté de l’icône. L’aperçu ci-dessus se met à jour en direct.",
        obStepMenuBarNote: "Nouveau : blocs Réseau et Énergie et graphiques dans le panneau. Ajustez le tout plus tard dans Réglages › Moniteur.",
        monitorMemoryStyleLabel: "Afficher la mémoire en",
        memoryStyleDot: "Point",
        memoryStylePercent: "%",
        memoryStyleBoth: "Les deux",

        systemUptime: "Actif depuis",
        powerHealth: "État de la batterie",
        powerCycles: "cycles",
        speedTestRun: "Test de débit",
        speedTestAgain: "Tester à nouveau",
        speedTestLatency: "Latence",
        speedTestTesting: "Test en cours…",
        speedTestFailed: "Échec du test",

        monitorShowInPanel: "Afficher dans le panneau",
        monitorItemUptime: "Durée d’activité",
        monitorItemNetSpeed: "Débit en direct",
        monitorItemNetTotals: "Totaux de la session",
        monitorItemNetTest: "Test de débit",
        monitorPanelConfigHint: "Ouvrez un bloc pour choisir ce qu’il affiche.",
        monitorOrderSection: "Ordre des sections",
        monitorOrderHint: "Glissez pour réordonner les sections du panneau. Utilisez le chevron de chaque section dans le panneau pour la replier.",
        obStepPanelTitle: "Ce qui s’affiche dans le panneau",
        obStepPanelBody: "Ouvrez chaque bloc et choisissez exactement ce qui s’affiche quand vous cliquez sur l’icône.",

        cleaningMenuItem: "Mode nettoyage",
        cleaningOverlayTitle: "Clavier verrouillé pour le nettoyage",
        cleaningOverlaySubtitle: "Appuyez 5 fois sur la même touche pour déverrouiller",
        cleaningOverlayUnlock: "Déverrouiller",
        cleaningOverlayMouseHint: "Votre souris et votre trackpad fonctionnent toujours",
        cleaningNeedsAxTitle: "Accessibilité requise",
        cleaningNeedsAxBody: "Pour verrouiller le clavier en toute sécurité, Vorssaint a besoin de l’autorisation Accessibilité. Accordez-la dans les Réglages Système et réessayez.",

        tabSupport: "Soutenir",
        donateHeading: "Soutenir Vorssaint",
        donateMessage: "Chacun de mes projets publics est, et sera toujours, entièrement gratuit : sans abonnement, sans publicité. Le soutien de la communauté est la seule chose qui le maintient en vie. Si Vorssaint vous aide, un café fait vraiment la différence.",
        donateButton: "Buy me a coffee",
        donateThanks: "Merci d’être là. 🖤",
        obStepDonateTitle: "Vous aimez Vorssaint ? 🖤",
        showMenuBarIcon: "Afficher l’icône dans la barre des menus",
        showMenuBarIconCaption: "Si l’icône de Vorssaint disparaît (macOS peut masquer des icônes lorsque la barre des menus manque de place, fréquent sur les Mac avec encoche), rouvrez Vorssaint depuis Applications ou Spotlight : cela recrée l’icône et, si elle reste masquée, ouvre cette fenêtre. Le bouton ci-dessus fait de même lorsque vous parvenez déjà jusqu’ici. Garder moins d’icônes dans la barre des menus, ou moins de mesures dans Vorssaint, réduit nettement le risque."
    )
}
